feat(general): add assert pre request task to the recipes

diff --git a/recipes/newrelic/cassandra/debian.yml b/recipes/newrelic/cassandra/debian.yml
--- a/recipes/newrelic/cassandra/debian.yml
+++ b/recipes/newrelic/cassandra/debian.yml
@@ -51,8 +51,18 @@ install:
   tasks:
     default:
       cmds:
+        - task: assert_pre_req
         - task: setup
         - task: restart
+
+    assert_pre_req:
+      cmds:
+        - |
+          SERVICE_EXIST=$(sudo systemctl status newrelic-infra.service | grep "Active" | wc -l)
+          if [ $SERVICE_EXIST -eq 0 ]; then
+            echo "The newrelic-infra agent service is NOT installed on the host, but is required to install this integration." >> /dev/stderr
+            exit 1
+          fi
 
     setup:
       label: "Installing cassandra integration..."
