add all distributions

diff --git a/recipes/newrelic/infrastructure/super-agent/debian.yml b/recipes/newrelic/infrastructure/super-agent/debian.yml
--- a/recipes/newrelic/infrastructure/super-agent/debian.yml
+++ b/recipes/newrelic/infrastructure/super-agent/debian.yml
@@ -158,6 +158,12 @@ install:
             exit 18
           fi
         - |
+          IS_MKTEMP_INSTALLED=$(which mktemp | wc -l)
+          if [ $IS_MKTEMP_INSTALLED -eq 0 ] ; then
+            echo "mktemp is required to run the newrelic install. Please install coreutils and re-run the installation." >&2
+            exit 19
+          fi
+        - |
           if [ -n "{{.DEBIAN_CODENAME}}" ]; then
             IS_AGENT_AVAILABLE=$(curl -Is {{.NEW_RELIC_DOWNLOAD_URL}}preview/linux/apt/dists/{{.DEBIAN_CODENAME}}/InRelease | grep " 2[0-9][0-9] " | wc -l)
             if [ $IS_AGENT_AVAILABLE -eq 0 ] ; then
@@ -429,13 +435,23 @@ install:
             sed -i '/^\s*#\s*endpoint: https:\/\/opamp/s/# //' /etc/newrelic-super-agent/config.yaml
           fi
         - |
-          if [ "{{.NEW_RELIC_SUPER_AGENT_FLEET_ENABLED}}" = "false" ] && [ "{{ .NEW_RELIC_ORGANIZATION }}" == "" ]; then
+          if [ "{{.NEW_RELIC_SUPER_AGENT_FLEET_ENABLED}}" = "false" ]; then
             sed -i '/^\s*api-key:/s/^/#/' /etc/newrelic-super-agent/config.yaml
             sed -i '/^\s*headers:/s/^/#/' /etc/newrelic-super-agent/config.yaml
           else
             sed -i '/^\s*#\s*api-key:/s/# //' /etc/newrelic-super-agent/config.yaml
             sed -i '/^\s*#\s*headers:/s/# //' /etc/newrelic-super-agent/config.yaml
           fi
+        - |
+          if [ "{{.NEW_RELIC_REGION}}" = "STAGING" ]; then
+            sed -i 's/\(endpoint: https:\/\/opamp.\).*/\1'"staging-service.newrelic.com\/v1\/opamp"'/' /etc/newrelic-super-agent/config.yaml
+          elif [ "{{.NEW_RELIC_REGION}}" = "EU" ]; then
+            sed -i 's/\(endpoint: https:\/\/opamp.\).*/\1'"service.eu.newrelic.com\/v1\/opamp"'/' /etc/newrelic-super-agent/config.yaml
+          else
+            sed -i 's/\(endpoint: https:\/\/opamp.\).*/\1'"service.newrelic.com\/v1\/opamp"'/' /etc/newrelic-super-agent/config.yaml
+          fi
+    config_super_agent_auth:
+      cmds:
         - |
           if [ "{{.NEW_RELIC_SUPER_AGENT_FLEET_ENABLED}}" = "false" ] && [ "{{ .NEW_RELIC_ORGANIZATION }}" != "" ]; then
             sed -i '/^\s*auth_config: PLACEHOLDER/s/^/#/' /etc/newrelic-super-agent/config.yaml
@@ -451,24 +467,14 @@ install:
             sed -i '/^\s*#\s*private_key_path: PLACEHOLDER/s/# //' /etc/newrelic-super-agent/config.yaml
           fi
         - |
-          if [ "{{.NEW_RELIC_REGION}}" = "STAGING" ]; then
-            sed -i 's/\(endpoint: https:\/\/opamp.\).*/\1'"staging-service.newrelic.com\/v1\/opamp"'/' /etc/newrelic-super-agent/config.yaml
-          elif [ "{{.NEW_RELIC_REGION}}" = "EU" ]; then
-            sed -i 's/\(endpoint: https:\/\/opamp.\).*/\1'"service.eu.newrelic.com\/v1\/opamp"'/' /etc/newrelic-super-agent/config.yaml
-          else
-            sed -i 's/\(endpoint: https:\/\/opamp.\).*/\1'"service.newrelic.com\/v1\/opamp"'/' /etc/newrelic-super-agent/config.yaml
-          fi
-    config_super_agent_auth:
-      cmds:
-        - |
           if [ "{{.NEW_RELIC_SUPER_AGENT_FLEET_ENABLED}}" != "false" ] && [ "{{ .NEW_RELIC_ORGANIZATION }}" != "" ]; then
-            set -o nounset,pipefail
+            set -uo pipefail
 
             mkdir /etc/newrelic-super-agent/keys
             chown root:root /etc/newrelic-super-agent/keys
             chmod 700 /etc/newrelic-super-agent/keys
 
-            TEMPORAL_FOLDER=$(mkdir -p "$TMP/super-agent-installation-$RANDOM")
+            TEMPORAL_FOLDER=$(mktemp -d newrelic-super-agent.XXXXXXXXXX)
             openssl genrsa -out "$TEMPORAL_FOLDER/key" 4096
             openssl rsa -in "$TEMPORAL_FOLDER/key" -pubout -out "$TEMPORAL_FOLDER/pub"
 
@@ -507,8 +513,6 @@ install:
                   -o "$TEMPORAL_FOLDER/response.json" \
                   --data @- \
                   "$REGISTRATION_ENDPOINT"
-                --data '{ "query": "mutation { createSystemIdentity(name: \"'${NAME}'\", organizationId: \"'${ORGANIZATION_ID}'\", publicKey: \"'$(openssl enc -base64 -A -in "$TEMPORAL_FOLDER/pub")'\") { id name organizationId clientId publicKey } }" }' \
-                ${REGISTRATION_ENDPOINT}
               )
 
               if [ $HTTP_CODE -eq 200 ]; then
diff --git a/recipes/newrelic/infrastructure/super-agent/suse.yml b/recipes/newrelic/infrastructure/super-agent/suse.yml
--- a/recipes/newrelic/infrastructure/super-agent/suse.yml
+++ b/recipes/newrelic/infrastructure/super-agent/suse.yml
@@ -67,6 +67,7 @@ install:
         - task: config_supervisors
         - task: config_fleet_id
         - task: config_opamp
+        - task: config_super_agent_auth
         - task: config_host_monitoring
         - task: update_otel_mem_limit
         - task: update_otel_end_point
@@ -123,6 +124,30 @@ install:
           if [ $IS_TOUCH_INSTALLED -eq 0 ] ; then
             echo "touch is required to run the newrelic install. Please install touch and re-run the installation." >&2
             exit 15
+          fi
+        - |
+          IS_CURL_INSTALLED=$(which curl | wc -l)
+          if [ $IS_CURL_INSTALLED -eq 0 ] ; then
+            echo "curl is required to run the newrelic install. Please install curl and re-run the installation." >&2
+            exit 16
+          fi
+        - |
+          IS_OPENSSL_INSTALLED=$(which openssl | wc -l)
+          if [ $IS_OPENSSL_INSTALLED -eq 0 ] ; then
+            echo "openssl is required to run the newrelic install. Please install openssl and re-run the installation." >&2
+            exit 17
+          fi
+        - |
+          IS_JQ_INSTALLED=$(which jq | wc -l)
+          if [ $IS_JQ_INSTALLED -eq 0 ] ; then
+            echo "jq is required to run the newrelic install. Please install jq and re-run the installation." >&2
+            exit 18
+          fi
+        - |
+          IS_MKTEMP_INSTALLED=$(which mktemp | wc -l)
+          if [ $IS_MKTEMP_INSTALLED -eq 0 ] ; then
+            echo "mktemp is required to run the newrelic install. Please install coreutils and re-run the installation." >&2
+            exit 19
           fi
         - |
           IS_INFRA_AVAILABLE=$(curl -Is {{.NEW_RELIC_DOWNLOAD_URL}}preview/linux/zypp/sles/{{.SLES_VERSION}}/x86_64/newrelic-infra.repo | grep " 2[0-9][0-9] " | wc -l)
@@ -291,16 +316,20 @@ install:
     config_opamp:
       cmds:
         - |
-          if [ "{{.NEW_RELIC_SUPER_AGENT_FLEET_ENABLED}}" = "false" ] ; then
+          if [ "{{.NEW_RELIC_SUPER_AGENT_FLEET_ENABLED}}" = "false" ]; then
             sed -i '/^\s*opamp:/s/^/#/' /etc/newrelic-super-agent/config.yaml
             sed -i '/^\s*endpoint: https:\/\/opamp/s/^/#/' /etc/newrelic-super-agent/config.yaml
+          else
+            sed -i 's/s*#\s*opamp:/opamp:/g' /etc/newrelic-super-agent/config.yaml
+            sed -i '/^\s*#\s*endpoint: https:\/\/opamp/s/# //' /etc/newrelic-super-agent/config.yaml
+          fi
+        - |
+          if [ "{{.NEW_RELIC_SUPER_AGENT_FLEET_ENABLED}}" = "false" ]; then
             sed -i '/^\s*api-key:/s/^/#/' /etc/newrelic-super-agent/config.yaml
             sed -i '/^\s*headers:/s/^/#/' /etc/newrelic-super-agent/config.yaml
           else
-            sed -i 's/s*#\s*opamp:/opamp:/g' /etc/newrelic-super-agent/config.yaml
-            sed -i '/^\s*#\s*endpoint: https:\/\/opamp/s/#//' /etc/newrelic-super-agent/config.yaml
-            sed -i '/^\s*#\s*api-key:/s/#//' /etc/newrelic-super-agent/config.yaml
-            sed -i '/^\s*#\s*headers:/s/#//' /etc/newrelic-super-agent/config.yaml
+            sed -i '/^\s*#\s*api-key:/s/# //' /etc/newrelic-super-agent/config.yaml
+            sed -i '/^\s*#\s*headers:/s/# //' /etc/newrelic-super-agent/config.yaml
           fi
         - |
           if [ "{{.NEW_RELIC_REGION}}" = "STAGING" ]; then
@@ -310,9 +339,97 @@ install:
           else
             sed -i 's/\(endpoint: https:\/\/opamp.\).*/\1'"service.newrelic.com\/v1\/opamp"'/' /etc/newrelic-super-agent/config.yaml
           fi
+
+    config_super_agent_auth:
+      cmds:
         - |
-          if [ "{{.NEW_RELIC_SUPER_AGENT_FLEET_ENABLED}}" != "false" ] ; then
-            sed -i 's/api-key: API_KEY_HERE/api-key: {{.NEW_RELIC_LICENSE_KEY}}/g' /etc/newrelic-super-agent/config.yaml
+          if [ "{{.NEW_RELIC_SUPER_AGENT_FLEET_ENABLED}}" = "false" ] && [ "{{ .NEW_RELIC_ORGANIZATION }}" != "" ]; then
+            sed -i '/^\s*auth_config: PLACEHOLDER/s/^/#/' /etc/newrelic-super-agent/config.yaml
+            # TODO: sed -i '/^\s*token_url: PLACEHOLDER/s/^/#/' /etc/newrelic-super-agent/config.yaml
+            sed -i '/^\s*client_id: PLACEHOLDER/s/^/#/' /etc/newrelic-super-agent/config.yaml
+            sed -i '/^\s*provider: PLACEHOLDER/s/^/#/' /etc/newrelic-super-agent/config.yaml
+            sed -i '/^\s*private_key_path: PLACEHOLDER/s/^/#/' /etc/newrelic-super-agent/config.yaml
+          else
+            sed -i '/^\s*#\s*auth_config: PLACEHOLDER/s/# //' /etc/newrelic-super-agent/config.yaml
+            # TODO: sed -i '/^\s*#\s*token_url: PLACEHOLDER/s/# //' /etc/newrelic-super-agent/config.yaml
+            sed -i '/^\s*#\s*client_id: PLACEHOLDER/s/# //' /etc/newrelic-super-agent/config.yaml
+            sed -i '/^\s*#\s*provider: PLACEHOLDER/s/# //' /etc/newrelic-super-agent/config.yaml
+            sed -i '/^\s*#\s*private_key_path: PLACEHOLDER/s/# //' /etc/newrelic-super-agent/config.yaml
+          fi
+        - |
+          if [ "{{.NEW_RELIC_SUPER_AGENT_FLEET_ENABLED}}" != "false" ] && [ "{{ .NEW_RELIC_ORGANIZATION }}" != "" ]; then
+            set -uo pipefail
+
+            mkdir /etc/newrelic-super-agent/keys
+            chown root:root /etc/newrelic-super-agent/keys
+            chmod 700 /etc/newrelic-super-agent/keys
+
+            TEMPORAL_FOLDER=$(mktemp -d newrelic-super-agent.XXXXXXXXXX)
+            openssl genrsa -out "$TEMPORAL_FOLDER/key" 4096
+            openssl rsa -in "$TEMPORAL_FOLDER/key" -pubout -out "$TEMPORAL_FOLDER/pub"
+
+            if [ "{{.NEW_RELIC_REGION}}" = "STAGING" ]; then
+              REGISTRATION_ENDPOINT=https://staging-iam-service.vip.cf.nr-ops.net/graphql
+              # TODO: TOKEN_RENEWAL_ENDPOINT
+            elif [ "{{.NEW_RELIC_REGION}}" = "EU" ]; then
+              REGISTRATION_ENDPOINT=https://iam-service.eu.vip.cf.nr-ops.net/graphql
+              # TODO: TOKEN_RENEWAL_ENDPOINT
+            else
+              REGISTRATION_ENDPOINT=https://iam-service.vip.cf.nr-ops.net/graphql
+              # TODO: TOKEN_RENEWAL_ENDPOINT
+            fi
+
+            NAME="System Identity for $(hostname)"
+
+            for RETRY in 1 2 3; do
+              HTTP_CODE=$(echo '{ "query":
+                  "{
+                    mutation createSystemIdentity {
+                      createSystemIdentity(
+                        name: \"'$NAME'\",
+                        organizationId: \"{{ .NEW_RELIC_ORGANIZATION }}\",
+                        publicKey: \"'$(openssl enc -base64 -A -in "$TEMPORAL_FOLDER/pub")'\"
+                      ) {
+                        clientId,
+                        id,
+                        name
+                      }
+                    }
+                  }"
+                }' | tr -d $'\n' | curl -X POST \
+                  -s -w "%{http_code}" \
+                  -H "Content-Type: application/json" \
+                  -H "api-key: {{ .NEW_RELIC_API_KEY }}" \
+                  -o "$TEMPORAL_FOLDER/response.json" \
+                  --data @- \
+                  "$REGISTRATION_ENDPOINT"
+              )
+
+              if [ $HTTP_CODE -eq 200 ]; then
+                break
+              fi
+
+              echo "Error creating the new system identity. The API endpoint returned $HTTP_CODE. Retrying ($RETRY/3)..."
+              sleep 2
+            done
+
+            ERROR_MESSAGE=$(jq -r '.errors[0].message // "NOERROR"' < "$TEMPORAL_FOLDER/response.json")
+            if [ "$ERROR_MESSAGE" != "NOERROR" ]; then
+              echo "Error creating an identity: $ERROR_MESSAGE"
+              exit
+            fi
+
+            CLIENT_ID=$(jq 'data.createSystemIdentity.clientId' < "$TEMPORAL_FOLDER/response.json")
+            ID=$(jq 'data.createSystemIdentity.id' < "$TEMPORAL_FOLDER/response.json")
+            NAME=$(jq 'data.createSystemIdentity.name' < "$TEMPORAL_FOLDER/response.json")
+
+            mv "$TEMPORAL_FOLDER/key" "/etc/newrelic-super-agent/keys/$CLIENT_ID.key"
+            # TODO: sed -i 's/token_url: PLACEHOLDER/token_url: '"$TOKEN_RENEWAL_ENDPOINT"'/g' /etc/newrelic-super-agent/config.yaml
+            sed -i 's/client_id: PLACEHOLDER/client_id: '"$CLIENT_ID"'/g' /etc/newrelic-super-agent/config.yaml
+            sed -i 's/provider: PLACEHOLDER/provider: local/g' /etc/newrelic-super-agent/config.yaml
+            sed -i 's/private_key_path: PLACEHOLDER/private_key_path: '"/etc/newrelic-super-agent/keys/$CLIENT_ID.key"'/g' /etc/newrelic-super-agent/config.yaml
+
+            rm -rf "$TEMPORAL_FOLDER"
           fi
 
     config_host_monitoring:
