fix: Super agent recipe final step check status endpoint and rename to Agent Control (#1102)
* Super agent recipe final step check status endpoint

* Rename Super Agent to Agent Control on all displays

* Refine the name for the Agent Control display

* Fix super-agent tests to look for new validated output

* Remove unsupported OS from the super-agent tests

diff --git a/recipes/newrelic/infrastructure/super-agent/debian.yml b/recipes/newrelic/infrastructure/super-agent/debian.yml
--- a/recipes/newrelic/infrastructure/super-agent/debian.yml
+++ b/recipes/newrelic/infrastructure/super-agent/debian.yml
@@ -2,8 +2,8 @@
 # https://github.com/newrelic/open-install-library/blob/main/docs/recipe-spec/recipe-spec.md#schema-definition
 
 name: super-agent
-displayName: New Relic Super Agent
-description: New Relic install recipe for the Super Agent
+displayName: Agent Control
+description: New Relic install recipe for Agent Control
 repository: https://github.com/newrelic/newrelic-super-agent
 
 installTargets:
@@ -92,7 +92,7 @@ install:
         - task: update_otel_end_point
         - task: migrate_newrelic_infra_config
         - task: restart_super_agent
-        - task: assert_super_agent_started
+        - task: assert_super_agent_status_ok
         - task: signal_recipe_applied
         - task: post_install
 
@@ -175,18 +175,18 @@ install:
           if [ -n "{{.DEBIAN_CODENAME}}" ]; then
             IS_AGENT_AVAILABLE=$(curl -Is {{.NEW_RELIC_DOWNLOAD_URL}}preview/linux/apt/dists/{{.DEBIAN_CODENAME}}/InRelease | grep " 2[0-9][0-9] " | wc -l)
             if [ $IS_AGENT_AVAILABLE -eq 0 ] ; then
-              echo "there is no newrelic super agent available for the distribution with codename '{{.DEBIAN_CODENAME}}'." >&2
+              echo "there is no New Relic Agent Control available for the distribution with codename '{{.DEBIAN_CODENAME}}'." >&2
               exit 131
             fi
           else
             if [ -n "{{.DEBIAN_VERSION_CODENAME}}" ]; then
               IS_INFRA_AVAILABLE=$(curl -Is {{.NEW_RELIC_DOWNLOAD_URL}}preview/linux/apt/dists/{{.DEBIAN_VERSION_CODENAME}}/InRelease | grep " 2[0-9][0-9] " | wc -l)
               if [ $IS_INFRA_AVAILABLE -eq 0 ] ; then
-                echo "there is no newrelic super agent available for the distribution with version codename '{{.DEBIAN_VERSION_CODENAME}}'." >&2
+                echo "there is no New Relic Agent Control available for the distribution with version codename '{{.DEBIAN_VERSION_CODENAME}}'." >&2
                 exit 131
               fi
             else
-              echo "there is no newrelic super agent available for the distribution, no version codename was found." >&2
+              echo "there is no New Relic Agent Control available for the distribution, no version codename was found." >&2
               exit 131
             fi
           fi
@@ -198,7 +198,7 @@ install:
 
     cleanup:
       # skipping this task if .nr-cli exists
-      status: 
+      status:
         - test -f /etc/newrelic-super-agent/.nr-cli
       cmds:
         - |
@@ -207,8 +207,8 @@ install:
           fi
 
     setup_infra_license:
-      status: 
-        - test -f /etc/newrelic-super-agent/.nr-cli 
+      status:
+        - test -f /etc/newrelic-super-agent/.nr-cli
       cmds:
         - |
           if [ "{{.NR_CLI_INFRA_AGENT}}" != "false" ] ; then
@@ -227,7 +227,7 @@ install:
               if [ "{{.NR_SA_MIGRATE_INFRA_CONFIG}}" == "true" ] || [ "{{.NEW_RELIC_ASSUME_YES}}" == "true" ] ; then
                 touch /etc/newrelic-infra-do-migrate
               else
-                printf "\nWould you like to migrate this newrelic-infra config to use it with the newrelic super agent? (y/N): "
+                printf "\nWould you like to migrate this newrelic-infra config to use it with New Relic Agent Control? (y/N): "
                 read -r MIGRATE_NEWRELIC_INFRA_CONFIG
                 MIGRATE_NEWRELIC_INFRA_CONFIG=${MIGRATE_NEWRELIC_INFRA_CONFIG:-N}
 
@@ -253,8 +253,8 @@ install:
             echo '{{.NRIA_CUSTOM_ATTRIBUTES}}' >> /etc/newrelic-infra.yml
           fi
     setup_infra_proxy:
-      status: 
-        - test -f /etc/newrelic-super-agent/.nr-cli 
+      status:
+        - test -f /etc/newrelic-super-agent/.nr-cli
       cmds:
         - |
           if [ "{{.NR_CLI_INFRA_AGENT}}" != "false" ] && [ ! -z "$HTTPS_PROXY" ]; then
@@ -368,9 +368,9 @@ install:
           fi
       silent: true
 
-    # If configured to do so, migrate the newrelic-infra configuration for usage with the super agent
+    # If configured to do so, migrate the newrelic-infra configuration for usage with New Relic Agent Control
     migrate_newrelic_infra_config:
-      status: 
+      status:
         - test -f /etc/newrelic-super-agent/.nr-cli
       cmds:
         - |
@@ -379,18 +379,18 @@ install:
             newrelic-config-migrate
           fi
 
-    # Add NR Ingest Key as ENV Var for the Super Agent Systemd service (used by Infra Agent and Otel)
+    # Add NR Ingest Key as ENV Var for the super-agent Systemd service (used by Infra Agent and Otel)
     update_otel_license_key:
-      status: 
-        - test -f /etc/newrelic-super-agent/.nr-cli 
+      status:
+        - test -f /etc/newrelic-super-agent/.nr-cli
       cmds:
         - |
           sed -i "/^NEW_RELIC_LICENSE_KEY/d" /etc/newrelic-super-agent/newrelic-super-agent.conf
           echo 'NEW_RELIC_LICENSE_KEY="{{.NEW_RELIC_LICENSE_KEY}}"' >> /etc/newrelic-super-agent/newrelic-super-agent.conf
 
     update_otel_mem_limit:
-      status: 
-        - test -f /etc/newrelic-super-agent/.nr-cli 
+      status:
+        - test -f /etc/newrelic-super-agent/.nr-cli
       cmds:
         - |
           if [ "{{.NR_CLI_NRDOT}}" != "false" ]; then
@@ -399,8 +399,8 @@ install:
 
     # Add OTLP Endpoint as ENV Var for the Super Agent Systemd service
     update_otel_end_point:
-      status: 
-        - test -f /etc/newrelic-super-agent/.nr-cli 
+      status:
+        - test -f /etc/newrelic-super-agent/.nr-cli
       cmds:
         - |
           if [ "{{.NR_CLI_NRDOT}}" != "false" ]; then
@@ -414,8 +414,8 @@ install:
           fi
 
     config_supervisors:
-      status: 
-        - test -f /etc/newrelic-super-agent/.nr-cli 
+      status:
+        - test -f /etc/newrelic-super-agent/.nr-cli
       cmds:
         - |
           if [ "{{.NR_CLI_INFRA_AGENT}}" = "false" ] && [ "{{.NR_CLI_NRDOT}}" = "false" ]; then
@@ -441,8 +441,8 @@ install:
           fi
 
     config_fleet_id:
-      status: 
-        - test -f /etc/newrelic-super-agent/.nr-cli 
+      status:
+        - test -f /etc/newrelic-super-agent/.nr-cli
       cmds:
         - |
           if [ ! -z "{{.NR_CLI_FLEET_ID}}" ] ; then
@@ -451,8 +451,8 @@ install:
           fi
 
     config_opamp:
-      status: 
-        - test -f /etc/newrelic-super-agent/.nr-cli 
+      status:
+        - test -f /etc/newrelic-super-agent/.nr-cli
       cmds:
         - |
           if [ "{{.NEW_RELIC_SUPER_AGENT_FLEET_ENABLED}}" = "false" ]; then
@@ -484,8 +484,8 @@ install:
           fi
 
     config_super_agent_auth:
-      status: 
-        - test -f /etc/newrelic-super-agent/.nr-cli 
+      status:
+        - test -f /etc/newrelic-super-agent/.nr-cli
       cmds:
         - |
           if [ "{{.NEW_RELIC_SUPER_AGENT_FLEET_ENABLED}}" != "false" ] && [ "{{ .NEW_RELIC_ORGANIZATION }}" != "" ]; then
@@ -579,8 +579,8 @@ install:
           fi
 
     config_host_monitoring:
-      status: 
-        - test -f /etc/newrelic-super-agent/.nr-cli 
+      status:
+        - test -f /etc/newrelic-super-agent/.nr-cli
       cmds:
         - |
           if [ "{{.NEW_RELIC_SUPER_AGENT_HOST_MONITORING_SOURCE}}" = "otel" ]; then
@@ -607,21 +607,45 @@ install:
             fi
           fi
 
-    assert_super_agent_started:
+    assert_super_agent_status_ok:
       cmds:
         - |
-          # Ensure super agent has enough time to start
-          sleep 10
-          IS_AGENT_INSTALLED=$(sudo ps aux | grep newrelic-super-agent | grep -v grep | wc -l)
-          if [ $IS_AGENT_INSTALLED -eq 0 ] ; then
-            echo "The newrelic super agent has not started after installing. Please try again later, or see our documentation for installing manually https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/install-configure/install-new-relic" >&2
-
-            if [ {{.IS_SYSTEMCTL}} -gt 0 ]; then
-              journalctl -u newrelic-super-agent --no-pager
+          MAX_RETRIES=150
+          TRIES=0
+          echo "Running agent status check attempt..."
+          # wait for status endpoint to be ready
+          while [ $TRIES -lt $MAX_RETRIES ]; do
+            ((TRIES++))
+            statusCheckOutput=$(curl -s http://localhost:51200/status)
+            if [ -z "$statusCheckOutput" ]; then
+              # so jq doesn't fail if empty
+              statusCheckOutput="{}"
             fi
-
-            exit 31
-          fi
+            STATUS=$(echo $statusCheckOutput | /usr/local/bin/newrelic utils jq '.super_agent.healthy')
+            if [ "$STATUS" == "true" ]; then
+              echo "Agent status check ok."
+              break
+            else
+              if [ "$TRIES" -eq "$MAX_RETRIES" ]; then
+                # Process-based validation attempt
+                IS_AGENT_INSTALLED=$(ps aux | grep newrelic-super-agent | grep -v grep | wc -l)
+                if [ $IS_AGENT_INSTALLED -gt 0 ] ; then
+                  echo "detected newrelic-super-agent process running"
+                  exit 0
+                fi
+                
+                echo "New Relic Agent Control has not started after installing. Please try again later, or see our documentation for installing manually https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/install-configure/install-new-relic" >&2
+                
+                if [ {{.IS_SYSTEMCTL}} -gt 0 ]; then
+                  journalctl -u newrelic-super-agent --no-pager
+                fi
+          
+                exit 31
+              fi
+            fi
+          
+            sleep 2
+          done
 
     signal_recipe_applied:
       cmds:
@@ -630,4 +654,4 @@ install:
 
     post_install:
       info: |2
-          ⚙️  The New Relic Super Agent configuration file can be found in /etc/newrelic-super-agent/config.yaml
+          ⚙️  New Relic Agent Control configuration file can be found in /etc/newrelic-super-agent/config.yaml
diff --git a/recipes/newrelic/infrastructure/super-agent/suse.yml b/recipes/newrelic/infrastructure/super-agent/suse.yml
--- a/recipes/newrelic/infrastructure/super-agent/suse.yml
+++ b/recipes/newrelic/infrastructure/super-agent/suse.yml
@@ -2,8 +2,8 @@
 # https://github.com/newrelic/open-install-library/blob/main/docs/recipe-spec/recipe-spec.md#schema-definition
 
 name: super-agent
-displayName: New Relic Super Agent
-description: New Relic install recipe for the Super Agent
+displayName: Agent Control
+description: New Relic install recipe for Agent Control
 repository: https://github.com/newrelic/newrelic-super-agent
 
 installTargets:
@@ -78,7 +78,7 @@ install:
         - task: update_otel_end_point
         - task: migrate_newrelic_infra_config
         - task: restart_super_agent
-        - task: assert_super_agent_started
+        - task: assert_super_agent_status_ok
         - task: signal_recipe_applied
         - task: post_install
 
@@ -160,7 +160,7 @@ install:
         - |
           IS_INFRA_AVAILABLE=$(curl -Is {{.NEW_RELIC_DOWNLOAD_URL}}preview/linux/zypp/sles/{{.SLES_VERSION}}/x86_64/newrelic-infra.repo | grep " 2[0-9][0-9] " | wc -l)
           if [ $IS_INFRA_AVAILABLE -eq 0 ] ; then
-            echo "there is no newrelic super agent available for the distribution '{{.SLES_VERSION}}'." >&2
+            echo "there is no New Relic Agent Control available for the distribution '{{.SLES_VERSION}}'." >&2
             exit 131
           fi
       vars:
@@ -169,15 +169,15 @@ install:
 
     cleanup:
       # skipping this task if .nr-cli exists
-      status: 
-        - test -f /etc/newrelic-super-agent/.nr-cli 
+      status:
+        - test -f /etc/newrelic-super-agent/.nr-cli
       cmds:
         - |
           rm -rf /var/db/newrelic-infra/data 2>/dev/null
 
     setup_infra_license:
-      status: 
-        - test -f /etc/newrelic-super-agent/.nr-cli 
+      status:
+        - test -f /etc/newrelic-super-agent/.nr-cli
       cmds:
         - |
           if [ "{{.NR_CLI_INFRA_AGENT}}" != "false" ] ; then
@@ -196,7 +196,7 @@ install:
               if [ "{{.NR_SA_MIGRATE_INFRA_CONFIG}}" == "true" ] || [ "{{.NEW_RELIC_ASSUME_YES}}" == "true" ] ; then
                 touch /etc/newrelic-infra-do-migrate
               else
-                printf "\nWould you like to migrate this newrelic-infra config to use it with the newrelic super agent? (y/N): "
+                printf "\nWould you like to migrate this newrelic-infra config to use it with New Relic Agent Control? (y/N): "
                 read -r MIGRATE_NEWRELIC_INFRA_CONFIG
                 MIGRATE_NEWRELIC_INFRA_CONFIG=${MIGRATE_NEWRELIC_INFRA_CONFIG:-N}
 
@@ -224,8 +224,8 @@ install:
           fi
 
     setup_infra_proxy:
-      status: 
-        - test -f /etc/newrelic-super-agent/.nr-cli 
+      status:
+        - test -f /etc/newrelic-super-agent/.nr-cli
       cmds:
         - |
           if [ "{{.NR_CLI_INFRA_AGENT}}" != "false" ] && [ ! -z "$HTTPS_PROXY" ]; then
@@ -240,7 +240,7 @@ install:
           SUPER_AGENT_REPO_URL=$(echo -n "{{.NEW_RELIC_DOWNLOAD_URL}}preview/linux/zypp/sles/{{.SLES_VERSION}}/$ARCH/newrelic-infra.repo")
           IS_NEWRELIC_AVAILABLE=$(curl -Ls $SUPER_AGENT_REPO_URL | grep "\[newrelic-infra\]" | wc -l)
           if [ $IS_NEWRELIC_AVAILABLE -eq 0 ] ; then
-            echo "newrelic super agent is not available for this architecture "$ARCH". See our documentation for installing manually https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/install-configure/install-new-relic" >&2
+            echo "New Relic Agent Control is not available for this architecture "$ARCH". See our documentation for installing manually https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/install-configure/install-new-relic" >&2
             exit 131
           fi
           INFRA_REPO_URL=$(echo -n "{{.NEW_RELIC_DOWNLOAD_URL}}infrastructure_agent/linux/zypp/sles/{{.SLES_VERSION}}/$ARCH/newrelic-infra.repo")
@@ -259,9 +259,9 @@ install:
           sh: awk -F= '/VERSION_ID/ {print $2}' /etc/os-release
       silent: true
 
-    # If configured to do so, migrate the newrelic-infra configuration for usage with the super agent
+    # If configured to do so, migrate the newrelic-infra configuration for usage with New Relic Agent Control
     migrate_newrelic_infra_config:
-      status: 
+      status:
         - test -f /etc/newrelic-super-agent/.nr-cli
       cmds:
         - |
@@ -271,26 +271,26 @@ install:
           fi
 
     update_otel_license_key:
-      status: 
-        - test -f /etc/newrelic-super-agent/.nr-cli 
+      status:
+        - test -f /etc/newrelic-super-agent/.nr-cli
       cmds:
         - |
           sed -i "/^NEW_RELIC_LICENSE_KEY/d" /etc/newrelic-super-agent/newrelic-super-agent.conf
           echo 'NEW_RELIC_LICENSE_KEY="{{.NEW_RELIC_LICENSE_KEY}}"' >> /etc/newrelic-super-agent/newrelic-super-agent.conf
 
     update_otel_mem_limit:
-      status: 
-        - test -f /etc/newrelic-super-agent/.nr-cli 
+      status:
+        - test -f /etc/newrelic-super-agent/.nr-cli
       cmds:
         - |
           if [ "{{.NR_CLI_NRDOT}}" != "false" ]; then
             sed -i "s/limit_mib: .*$/limit_mib: 100/g" /etc/newrelic-super-agent/fleet/agents.d/nr-otel-collector/values/values.yaml
           fi
 
-    # Add OTLP Endpoint as ENV Var for the Super Agent Systemd service
+    # Add OTLP Endpoint as ENV Var for the super-agent Systemd service
     update_otel_end_point:
-      status: 
-        - test -f /etc/newrelic-super-agent/.nr-cli 
+      status:
+        - test -f /etc/newrelic-super-agent/.nr-cli
       cmds:
         - |
           if [ "{{.NR_CLI_NRDOT}}" != "false" ]; then
@@ -304,8 +304,8 @@ install:
           fi
 
     config_supervisors:
-      status: 
-        - test -f /etc/newrelic-super-agent/.nr-cli 
+      status:
+        - test -f /etc/newrelic-super-agent/.nr-cli
       cmds:
         - |
           if [ "{{.NR_CLI_INFRA_AGENT}}" = "false" ] && [ "{{.NR_CLI_NRDOT}}" = "false" ]; then
@@ -331,8 +331,8 @@ install:
           fi
 
     config_fleet_id:
-      status: 
-        - test -f /etc/newrelic-super-agent/.nr-cli 
+      status:
+        - test -f /etc/newrelic-super-agent/.nr-cli
       cmds:
         - |
           if [ ! -z "{{.NR_CLI_FLEET_ID}}" ] ; then
@@ -341,8 +341,8 @@ install:
           fi
 
     config_opamp:
-      status: 
-        - test -f /etc/newrelic-super-agent/.nr-cli 
+      status:
+        - test -f /etc/newrelic-super-agent/.nr-cli
       cmds:
         - |
           if [ "{{.NEW_RELIC_SUPER_AGENT_FLEET_ENABLED}}" = "false" ]; then
@@ -374,8 +374,8 @@ install:
           fi
 
     config_super_agent_auth:
-      status: 
-        - test -f /etc/newrelic-super-agent/.nr-cli 
+      status:
+        - test -f /etc/newrelic-super-agent/.nr-cli
       cmds:
         - |
           if [ "{{.NEW_RELIC_SUPER_AGENT_FLEET_ENABLED}}" != "false" ] && [ "{{ .NEW_RELIC_ORGANIZATION }}" != "" ]; then
@@ -469,8 +469,8 @@ install:
           fi
 
     config_host_monitoring:
-      status: 
-        - test -f /etc/newrelic-super-agent/.nr-cli 
+      status:
+        - test -f /etc/newrelic-super-agent/.nr-cli
       cmds:
         - |
           if [ "{{.NEW_RELIC_SUPER_AGENT_HOST_MONITORING_SOURCE}}" = "otel" ]; then
@@ -497,21 +497,45 @@ install:
             fi
           fi
 
-    assert_super_agent_started:
+    assert_super_agent_status_ok:
       cmds:
         - |
-          # Ensure super agent has enough time to start
-          sleep 10
-          IS_AGENT_INSTALLED=$(sudo ps aux | grep newrelic-super-agent | grep -v grep | wc -l)
-          if [ $IS_AGENT_INSTALLED -eq 0 ] ; then
-            echo "The newrelic super agent has not started after installing. Please try again later, or see our documentation for installing manually https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/install-configure/install-new-relic" >&2
-
-            if [ {{.IS_SYSTEMCTL}} -gt 0 ]; then
-              journalctl -u newrelic-super-agent --no-pager
+          MAX_RETRIES=150
+          TRIES=0
+          echo "Running agent status check attempt..."
+          # wait for status endpoint to be ready
+          while [ $TRIES -lt $MAX_RETRIES ]; do
+            ((TRIES++))
+            statusCheckOutput=$(curl -s http://localhost:51200/status)
+            if [ -z "$statusCheckOutput" ]; then
+              # so jq doesn't fail if empty
+              statusCheckOutput="{}"
             fi
+            STATUS=$(echo $statusCheckOutput | /usr/local/bin/newrelic utils jq '.super_agent.healthy')
+            if [ "$STATUS" == "true" ]; then
+              echo "Agent status check ok."
+              break
+            else
+              if [ "$TRIES" -eq "$MAX_RETRIES" ]; then
+                # Process-based validation attempt
+                IS_AGENT_INSTALLED=$(ps aux | grep newrelic-super-agent | grep -v grep | wc -l)
+                if [ $IS_AGENT_INSTALLED -gt 0 ] ; then
+                  echo "detected newrelic-super-agent process running"
+                  exit 0
+                fi
+            
+                echo "New Relic Agent Control has not started after installing. Please try again later, or see our documentation for installing manually https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/install-configure/install-new-relic" >&2
+          
+                if [ {{.IS_SYSTEMCTL}} -gt 0 ]; then
+                  journalctl -u newrelic-super-agent --no-pager
+                fi
 
-            exit 31
-          fi
+                exit 31
+              fi
+            fi
+          
+            sleep 2
+          done
 
     signal_recipe_applied:
       cmds:
@@ -520,4 +544,4 @@ install:
 
     post_install:
       info: |2
-          ⚙️  The New Relic Super Agent configuration file can be found in /etc/newrelic-super-agent/config.yaml
+          ⚙️  New Relic Agent Control configuration file can be found in /etc/newrelic-super-agent/config.yaml
