first iteration for the super agent recipe for debian

diff --git a/recipes/newrelic/infrastructure/super-agent/debian.yml b/recipes/newrelic/infrastructure/super-agent/debian.yml
--- a/recipes/newrelic/infrastructure/super-agent/debian.yml
+++ b/recipes/newrelic/infrastructure/super-agent/debian.yml
@@ -81,6 +81,7 @@ install:
         - task: config_supervisors
         - task: config_fleet_id
         - task: config_opamp
+        - task: config_super_agent_auth
         - task: config_host_monitoring
         - task: update_otel_mem_limit
         - task: update_otel_end_point
@@ -137,6 +138,24 @@ install:
           if [ $IS_TOUCH_INSTALLED -eq 0 ] ; then
             echo "touch is required to run the newrelic install. Please install touch and re-run the installation." >&2
             exit 15
+          fi
+        - |
+          IS_CURL_INSTALLED=$(which curl | wc -l)
+          if [ $IS_CURL_INSTALLED -eq 0 ] ; then
+            echo "curl is required to run the newrelic install. Please install curl and re-run the installation." >&2
+            exit 16
+          fi
+        - |
+          IS_OPENSSL_INSTALLED=$(which openssl | wc -l)
+          if [ $IS_OPENSSL_INSTALLED -eq 0 ] ; then
+            echo "openssl is required to run the newrelic install. Please install openssl and re-run the installation." >&2
+            exit 17
+          fi
+        - |
+          IS_JQ_INSTALLED=$(which jq | wc -l)
+          if [ $IS_JQ_INSTALLED -eq 0 ] ; then
+            echo "jq is required to run the newrelic install. Please install jq and re-run the installation." >&2
+            exit 18
           fi
         - |
           if [ -n "{{.DEBIAN_CODENAME}}" ]; then
@@ -226,10 +245,9 @@ install:
     log_ssl_ciphers:
       cmds:
         - |
-          IS_OPENSSL_INSTALLED=$(which openssl | wc -l)
           IS_SORT_INSTALLED=$(which sort | wc -l)
           IS_UNIQ_INSTALLED=$(which uniq | wc -l)
-          if [ $IS_OPENSSL_INSTALLED -gt 0 ] && [ $IS_SORT_INSTALLED -gt 0 ] && [ $IS_UNIQ_INSTALLED -gt 0 ]; then
+          if [ $IS_SORT_INSTALLED -gt 0 ] && [ $IS_UNIQ_INSTALLED -gt 0 ]; then
             echo "Detecting available SSL ciphers..."
             openssl ciphers -v | awk '{print " - " $2}' | sort | uniq
           fi
@@ -406,13 +424,19 @@ install:
           if [ "{{.NEW_RELIC_SUPER_AGENT_FLEET_ENABLED}}" = "false" ] ; then
             sed -i '/^\s*opamp:/s/^/#/' /etc/newrelic-super-agent/config.yaml
             sed -i '/^\s*endpoint: https:\/\/opamp/s/^/#/' /etc/newrelic-super-agent/config.yaml
-            sed -i '/^\s*api-key:/s/^/#/' /etc/newrelic-super-agent/config.yaml
-            sed -i '/^\s*headers:/s/^/#/' /etc/newrelic-super-agent/config.yaml
+            sed -i '/^\s*auth_config: https:\/\/opamp/s/^/#/' /etc/newrelic-super-agent/config.yaml
+            sed -i '/^\s*token_url: https:\/\/opamp/s/^/#/' /etc/newrelic-super-agent/config.yaml
+            sed -i '/^\s*client_id: https:\/\/opamp/s/^/#/' /etc/newrelic-super-agent/config.yaml
+            sed -i '/^\s*provider: https:\/\/opamp/s/^/#/' /etc/newrelic-super-agent/config.yaml
+            sed -i '/^\s*private_key_path: https:\/\/opamp/s/^/#/' /etc/newrelic-super-agent/config.yaml
           else
             sed -i 's/s*#\s*opamp:/opamp:/g' /etc/newrelic-super-agent/config.yaml
-            sed -i '/^\s*#\s*endpoint: https:\/\/opamp/s/#//' /etc/newrelic-super-agent/config.yaml
-            sed -i '/^\s*#\s*api-key:/s/#//' /etc/newrelic-super-agent/config.yaml
-            sed -i '/^\s*#\s*headers:/s/#//' /etc/newrelic-super-agent/config.yaml
+            sed -i '/^\s*#\s*endpoint: https:\/\/opamp/s/# //' /etc/newrelic-super-agent/config.yaml
+            sed -i '/^\s*#\s*auth_config: https:\/\/opamp/s/# //' /etc/newrelic-super-agent/config.yaml
+            sed -i '/^\s*#\s*token_url: https:\/\/opamp/s/# //' /etc/newrelic-super-agent/config.yaml
+            sed -i '/^\s*#\s*client_id: https:\/\/opamp/s/# //' /etc/newrelic-super-agent/config.yaml
+            sed -i '/^\s*#\s*provider: https:\/\/opamp/s/# //' /etc/newrelic-super-agent/config.yaml
+            sed -i '/^\s*#\s*private_key_path: https:\/\/opamp/s/# //' /etc/newrelic-super-agent/config.yaml
           fi
         - |
           if [ "{{.NEW_RELIC_REGION}}" = "STAGING" ]; then
@@ -422,9 +446,81 @@ install:
           else
             sed -i 's/\(endpoint: https:\/\/opamp.\).*/\1'"service.newrelic.com\/v1\/opamp"'/' /etc/newrelic-super-agent/config.yaml
           fi
+    config_super_agent_auth:
+      cmds:
         - |
+          set -o nounset,pipefail
+
           if [ "{{.NEW_RELIC_SUPER_AGENT_FLEET_ENABLED}}" != "false" ] ; then
-            sed -i 's/api-key: API_KEY_HERE/api-key: {{.NEW_RELIC_LICENSE_KEY}}/g' /etc/newrelic-super-agent/config.yaml
+            mkdir /etc/newrelic-super-agent/keys
+            chown root:root /etc/newrelic-super-agent/keys
+            chmod 700 /etc/newrelic-super-agent/keys
+
+            TEMPORAL_FOLDER=$(mkdir -p "$TMP/super-agent-installation-$RANDOM")
+            openssl genrsa -out "$TEMPORAL_FOLDER/key" 4096
+            openssl rsa -in "$TEMPORAL_FOLDER/key" -pubout -out "$TEMPORAL_FOLDER/pub"
+
+            if [ "{{.NEW_RELIC_REGION}}" = "STAGING" ]; then
+              REGISTRATION_ENDPOINT=https://staging-iam-service.vip.cf.nr-ops.net/graphql
+              TOKEN_RENEWAL_ENDPOINT=https://staging-system-identity-poc.vip.cf.nr-ops.net/oauth/token
+            elif [ "{{.NEW_RELIC_REGION}}" = "EU" ]; then
+              echo "TODO: EU region is not supported for this POC"
+            else
+              echo "TODO: US region is not supported for this POC"
+            fi
+
+            NAME="System Identity for $(hostname)"
+
+            for RETRY in 1 2 3; do
+              HTTP_CODE=$(echo '{ "query":
+                  "{
+                    mutation createSystemIdentity {
+                      createSystemIdentity(
+                        name: \"'$NAME'\",
+                        organizationId: \"{{ .NEW_RELIC_ORGANIZATION }}\",
+                        publicKey: \"'$(openssl enc -base64 -A -in "$TEMPORAL_FOLDER/pub")'\"
+                      ) {
+                        clientId,
+                        id,
+                        name
+                      }
+                    }
+                  }"
+                }' | tr -d $'\n' | curl -X POST \
+                  -s -w "%{http_code}" \
+                  -H "Content-Type: application/json" \
+                  -H "api-key: {{ .NEW_RELIC_API_KEY }}" \
+                  -o "$TEMPORAL_FOLDER/response.json" \
+                  --data @- \
+                  "$REGISTRATION_ENDPOINT"
+                --data '{ "query": "mutation { createSystemIdentity(name: \"'${NAME}'\", organizationId: \"'${ORGANIZATION_ID}'\", publicKey: \"'$(openssl enc -base64 -A -in "$TEMPORAL_FOLDER/pub")'\") { id name organizationId clientId publicKey } }" }' \
+                ${REGISTRATION_ENDPOINT}
+              )
+
+              if [ $HTTP_CODE -eq 200 ]; then
+                break
+              fi
+
+              echo "Error creating the new system identity. The API endpoint returned $HTTP_CODE. Retrying ($RETRY/3)..."
+              sleep 2
+            done
+
+            ERROR_MESSAGE=$(jq -r '.errors[0].message // "NOERROR"' < "$TEMPORAL_FOLDER/response.json")
+            if [ "$ERROR_MESSAGE" != "NOERROR" ]; then
+              echo "Error creating an identity: $ERROR_MESSAGE"
+              exit
+            fi
+
+            CLIENT_ID=$(jq 'data.createSystemIdentity.clientId' < "$TEMPORAL_FOLDER/response.json")
+            ID=$(jq 'data.createSystemIdentity.id' < "$TEMPORAL_FOLDER/response.json")
+            NAME=$(jq 'data.createSystemIdentity.name' < "$TEMPORAL_FOLDER/response.json")
+
+            mv "$TEMPORAL_FOLDER/key" "/etc/newrelic-super-agent/keys/$CLIENT_ID.key"
+            sed -i 's/token_url: PLACEHOLDER/token_url: '"$TOKEN_RENEWAL_ENDPOINT"'/g' /etc/newrelic-super-agent/config.yaml
+            sed -i 's/client_id: PLACEHOLDER/client_id: '"$CLIENT_ID"'/g' /etc/newrelic-super-agent/config.yaml
+            sed -i 's/provider: PLACEHOLDER/provider: local/g' /etc/newrelic-super-agent/config.yaml
+            sed -i 's/private_key_path: PLACEHOLDER/private_key_path: '"/etc/newrelic-super-agent/keys/$CLIENT_ID.key"'/g' /etc/newrelic-super-agent/config.yaml
+            rm -rf "$TEMPORAL_FOLDER"
           fi
 
     config_host_monitoring:
