Update assert pre req to align with CLI changes

diff --git a/recipes/newrelic/apm/node/linux.yml b/recipes/newrelic/apm/node/linux.yml
--- a/recipes/newrelic/apm/node/linux.yml
+++ b/recipes/newrelic/apm/node/linux.yml
@@ -79,27 +79,27 @@ install:
     assert_pre_req:
       cmds:
         - |
-          sudo -i -u $SUDO_USER command -v node > /dev/null
-          if [ $? -ne 0 ] ; then
-            echo "A valid Node.js installation is required." >> /dev/stderr
+          ASSERT_NODE_INSTALLED=$(sudo -i -u $SUDO_USER command -v node > /dev/null)
+          if [ -z "$ASSERT_NODE_INSTALLED" ] ; then
+            echo "A valid Node.js installation is required." >&2
             exit 22
           fi
         - |
-          sudo -i -u $SUDO_USER command -v npm > /dev/null
-          if [ $? -ne 0 ] ; then
-            echo "A valid NPM installation is required." >> /dev/stderr
+          ASSERT_NPM_INSTALLED=$(sudo -i -u $SUDO_USER command -v npm > /dev/null)
+          if [ -z "$ASSERT_NPM_INSTALLED" ] ; then
+            echo "A valid NPM installation is required." >&2
             exit 22
           fi
         - |
-          sudo -i -u $SUDO_USER command -v pm2 > /dev/null
-          if [ $? -ne 0 ] ; then
-            echo "A valid PM2 installation is required." >> /dev/stderr
+          ASSERT_PM2_INSTALLED=$(sudo -i -u $SUDO_USER command -v pm2 > /dev/null)
+          if [ -z "$ASSERT_PM2_INSTALLED" ] ; then
+            echo "A valid PM2 installation is required." >&2
             exit 22
           fi
         - |
           IS_PM2_RUNNING=$(sudo ps aux | grep pm2 | grep -v grep | wc -l)
           if [ $IS_PM2_RUNNING -eq 0 ] ; then
-            echo "The PM2 process manager is required." >> /dev/stderr
+            echo "The PM2 process manager is required." >&2
             exit 22
           fi
 
@@ -115,7 +115,7 @@ install:
         - |
           FOUND_PROCESSES=$(sudo -i -u $SUDO_USER newrelic-introspector-node list)
           if [ "$FOUND_PROCESSES" == "" ] ||  [ "$FOUND_PROCESSES" == "[]" ]; then
-            echo "No Node processes found running on the host" >> /dev/stderr
+            echo "No Node processes found running on the host" >&2
             exit 1
           else
             PROCESSES=$(echo "$FOUND_PROCESSES" | sed -e "s/\[ //" | sed -e "s/ \]//")
