chore: redirect to process stderr

diff --git a/recipes/newrelic/apm/node/linux.yml b/recipes/newrelic/apm/node/linux.yml
--- a/recipes/newrelic/apm/node/linux.yml
+++ b/recipes/newrelic/apm/node/linux.yml
@@ -42,31 +42,31 @@ install:
       cmds:
         - |
           if [ {{.ACCEPT_RESTART}} != "y" ] && [ {{.ACCEPT_RESTART}} != "Y" ] ; then
-            echo -e "If you would like to manually install, please see our Node standard installation.\nhttps://docs.newrelic.com/docs/agents/nodejs-agent/installation-configuration/install-nodejs-agent/" >> /dev/stderr
+            echo -e "If you would like to manually install, please see our Node standard installation.\nhttps://docs.newrelic.com/docs/agents/nodejs-agent/installation-configuration/install-nodejs-agent/" >&2
             exit 130
           fi
         - |
           sudo -i -u $SUDO_USER command -v node > /dev/null
           if [ $? -ne 0 ] ; then
-            echo "A valid Node.js installation is required." >> /dev/stderr
+            echo "A valid Node.js installation is required." >&2
             exit 22
           fi
         - |
           sudo -i -u $SUDO_USER command -v npm > /dev/null
           if [ $? -ne 0 ] ; then
-            echo "A valid NPM installation is required." >> /dev/stderr
+            echo "A valid NPM installation is required." >&2
             exit 22
           fi
         - |
           sudo -i -u $SUDO_USER command -v pm2 > /dev/null
           if [ $? -ne 0 ] ; then
-            echo "A valid PM2 installation is required." >> /dev/stderr
+            echo "A valid PM2 installation is required." >&2
             exit 22
           fi
         - |
           IS_PM2_RUNNING=$(sudo ps aux | grep pm2 | grep -v grep | wc -l)
           if [ $IS_PM2_RUNNING -eq 0 ] ; then
-            echo "The PM2 process manager is required." >> /dev/stderr
+            echo "The PM2 process manager is required." >&2
             exit 22
           fi
 
@@ -82,7 +82,7 @@ install:
         - |
           FOUND_PROCESSES=$(sudo -i -u $SUDO_USER newrelic-introspector-node list)
           if [ "$FOUND_PROCESSES" == "" ] ||  [ "$FOUND_PROCESSES" == "[  ]" ]; then
-            echo "No Node processes found running on the host" >> /dev/stderr
+            echo "No Node processes found running on the host" >&2
             exit 1
           else
             PROCESSES=$(echo "$FOUND_PROCESSES" | sed -e "s/\[ //" | sed -e "s/ \]//")
diff --git a/recipes/newrelic/infrastructure/amazonlinux.yml b/recipes/newrelic/infrastructure/amazonlinux.yml
--- a/recipes/newrelic/infrastructure/amazonlinux.yml
+++ b/recipes/newrelic/infrastructure/amazonlinux.yml
@@ -38,49 +38,49 @@ install:
         - |
           IS_GREP_INSTALLED=$(which grep | wc -l)
           if [ $IS_GREP_INSTALLED -eq 0 ] ; then
-            echo "grep is required to run the newrelic install. Please install grep and re-run the installation." >> /dev/stderr
+            echo "grep is required to run the newrelic install. Please install grep and re-run the installation." >&2
             exit 10
           fi
         - |
           IS_SED_INSTALLED=$(which sed | wc -l)
           if [ $IS_SED_INSTALLED -eq 0 ] ; then
-            echo "sed is required to run the newrelic install. Please install sed and re-run the installation." >> /dev/stderr
+            echo "sed is required to run the newrelic install. Please install sed and re-run the installation." >&2
             exit 11
           fi
         - |
           IS_AWK_INSTALLED=$(which awk | wc -l)
           if [ $IS_AWK_INSTALLED -eq 0 ] ; then
-            echo "awk is required to run the newrelic install. Please install awk and re-run the installation." >> /dev/stderr
+            echo "awk is required to run the newrelic install. Please install awk and re-run the installation." >&2
             exit 12
           fi
         - |
           IS_CAT_INSTALLED=$(which cat | wc -l)
           if [ $IS_CAT_INSTALLED -eq 0 ] ; then
-            echo "cat is required to run the newrelic install. Please install cat and re-run the installation." >> /dev/stderr
+            echo "cat is required to run the newrelic install. Please install cat and re-run the installation." >&2
             exit 13
           fi
         - |
           IS_TEE_INSTALLED=$(which tee | wc -l)
           if [ $IS_TEE_INSTALLED -eq 0 ] ; then
-            echo "tee is required to run the newrelic install. Please install tee and re-run the installation." >> /dev/stderr
+            echo "tee is required to run the newrelic install. Please install tee and re-run the installation." >&2
             exit 14
           fi
         - |
           IS_TOUCH_INSTALLED=$(which touch | wc -l)
           if [ $IS_TOUCH_INSTALLED -eq 0 ] ; then
-            echo "touch is required to run the newrelic install. Please install touch and re-run the installation." >> /dev/stderr
+            echo "touch is required to run the newrelic install. Please install touch and re-run the installation." >&2
             exit 15
           fi
         - |
           IS_DOCKER_CONTAINER=$(sudo grep 'docker\|lxc' /proc/1/cgroup | wc -l)
           if [ $IS_DOCKER_CONTAINER -gt 0 ] ; then
-            echo "We’ve detected that you are installing our infrastructure agent inside a docker container. This agent is not designed to be installed within a container, but rather on the host it is running on or as a separate container. For additional information visit: https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/linux-installation/docker-container-infrastructure-monitoring/" >> /dev/stderr
+            echo "We’ve detected that you are installing our infrastructure agent inside a docker container. This agent is not designed to be installed within a container, but rather on the host it is running on or as a separate container. For additional information visit: https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/linux-installation/docker-container-infrastructure-monitoring/" >&2
             exit 18
           fi
         - |
           IS_WSL_CONTAINER=$(sudo grep -i 'Microsoft' /proc/version | wc -l)
           if [ $IS_WSL_CONTAINER -gt 0 ] ; then
-            echo "Sorry, our infrastructure agent cannot be installed for Microsoft Windows Subsystem for Linux, this is an unsupported operating system." >> /dev/stderr
+            echo "Sorry, our infrastructure agent cannot be installed for Microsoft Windows Subsystem for Linux, this is an unsupported operating system." >&2
             exit 19
           fi
 
@@ -133,7 +133,7 @@ install:
           sleep 10
           IS_INFRA_INSTALLED=$(sudo ps aux | grep newrelic-infra-service | grep -v grep | wc -l)
           if [ $IS_INFRA_INSTALLED -eq 0 ] ; then
-            echo "The infrastructure agent has not started after installing. Please try again later, or see our documentation for installing manually https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/install-configure/install-new-relic" >> /dev/stderr
+            echo "The infrastructure agent has not started after installing. Please try again later, or see our documentation for installing manually https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/install-configure/install-new-relic" >&2
             exit 31
           fi
 
diff --git a/recipes/newrelic/infrastructure/ohi/elasticsearch/debian.yml b/recipes/newrelic/infrastructure/ohi/elasticsearch/debian.yml
--- a/recipes/newrelic/infrastructure/ohi/elasticsearch/debian.yml
+++ b/recipes/newrelic/infrastructure/ohi/elasticsearch/debian.yml
@@ -76,22 +76,22 @@ install:
         - |
           IS_INFRA_INSTALLED=$(sudo ps aux | grep newrelic-infra-service | grep -v grep | wc -l)
           if [ $IS_INFRA_INSTALLED -eq 0 ] ; then
-            echo "The infrastructure agent is required to install this integration, we recommend going through our guided install path for this pre-requisite which can be found here:  https://docs.newrelic.com/docs/new-relic-guided-installation-overview" >> /dev/stderr
+            echo "The infrastructure agent is required to install this integration, we recommend going through our guided install path for this pre-requisite which can be found here:  https://docs.newrelic.com/docs/new-relic-guided-installation-overview" >&2
             exit 1
           fi
         - |
           if [ ! -f {{.NR_CLI_CONFIG_PATH}} ]; then
-            echo "[Error]: The ElasticSearch config file cannot be found at '{{.NR_CLI_CONFIG_PATH}}'. See https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/elasticsearch-monitoring-integration#comp-req for more info." >> /dev/stderr
+            echo "[Error]: The ElasticSearch config file cannot be found at '{{.NR_CLI_CONFIG_PATH}}'. See https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/elasticsearch-monitoring-integration#comp-req for more info." >&2
             exit 9
           fi
         - |
           if [ {{.NR_CLI_API_USE_SSL}} == true ]; then
             if [ ! -d {{.NR_CLI_API_CA_BUNDLE_DIR}} ]; then
-              echo "[Error]: SSL is true but no certificate bundle directory exist at '{{.NR_CLI_API_CA_BUNDLE_DIR}}'. See https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/elasticsearch-monitoring-integration#comp-req for more info." >> /dev/stderr
+              echo "[Error]: SSL is true but no certificate bundle directory exist at '{{.NR_CLI_API_CA_BUNDLE_DIR}}'. See https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/elasticsearch-monitoring-integration#comp-req for more info." >&2
               exit 11
             fi
             if [ ! -f {{.NR_CLI_API_CA_BUNDLE_DIR}}/{{.NR_CLI_API_CA_BUNDLE_FILE}} ]; then
-              echo "[Error]: SSL is true but no client certificate file exist at '{{.NR_CLI_API_CA_BUNDLE_DIR}}/{{.NR_CLI_API_CA_BUNDLE_FILE}}'. See https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/elasticsearch-monitoring-integration#comp-req for more info." >> /dev/stderr
+              echo "[Error]: SSL is true but no client certificate file exist at '{{.NR_CLI_API_CA_BUNDLE_DIR}}/{{.NR_CLI_API_CA_BUNDLE_FILE}}'. See https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/elasticsearch-monitoring-integration#comp-req for more info." >&2
               exit 12
             fi
           fi
diff --git a/recipes/newrelic/infrastructure/ohi/nginx/debian.yml b/recipes/newrelic/infrastructure/ohi/nginx/debian.yml
--- a/recipes/newrelic/infrastructure/ohi/nginx/debian.yml
+++ b/recipes/newrelic/infrastructure/ohi/nginx/debian.yml
@@ -65,13 +65,13 @@ install:
         - |
           IS_INFRA_INSTALLED=$(sudo ps aux | grep newrelic-infra-service | grep -v grep | wc -l)
           if [ $IS_INFRA_INSTALLED -eq 0 ] ; then
-            echo "The infrastructure agent is required to install this integration, we recommend going through our guided install path for this pre-requisite which can be found here:  https://docs.newrelic.com/docs/new-relic-guided-installation-overview" >> /dev/stderr
+            echo "The infrastructure agent is required to install this integration, we recommend going through our guided install path for this pre-requisite which can be found here:  https://docs.newrelic.com/docs/new-relic-guided-installation-overview" >&2
             exit 1
           fi
         - |
           STUB_STATUS_ENABLED=$(curl {{.NR_CLI_STUB_STATUS_URL}} -s | grep "Active connections:" | wc -l)
           if [ $STUB_STATUS_ENABLED -eq 0 ] ; then
-            echo "NGINX HTTP status module must be configured for New Relic to collect data. \n - See https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/nginx-monitoring-integration#config for more info." >> /dev/stderr
+            echo "NGINX HTTP status module must be configured for New Relic to collect data. \n - See https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/nginx-monitoring-integration#config for more info." >&2
             exit 2
           fi
 
diff --git a/recipes/newrelic/infrastructure/ohi/postgres/debian.yml b/recipes/newrelic/infrastructure/ohi/postgres/debian.yml
--- a/recipes/newrelic/infrastructure/ohi/postgres/debian.yml
+++ b/recipes/newrelic/infrastructure/ohi/postgres/debian.yml
@@ -89,29 +89,29 @@ install:
         - |
           IS_INFRA_INSTALLED=$(sudo ps aux | grep newrelic-infra-service | grep -v grep | wc -l)
           if [ $IS_INFRA_INSTALLED -eq 0 ] ; then
-            echo "The infrastructure agent is required to install this integration, we recommend going through our guided install path for this pre-requisite which can be found here:  https://docs.newrelic.com/docs/new-relic-guided-installation-overview" >> /dev/stderr
+            echo "The infrastructure agent is required to install this integration, we recommend going through our guided install path for this pre-requisite which can be found here:  https://docs.newrelic.com/docs/new-relic-guided-installation-overview" >&2
             exit 1
           fi
         - |
           IS_DATABASE_VALID=$(PGPASSWORD={{.NR_CLI_DB_PASSWORD}} psql -U {{.NR_CLI_DB_USERNAME}} -w {{.NR_CLI_DATABASE}} -h {{.NR_CLI_DB_HOSTNAME}} -p {{.NR_CLI_PORT}} -c "select version();" 2>&1 | grep -i PostgreSQL | grep -v grep | wc -l)
           if [ $IS_DATABASE_VALID -eq 0 ] ; then
-            echo "[Error]: The provided database name is not accessible with the provided username and password and port. See https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/postgresql-monitoring-integration#comp-req for more info." >> /dev/stderr
+            echo "[Error]: The provided database name is not accessible with the provided username and password and port. See https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/postgresql-monitoring-integration#comp-req for more info." >&2
             exit 2
           fi
         - |
           if [ {{.NR_CLI_SSL}} == true ]; then
             if [ ! -f {{.NR_CLI_CLIENT_CERT_FILE}} ]; then
-              echo "[Error]: SSL is true but no client certificate file exist at '{{.NR_CLI_CLIENT_CERT_FILE}}'. See https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/postgresql-monitoring-integration#comp-req for more info." >> /dev/stderr
+              echo "[Error]: SSL is true but no client certificate file exist at '{{.NR_CLI_CLIENT_CERT_FILE}}'. See https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/postgresql-monitoring-integration#comp-req for more info." >&2
               exit 11
             fi
             if [ ! -f {{.NR_CLI_CERT_KEY}} ]; then
-              echo "[Error]: SSL is true but no PEM key file exist at '{{.NR_CLI_CERT_KEY}}'. See https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/postgresql-monitoring-integration#comp-req for more info." >> /dev/stderr
+              echo "[Error]: SSL is true but no PEM key file exist at '{{.NR_CLI_CERT_KEY}}'. See https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/postgresql-monitoring-integration#comp-req for more info." >&2
               exit 12
             fi
           fi
           if [ {{.NR_CLI_TRUST_SERVER_CERTIFICATE}} == true ]; then
             if [ ! -f {{.NR_CLI_CERT_AUTH_FILE}} ]; then
-              echo "[Error]: Trust certificate is true but no certificate authority file exist at '{{.NR_CLI_CERT_AUTH_FILE}}'. See https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/postgresql-monitoring-integration#comp-req for more info." >> /dev/stderr
+              echo "[Error]: Trust certificate is true but no certificate authority file exist at '{{.NR_CLI_CERT_AUTH_FILE}}'. See https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/postgresql-monitoring-integration#comp-req for more info." >&2
               exit 13
             fi
           fi
