fix(couchbase-rhel): update tasks and fields in recipe

diff --git a/recipes/newrelic/couchbase/rhel.yml b/recipes/newrelic/couchbase/rhel.yml
--- a/recipes/newrelic/couchbase/rhel.yml
+++ b/recipes/newrelic/couchbase/rhel.yml
@@ -62,7 +62,17 @@ install:
   tasks:
     default:
       cmds:
+        - task: assert_pre_req
         - task: setup
+
+    assert_pre_req:
+      cmds:
+        - |
+          SERVICE_EXIST=$(sudo systemctl status newrelic-infra.service | grep "Active" | wc -l)
+          if [ $SERVICE_EXIST -eq 0 ]; then
+            echo "The newrelic-infra agent service is NOT installed on the host, but is required to install this integration." >> /dev/stderr
+            exit 1
+          fi
 
     setup:
       label: "Installing couchbase integration..."
@@ -80,7 +90,7 @@ install:
 
           sudo touch /etc/newrelic-infra/integrations.d/couchbase-config.yml;
         - |
-          if [ "$NR_CLI_API_USE_SSL" == false ]; then
+          if [ {{.NR_CLI_API_USE_SSL}} == false ]; then
             sudo tee -a /etc/newrelic-infra/integrations.d/couchbase-config.yml > /dev/null <<"EOT"
           integration_name: com.newrelic.couchbase
 
@@ -100,7 +110,7 @@ install:
 
           instances:
             - name: couchbase
-              command: all
+              command: all_data
               arguments:
                 hostname: {{.NR_CLI_API_HOSTNAME}}
                 port: {{.NR_CLI_API_PORT}}
