Apache recipe improvements

diff --git a/recipes/newrelic/infrastructure/ohi/apache/debian.yml b/recipes/newrelic/infrastructure/ohi/apache/debian.yml
--- a/recipes/newrelic/infrastructure/ohi/apache/debian.yml
+++ b/recipes/newrelic/infrastructure/ohi/apache/debian.yml
@@ -34,14 +34,7 @@ logMatch:
 
 # NRQL the newrelic-cli will use to validate the agent/integration this recipe
 # installed is successfully sending data to New Relic
-validationNrql: "SELECT count(*) from ApacheSample where hostname like '{{.HOSTNAME}}' FACET entityGuid SINCE 10 minutes ago"
-
-# Prompts for input from the user. These variables then become
-# available to go-task in the form of {{.VAR_NAME}}
-inputVars:
-  - name: "NR_CLI_STATUS_URL"
-    prompt: "Apache status URL (default: http://127.0.0.1/server-status?auto)"
-    default: "http://127.0.0.1/server-status?auto"
+validationNrql: "SELECT count(*) from ApacheSample where hostname like '{{.HOSTNAME}}%' FACET entityGuid SINCE 10 minutes ago"
 
 preInstall:
   info: |2
@@ -57,11 +50,13 @@ install:
   tasks:
     default:
       cmds:
-        - task: assert_pre_req
-        - task: setup
+        - task: assert_infra
+        - task: input_assert
+          vars:
+            MAX_RETRIES: 3
         - task: restart
 
-    assert_pre_req:
+    assert_infra:
       cmds:
         - |
           IS_INFRA_INSTALLED=$(sudo ps aux | grep newrelic-infra-service | grep -v grep | wc -l)
@@ -69,43 +64,66 @@ install:
             echo "The infrastructure agent is required to install this integration, we recommend going through our guided install path for this pre-requisite which can be found here:  https://docs.newrelic.com/docs/new-relic-guided-installation-overview" >> /dev/stderr
             exit 1
           fi
-        - |
-          STUB_STATUS_ENABLED=$(curl {{.NR_CLI_STATUS_URL}} -s | grep "IdleWorkers:" | wc -l)
-          if [ $STUB_STATUS_ENABLED -eq 0 ] ; then
-            echo "Status page is not returning data. Apache2 must be correctly configured for New Relic to collect data. \n - See https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/apache-monitoring-integration#config for more info." >> /dev/stderr
-            exit 2
-          fi
 
-    setup:
-      label: "Installing Apache integration..."
+    input_assert:
       cmds:
         - |
+          TRIES=0
+
+          # Check Env Vars
+          NEW_RELIC_ASSUME_YES="{{.NEW_RELIC_ASSUME_YES}}"
+          NR_CLI_STATUS_URL="{{.NR_CLI_STATUS_URL}}"
+
+          # Set Defaults
+          NR_CLI_STATUS_URL=${NR_CLI_STATUS_URL:-'http://127.0.0.1/server-status?auto'}
+
+          if [[ "$NEW_RELIC_ASSUME_YES" != "true" ]]; then
+            while [ $TRIES -lt {{.MAX_RETRIES}} ]; do
+              printf "\nApache status URL (default: http://127.0.0.1/server-status?auto): "
+              read -r NR_CLI_STATUS_URL
+              NR_CLI_STATUS_URL=${NR_CLI_STATUS_URL:-http://127.0.0.1/server-status?auto}
+              ((TRIES++))
+
+              code=$(curl -I $NR_CLI_STATUS_URL -w %{response_code} -so '/dev/null')
+              if [ $code != "200" ]; then
+                printf "\nApache status page is returning http error code $code. Apache must be correctly configured for New Relic to collect data. \n - See https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/apache-monitoring-integration#config for more info.\n" >> /dev/stderr
+                if [ ! $TRIES -lt {{.MAX_RETRIES}} ]; then exit 3; else continue; fi
+                echo "Please try again"
+                continue
+              fi
+              STUB_STATUS_ENABLED=$(curl $NR_CLI_STATUS_URL -s | grep "IdleWorkers:" | wc -l)
+              if [ $STUB_STATUS_ENABLED -eq 0 ] ; then
+                printf "\nStatus page is not returning expected data. Apache2 must be correctly configured for New Relic to collect data. \n - See https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/apache-monitoring-integration#config for more info.\n" >> /dev/stderr
+                if [ ! $TRIES -lt {{.MAX_RETRIES}} ]; then exit 2; else continue; fi
+                echo "Please try again"
+                continue
+              fi
+              break
+            done
+          fi
+          printf "\n[OK] All checks passed. Installing Apache Integration...\n\n"
+
           sudo mkdir -p "/etc/newrelic-infra/integrations.d"
-        - |
           sudo apt-get update -yq
-        - |
           sudo apt-get install nri-apache -y
-        - |
+
           if [ -f /etc/newrelic-infra/integrations.d/apache-config.yml ]; then
             sudo rm /etc/newrelic-infra/integrations.d/apache-config.yml;
           fi
-
           sudo cp /etc/newrelic-infra/integrations.d/apache-config.yml.sample /etc/newrelic-infra/integrations.d/apache-config.yml;
-
-        - |
-          sudo tee /etc/newrelic-infra/integrations.d/apache-config.yml > /dev/null <<"EOT"
+          sudo tee /etc/newrelic-infra/integrations.d/apache-config.yml > /dev/null <<EOT
           integration_name: com.newrelic.apache
 
           instances:
               - name: apache-server-metrics
                 command: metrics
                 arguments:
-                    status_url: {{.NR_CLI_STATUS_URL}}
+                    status_url: $NR_CLI_STATUS_URL
 
-                    # New users should leave this property as `true`, to identify the
-                    # monitored entities as `remote`. Setting this property to `false` (the
+                    # New users should leave this property as 'true', to identify the
+                    # monitored entities as 'remote'. Setting this property to 'false' (the
                     # default value) is deprecated and will be removed soon, disallowing
-                    # entities that are identified as `local`.
+                    # entities that are identified as 'local'.
                     # Please check the documentation to get more information about local
                     # versus remote entities:
                     # https://github.com/newrelic/infra-integrations-sdk/blob/master/docs/entity-definition.md
@@ -114,12 +132,12 @@ install:
               - name: apache-server-inventory
                 command: inventory
                 arguments:
-                    status_url: {{.NR_CLI_STATUS_URL}}
+                    status_url: $NR_CLI_STATUS_URL
 
-                    # New users should leave this property as `true`, to identify the
-                    # monitored entities as `remote`. Setting this property to `false` (the
+                    # New users should leave this property as 'true', to identify the
+                    # monitored entities as 'remote'. Setting this property to 'false' (the
                     # default value) is deprecated and will be removed soon, disallowing
-                    # entities that are identified as `local`.
+                    # entities that are identified as 'local'.
                     # Please check the documentation to get more information about local
                     # versus remote entities:
                     # https://github.com/newrelic/infra-integrations-sdk/blob/master/docs/entity-definition.md
