fix: ensure apache is installed with expected path

diff --git a/recipes/newrelic/infrastructure/ohi/apache/rhel.yml b/recipes/newrelic/infrastructure/ohi/apache/rhel.yml
--- a/recipes/newrelic/infrastructure/ohi/apache/rhel.yml
+++ b/recipes/newrelic/infrastructure/ohi/apache/rhel.yml
@@ -78,7 +78,11 @@ install:
           STUB_STATUS_ENABLED=$(curl $NR_CLI_STATUS_URL -s | grep -i "idle" | wc -l)
           if [ $STUB_STATUS_ENABLED -eq 0 ] ; then
             if [ -f /etc/httpd/conf.d/server-status.conf ]; then
-              printf "\nThe status page is not returning expected data. Apache2 must be correctly configured for New Relic to collect data. \n - See https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/apache-monitoring-integration#config for more info.\n" >&2
+              printf "\nThe status page is not returning expected data. Apache must be configured with the server-status module for New Relic to collect data. \n - See https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/apache-monitoring-integration#config for more info.\n" >&2
+              exit 131
+            fi
+            if [ ! -d /etc/httpd/conf.d ]; then
+              printf "\nThe server-status module is required in order to instrument Apache. \n - See https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/apache-monitoring-integration#config for more info.\n" >&2
               exit 131
             fi
             echo "The server-status module is currently not enabled."
