feat(php): add helpful error messaging for some important preInstall checks

diff --git a/recipes/newrelic/apm/php/debian.yml b/recipes/newrelic/apm/php/debian.yml
--- a/recipes/newrelic/apm/php/debian.yml
+++ b/recipes/newrelic/apm/php/debian.yml
@@ -40,6 +40,7 @@ preInstall:
       IS_PHP_INSTALLED=$(which php | wc -l)
       if [ "$IS_PHP_INSTALLED" -eq 0 ]; then
         # PHP not installed, no detection
+        echo "Error: PHP is not installed. Please install PHP, configure and enable your web server (Apache or NGINX), then retry the installation." >&2
         exit 1
       fi
 
@@ -64,12 +65,14 @@ preInstall:
         # No FPM running, recipe cannot install, either signal DETECTED or skip
         if [ "$IS_APACHE_RUNNING" -eq 0 ]; then
           # No Apache or FPM running, no detection
+          echo "Error: Neither Apache nor php-fpm is running. Please start the relevant services then retry the installation." >&2
           exit 4
         else
           # No FPM, Apache is running, let's check if Apache PHP module is enabled
           IS_APACHE_PHP_ENABLED=$(apachectl -t -D DUMP_MODULES | grep php | grep -v grep | wc -l)
           if [ "$IS_APACHE_PHP_ENABLED" -eq 0 ]; then
             # No FPM, Apache is running, but not PHP module enabled, no detection
+            echo "Error: Apache is running, but the PHP module is still disabled. Please enable the PHP module and retry the installation." >&2
             exit 5
           else
             echo "No FPM, Apache running with PHP module, Ok to install" >&2
