Instruction clarification.

diff --git a/recipes/newrelic/apm/php/debian-fpm.yml b/recipes/newrelic/apm/php/debian-fpm.yml
--- a/recipes/newrelic/apm/php/debian-fpm.yml
+++ b/recipes/newrelic/apm/php/debian-fpm.yml
@@ -28,7 +28,7 @@ inputVars:
     prompt: "What is the name of your PHP application?"
     default: "PHP Application"
   - name: "NR_PHP_RESTART"
-    prompt: "Restart the PHP application after installation? (y/n)"
+    prompt: "Restart the PHP web service after PHP agent installation? Selecting 'y' will automatically restart php-fpm or nginx depending on the service that is detected. Selecting 'n' will require you to manually restart the process when prompted. (y/n)"
     default: "y"
 
 install:
@@ -64,15 +64,15 @@ install:
     verify_continue:
       cmds:
         - |
+          echo -e "{{.YELLOW}}Confirmation:  The following options were selected.  If you wish to change an option, please select 'n' at the prompt and restart the installation."
+          echo -e "* The following application name was selected: {{.NR_PHP_APPLICATION}}"
           if [ "{{.NR_PHP_RESTART}}" = "y" ]; then
-            echo -e "{{.YELLOW}}Confirmation:
-            This installation will restart php-fpm or nginx depending on the application
-            architecture detected. If you would prefer to run this step manually, enter 'n'
-            at the following prompt to exit the installer, and enter 'n' at the previous restart prompt.{{.NOCOLOR}}"
+            echo -e "{{.YELLOW}}* Automatic process restart was selected.  This installation will restart the php-fpm or nginx process depending on the application architecture detected.{{.NOCOLOR}}"
+          else
+            echo -e "{{.YELLOW}}* Manual process restart was selected.  This installation will not automatically restart the php-fpm or nginx process depending on the application architecture detected.  You will be prompted to restart manually in order to complete a successful installation of the PHP agent.{{.NOCOLOR}}"
           fi
-
           echo -e "{{.GRAY}}
-          Note: If you are hosting your PHP application differently, check out our other installation options:
+          Note: If you are hosting your PHP application on something other than nginx or php-fpm, please select 'n' and check out our other installation options:
           https://docs.newrelic.com/docs/agents/php-agent/installation/php-agent-installation-overview/{{.NOCOLOR}}
           "
           if [[ "{{.NEW_RELIC_ASSUME_YES}}" != "true" ]]; then
@@ -84,11 +84,11 @@ install:
               if [[ -z "$NEW_RELIC_CONTINUE" ]]; then
                 NEW_RELIC_CONTINUE="Y"
               fi
-              if [[ "$NEW_RELIC_CONTINUE" == "N" ]]; then
+              if [[ "$NEW_RELIC_CONTINUE" == "n" ]] || [[ "$NEW_RELIC_CONTINUE" == "N" ]]; then
                 echo -e "{{.WHITE}}Exiting the installation{{.NOCOLOR}}"
                 exit 130
               fi
-              if [[ "$NEW_RELIC_CONTINUE" == "Y" ]]; then
+              if [[ "$NEW_RELIC_CONTINUE" == "y" ]] || [[ "$NEW_RELIC_CONTINUE" == "Y" ]]; then
                 break
               fi
               echo -e "{{.WHITE}}Please type Y or N only.{{.NOCOLOR}}"
@@ -328,19 +328,19 @@ install:
             fi
             if [[ "{{.NEW_RELIC_ASSUME_YES}}" != "true" ]]; then
               while :; do
-                echo -n -e "{{.WHITE}}Press Y if you successfully restarted your web server.  Press N if you are unable to restart your web server at this time and you wish to exit the installation. (default: Y)? {{.NOCOLOR}}"
+                echo -n -e "{{.WHITE}}Press Y if you successfully restarted your web server.  Press N if you are unable to restart your web server at this time, and you wish to exit the installation. (default: Y)? {{.NOCOLOR}}"
                 read answer
                 echo ""
                 NEW_RELIC_RESTARTED=$(echo "${answer^^}" | cut -c1-1)
                 if [[ -z "$NEW_RELIC_RESTARTED" ]]; then
                   NEW_RELIC_RESTARTED="Y"
                 fi
-                if [[ "$NEW_RELIC_RESTARTED" == "N" ] || [ "$NEW_RELIC_RESTARTED" == "n" ]]; then
+                if [[ "$NEW_RELIC_RESTARTED" == "N" ]] || [[ "$NEW_RELIC_RESTARTED" == "n" ]]; then
                   echo -e "{{.WHITE}}Exiting the installation{{.NOCOLOR}}"
-		  #exit 23: User declined to accept recipe terms
-                  exit 23
+		  # exit 130: Installation was cancelled either using Ctrl+C or by selecting not to continue the installation
+                  exit 130
                 fi
-                if [[ "$NEW_RELIC_RESTARTED" == "Y" ] || [ "$NEW_RELIC_RESTARTED" == "y" ]]; then
+                if [[ "$NEW_RELIC_RESTARTED" == "Y" ]] || [[ "$NEW_RELIC_RESTARTED" == "y" ]]; then
                   break
                 fi
                 echo -e "{{.WHITE}}Please type Y or N only.{{.NOCOLOR}}"
diff --git a/recipes/newrelic/apm/php/redhat-fpm.yml b/recipes/newrelic/apm/php/redhat-fpm.yml
--- a/recipes/newrelic/apm/php/redhat-fpm.yml
+++ b/recipes/newrelic/apm/php/redhat-fpm.yml
@@ -25,7 +25,7 @@ inputVars:
     prompt: "What is the name of your PHP application?"
     default: "PHP Application"
   - name: "NR_PHP_RESTART"
-    prompt: "Restart the PHP application after installation? (y/n)"
+    prompt: "Restart the PHP web service after PHP agent installation? Selecting 'y' will automatically restart php-fpm or nginx depending on the service that is detected. Selecting 'n' will require you to manually restart the process when prompted. (y/n)"
     default: "y"
 
 install:
@@ -37,7 +37,8 @@ install:
       sh: mktemp -d /tmp/newrelic-php-agent.XXXXXX
     WHITE: '\033[0;97m'
     RED: '\033[0;31m'
-    GRAY: '\033[38;5;240m'
+    GRAY: '\033[38;5;248m'
+    CYAN: '\033[0;36m'
     NOCOLOR: '\033[0m'
     YELLOW: '\033[0;33m'
     ARROW: '\033[0;36m===> \033[0;97m'
@@ -60,19 +61,16 @@ install:
     verify_continue:
       cmds:
         - |
-          echo -e "{{.YELLOW}}
-          ================================================================================
-          =                                                                              =
-          =                                   Warning                                    =
-          =                                                                              =
-          =               This installation will automatically reload your               =
-          =                          nginx and/or FPM services                           =
-          =                                                                              =
-          ================================================================================
-          {{.NOCOLOR}}"
-          echo "
-          If you are hosting your PHP application differently then check out our other installation options:
-          https://docs.newrelic.com/docs/agents/php-agent/installation/php-agent-installation-overview/
+          echo -e "{{.YELLOW}}Confirmation:  The following options were selected.  If you wish to change an option, please select 'n' at the prompt and restart the installation."
+          echo -e "* The following application name was selected: {{.NR_PHP_APPLICATION}}"
+          if [ "{{.NR_PHP_RESTART}}" = "y" ]; then
+            echo -e "{{.YELLOW}}* Automatic process restart was selected.  This installation WILL restart the php-fpm or nginx process depending on the application architecture detected.{{.NOCOLOR}}"
+          else
+            echo -e "{{.YELLOW}}* Manual process restart was selected.  This installation WILL NOT automatically restart the php-fpm or nginx process depending on the application architecture detected.  You will be prompted to restart manually in order to complete a successful installation of the PHP agent.{{.NOCOLOR}}"
+          fi
+          echo -e "{{.GRAY}}
+          Note: If you are hosting your PHP application on something other than nginx or php-fpm, please select 'n' and check out our other installation options:
+          https://docs.newrelic.com/docs/agents/php-agent/installation/php-agent-installation-overview/{{.NOCOLOR}}
           "
           if [[ "{{.NEW_RELIC_ASSUME_YES}}" != "true" ]]; then
             while :; do
@@ -83,11 +81,11 @@ install:
               if [[ -z "$NEW_RELIC_CONTINUE" ]]; then
                 NEW_RELIC_CONTINUE="Y"
               fi
-              if [[ "$NEW_RELIC_CONTINUE" == "N" ]]; then
+              if [[ "$NEW_RELIC_CONTINUE" == "n" ]] || [[ "$NEW_RELIC_CONTINUE" == "N" ]]; then
                 echo -e "{{.WHITE}}Exiting the installation{{.NOCOLOR}}"
                 exit 130
               fi
-              if [[ "$NEW_RELIC_CONTINUE" == "Y" ]]; then
+              if [[ "$NEW_RELIC_CONTINUE" == "y" ]] || [[ "$NEW_RELIC_CONTINUE" == "Y" ]]; then
                 break
               fi
               echo -e "{{.WHITE}}Please type Y or N only.{{.NOCOLOR}}"
@@ -314,10 +312,26 @@ install:
               echo -e "{{.RED}}Please restart $process as privileged user $user_name for instrumentation to be enabled.{{.NOCOLOR}}"
             else
               echo -e "{{.RED}}You will need to restart your PHP web server in order for web instrumentation to be enabled.{{.NOCOLOR}}"
-              if [[ "{{.NEW_RELIC_ASSUME_YES}}" != "true" ]]; then
-                echo -n "Press enter to continue once this has been done."
+            fi
+            if [[ "{{.NEW_RELIC_ASSUME_YES}}" != "true" ]]; then
+              while :; do
+                echo -n -e "{{.WHITE}}Press Y if you successfully restarted your web server.  Press N if you are unable to restart your web server at this time, and you wish to exit the installation. (default: Y)? {{.NOCOLOR}}"
                 read answer
-              fi
+                echo ""
+                NEW_RELIC_RESTARTED=$(echo "${answer^^}" | cut -c1-1)
+                if [[ -z "$NEW_RELIC_RESTARTED" ]]; then
+                  NEW_RELIC_RESTARTED="Y"
+                fi
+                if [[ "$NEW_RELIC_RESTARTED" == "N" ]] || [[ "$NEW_RELIC_RESTARTED" == "n" ]]; then
+                  echo -e "{{.WHITE}}Exiting the installation{{.NOCOLOR}}"
+                  #exit 130: Installation was cancelled either using Ctrl+C or by selecting not to continue the installation
+                  exit 130
+                fi
+                if [[ "$NEW_RELIC_RESTARTED" == "Y" ]] || [[ "$NEW_RELIC_RESTARTED" == "y" ]]; then
+                  break
+                fi
+                echo -e "{{.WHITE}}Please type Y or N only.{{.NOCOLOR}}"
+              done
             fi
           fi
 
