fix: jq checking wrong index

diff --git a/recipes/newrelic/infrastructure/alerts/golden.yml b/recipes/newrelic/infrastructure/alerts/golden.yml
--- a/recipes/newrelic/infrastructure/alerts/golden.yml
+++ b/recipes/newrelic/infrastructure/alerts/golden.yml
@@ -40,8 +40,8 @@ preInstall:
           -d '{"query":"{actor {account(id: '$NEW_RELIC_ACCOUNT_ID') {alerts {policiesSearch {totalCount policies { name id } } } } } }"}'
       )
 
-      POLICY_ID=$(echo $POLICY_RESULT | grep -o '{"id":"[0-9]\+","name":"Golden Signals"}' | cut -d "," -f1 | cut -d ":" -f2)
-      POLICY_ID=$(sed -e 's/^"//' -e 's/"$//' <<<"$POLICY_ID")
+      POLICY_ID=$(echo $POLICY_RESULT | /usr/local/bin/newrelic utils jq 'first(.data.actor.account.alerts.policiesSearch.policies[] | select(.name=="Golden Signals") | .id)')
+      POLICY_ID=$([[ $POLICY_ID =~ 'null' ]] && echo 0 || echo "${POLICY_ID//\"/""}")
 
       if [[ -n "$POLICY_ID" ]] && [ $POLICY_ID -gt 0 ] ; then
         echo "Golden Signals already installed on this account, skipped"
@@ -70,24 +70,21 @@ install:
             NEW_RELIC_API_URL=$(echo -n 'https://api.eu.newrelic.com')
           fi
 
-          while true; do
-            POLICY_RESULT=$(curl -sX POST $NEW_RELIC_API_URL'/graphql' \
-                -H 'Api-Key:{{.NEW_RELIC_API_KEY}}' \
-                -L -H 'Content-Type: application/json' \
-                -d '{"query":"{actor {account(id: '$NEW_RELIC_ACCOUNT_ID') {alerts {policiesSearch {totalCount policies { name id } } } } } }"}'
-            )
-            if [ -f /tmp/policy.json ]; then
-              sudo rm -f /tmp/policy.json
-            fi
-            POLICY_ID=$(echo $POLICY_RESULT | /usr/local/bin/newrelic utils jq '.data.actor.account.alerts.policiesSearch.policies[0] | select(.name=="{{.ALERT_POLICY_NAME}}") | .id | tonumber')
-            if [ -n "$POLICY_ID" ] && [ $POLICY_ID -gt 0 ] ; then
-              curl -sX DELETE $NEW_RELIC_API_URL'/v2/alerts_policies/'$POLICY_ID'.json' -H 'Api-Key:{{.NEW_RELIC_API_KEY}}' -i > /dev/null
-              continue
-            else
-              break
-            fi
-          done
+          POLICY_RESULT=$(curl -sX POST $NEW_RELIC_API_URL'/graphql' \
+              -H 'Api-Key:{{.NEW_RELIC_API_KEY}}' \
+              -L -H 'Content-Type: application/json' \
+              -d '{"query":"{actor {account(id: '$NEW_RELIC_ACCOUNT_ID') {alerts {policiesSearch {totalCount policies { name id } } } } } }"}'
+          )
+          POLICY_ID=$(echo $POLICY_RESULT | /usr/local/bin/newrelic utils jq 'first(.data.actor.account.alerts.policiesSearch.policies[] | select(.name=="{{.ALERT_POLICY_NAME}}") | .id)')
+          POLICY_ID=$([[ $POLICY_ID =~ 'null' ]] && echo 0 || echo "${POLICY_ID//\"/""}")
+          if [ -n "$POLICY_ID" ] && [ $POLICY_ID -gt 0 ] ; then
+            return 0
+          fi
+
           echo 'Creating alert policy {{.ALERT_POLICY_NAME}}...'
+          if [ -f /tmp/policy.json ]; then
+            sudo rm -f /tmp/policy.json
+          fi
           sudo tee -a /tmp/policy.json > /dev/null <<"EOT"
           {
             "query": "mutation {alertsPolicyCreate(accountId: {{.NEW_RELIC_ACCOUNT_ID}}, policy: { name: POLICY_NAME incidentPreference: PER_CONDITION_AND_TARGET }) { id name } }"
@@ -100,7 +97,8 @@ install:
               -L -H 'Content-Type: application/json' \
               -d @/tmp/policy.json
           )
-          POLICY_ID=$(echo $POLICY_RESULT | /usr/local/bin/newrelic utils jq '.data.alertsPolicyCreate.id | tonumber')
+          POLICY_ID=$(echo $POLICY_RESULT | /usr/local/bin/newrelic utils jq '.data.alertsPolicyCreate.id')
+          POLICY_ID=$([[ $POLICY_ID =~ 'null' ]] && echo 0 || echo "${POLICY_ID//\"/""}")
           if [ -f /tmp/policy.json ]; then
             rm -f /tmp/policy.json
           fi
@@ -129,7 +127,8 @@ install:
           fi
 
 
-          HIGH_CPU_CONDITION_ID=$(echo $CONDITIONS_LOOKUP_RESULT | /usr/local/bin/newrelic utils jq '.data.actor.account.alerts.nrqlConditionsSearch.nrqlConditions[0] | select(.name=="{{.ALERT_HIGH_CPU_CONDITION_NAME}}") | .id | tonumber')
+          HIGH_CPU_CONDITION_ID=$(echo $CONDITIONS_LOOKUP_RESULT | /usr/local/bin/newrelic utils jq 'first(.data.actor.account.alerts.nrqlConditionsSearch.nrqlConditions[] | select(.name=="{{.ALERT_HIGH_CPU_CONDITION_NAME}}") | .id)')
+          HIGH_CPU_CONDITION_ID=$([[ $HIGH_CPU_CONDITION_ID =~ 'null' ]] && echo 0 || echo "${HIGH_CPU_CONDITION_ID//\"/""}")
           if [ -f /tmp/condition.json ]; then
             sudo rm -f /tmp/condition.json
           fi
@@ -163,7 +162,8 @@ install:
           echo 'done'
 
 
-          HIGH_ERROR_CONDITION_ID=$(echo $CONDITIONS_LOOKUP_RESULT | /usr/local/bin/newrelic utils jq '.data.actor.account.alerts.nrqlConditionsSearch.nrqlConditions[0] | select(.name=="{{.ALERT_HIGH_ERROR_RATE_NAME}}") | .id | tonumber')
+          HIGH_ERROR_CONDITION_ID=$(echo $CONDITIONS_LOOKUP_RESULT | /usr/local/bin/newrelic utils jq 'first(.data.actor.account.alerts.nrqlConditionsSearch.nrqlConditions[] | select(.name=="{{.ALERT_HIGH_ERROR_RATE_NAME}}") | .id)')
+          HIGH_ERROR_CONDITION_ID=$([[ $HIGH_ERROR_CONDITION_ID =~ 'null' ]] && echo 0 || echo "${HIGH_ERROR_CONDITION_ID//\"/""}")
           if [ -f /tmp/condition.json ]; then
             sudo rm -f /tmp/condition.json
           fi
@@ -197,7 +197,8 @@ install:
           echo 'done'
 
 
-          HIGH_RESPONSE_CONDITION_ID=$(echo $CONDITIONS_LOOKUP_RESULT | /usr/local/bin/newrelic utils jq '.data.actor.account.alerts.nrqlConditionsSearch.nrqlConditions[0] | select(.name=="{{.ALERT_HIGH_RESPONSE_TIME_NAME}}") | .id | tonumber')
+          HIGH_RESPONSE_CONDITION_ID=$(echo $CONDITIONS_LOOKUP_RESULT | /usr/local/bin/newrelic utils jq 'first(.data.actor.account.alerts.nrqlConditionsSearch.nrqlConditions[] | select(.name=="{{.ALERT_HIGH_RESPONSE_TIME_NAME}}") | .id)')
+          HIGH_RESPONSE_CONDITION_ID=$([[ $HIGH_RESPONSE_CONDITION_ID =~ 'null' ]] && echo 0 || echo "${HIGH_RESPONSE_CONDITION_ID//\"/""}")
           if [ -f /tmp/condition.json ]; then
             sudo rm -f /tmp/condition.json
           fi
@@ -231,7 +232,8 @@ install:
           echo 'done'
 
 
-          LOW_THROUGHPUT_CONDITION_ID=$(echo $CONDITIONS_LOOKUP_RESULT | /usr/local/bin/newrelic utils jq '.data.actor.account.alerts.nrqlConditionsSearch.nrqlConditions[0] | select(.name=="{{.ALERT_LOW_THROUGHPUT_NAME}}") | .id | tonumber')
+          LOW_THROUGHPUT_CONDITION_ID=$(echo $CONDITIONS_LOOKUP_RESULT | /usr/local/bin/newrelic utils jq 'first(.data.actor.account.alerts.nrqlConditionsSearch.nrqlConditions[] | select(.name=="{{.ALERT_LOW_THROUGHPUT_NAME}}") | .id)')
+          LOW_THROUGHPUT_CONDITION_ID=$([[ $LOW_THROUGHPUT_CONDITION_ID =~ 'null' ]] && echo 0 || echo "${LOW_THROUGHPUT_CONDITION_ID//\"/""}")
           if [ -f /tmp/condition.json ]; then
             sudo rm -f /tmp/condition.json
           fi
@@ -368,4 +370,3 @@ install:
           sh: echo 'High Application Response Time'
         ALERT_LOW_THROUGHPUT_NAME:
           sh: echo 'Low Application Throughput'
-
