fix(alerts): check if the policy file is available

diff --git a/recipes/newrelic/infrastructure/alerts/golden.yml b/recipes/newrelic/infrastructure/alerts/golden.yml
--- a/recipes/newrelic/infrastructure/alerts/golden.yml
+++ b/recipes/newrelic/infrastructure/alerts/golden.yml
@@ -78,6 +78,12 @@ install:
             "query": "mutation {alertsPolicyCreate(accountId: {{.NEW_RELIC_ACCOUNT_ID}}, policy: { name: POLICY_NAME incidentPreference: PER_CONDITION_AND_TARGET }) { id name } }"
           }
           EOT
+          if [ $? -eq 0 ]; then 
+            echo "File '/tmp/policy.json' is created"
+          else 
+            echo "Unable to create the file '/tmp/policy.json'. Please retry using the right permissions"
+            exit 2
+          fi 
           sudo sed -i "s/POLICY_NAME/\"\"{{.ALERT_POLICY_NAME}}\"\"/g" /tmp/policy.json
           sudo sed -i 's/""/\\"/g' /tmp/policy.json
           POLICY_RESULT=$(curl -sX POST $NEW_RELIC_API_URL'/graphql' \
@@ -113,6 +119,12 @@ install:
             "query": "mutation {alertsNrqlConditionStaticCreate(accountId: {{.NEW_RELIC_ACCOUNT_ID}}, policyId: POLICY_ID, condition: { name: CONDITION_NAME enabled: true nrql: { query: NRQL_QUERY } signal: { aggregationMethod: EVENT_FLOW aggregationDelay: 120 } terms: { threshold: 85 thresholdDuration: 300 thresholdOccurrences: ALL operator: ABOVE priority: CRITICAL } violationTimeLimitSeconds: 2592000 valueFunction: SINGLE_VALUE }) { id name } }"
           }
           EOT
+          if [ $? -eq 0 ]; then 
+            echo "File '/tmp/condition.json' is created"
+          else 
+            echo "Unable to create the file '/tmp/condition.json'. Please retry using the right permissions"
+            exit 2
+          fi 
           sudo sed -i 's/POLICY_ID/'$POLICY_ID'/g' /tmp/condition.json
           sudo sed -i "s/CONDITION_NAME/\"\"{{.ALERT_HIGH_CPU_CONDITION_NAME}}\"\"/g" /tmp/condition.json
           sudo sed -i "s/CONDITION_ID/\"\"$HIGH_CPU_CONDITION_ID\"\"/g" /tmp/condition.json
@@ -137,6 +149,12 @@ install:
             "query": "mutation {alertsNrqlConditionBaselineCreate(accountId: {{.NEW_RELIC_ACCOUNT_ID}}, policyId: POLICY_ID, condition: { name: CONDITION_NAME enabled: true nrql: { query: NRQL_QUERY } signal: { aggregationMethod: EVENT_FLOW aggregationDelay: 120 } terms: { threshold: 3 thresholdDuration: 300 thresholdOccurrences: ALL operator: ABOVE priority: CRITICAL } violationTimeLimitSeconds: 2592000 baselineDirection: UPPER_ONLY }) { id name } }"
           }
           EOT
+          if [ $? -eq 0 ]; then 
+            echo "File '/tmp/condition.json' is created"
+          else 
+            echo "Unable to create the file '/tmp/condition.json'. Please retry using the right permissions"
+            exit 2
+          fi 
           sudo sed -i 's/POLICY_ID/'$POLICY_ID'/g' /tmp/condition.json
           sudo sed -i "s/CONDITION_NAME/\"\"{{.ALERT_HIGH_ERROR_RATE_NAME}}\"\"/g" /tmp/condition.json
           sudo sed -i "s/CONDITION_ID/\"\"$HIGH_ERROR_CONDITION_ID\"\"/g" /tmp/condition.json
@@ -162,6 +180,12 @@ install:
             "query": "mutation {alertsNrqlConditionBaselineCreate(accountId: {{.NEW_RELIC_ACCOUNT_ID}}, policyId: POLICY_ID, condition: { name: CONDITION_NAME enabled: true nrql: { query: NRQL_QUERY } signal: { aggregationMethod: EVENT_FLOW aggregationDelay: 120 } terms: { threshold: 3 thresholdDuration: 300 thresholdOccurrences: ALL operator: ABOVE priority: CRITICAL } violationTimeLimitSeconds: 2592000 baselineDirection: UPPER_ONLY }) { id name } }"
           }
           EOT
+          if [ $? -eq 0 ]; then 
+            echo "File '/tmp/condition.json' is created"
+          else 
+            echo "Unable to create the file '/tmp/condition.json'. Please retry using the right permissions"
+            exit 2
+          fi 
           sudo sed -i 's/POLICY_ID/'$POLICY_ID'/g' /tmp/condition.json
           sudo sed -i "s/CONDITION_NAME/\"\"{{.ALERT_HIGH_RESPONSE_TIME_NAME}}\"\"/g" /tmp/condition.json
           sudo sed -i "s/CONDITION_ID/\"\"$HIGH_RESPONSE_CONDITION_ID\"\"/g" /tmp/condition.json
@@ -184,6 +208,12 @@ install:
             "query": "mutation {alertsNrqlConditionBaselineCreate(accountId: {{.NEW_RELIC_ACCOUNT_ID}}, policyId: POLICY_ID, condition: { name: CONDITION_NAME enabled: true nrql: { query: NRQL_QUERY } signal: { aggregationMethod: EVENT_FLOW aggregationDelay: 120 } terms: { threshold: 3 thresholdDuration: 300 thresholdOccurrences: ALL operator: ABOVE priority: CRITICAL } violationTimeLimitSeconds: 2592000 baselineDirection: LOWER_ONLY expiration: { closeViolationsOnExpiration: true expirationDuration: 600 openViolationOnExpiration: true } }) { id name } }"
           }
           EOT
+          if [ $? -eq 0 ]; then 
+            echo "File '/tmp/condition.json' is created"
+          else 
+            echo "Unable to create the file '/tmp/condition.json'. Please retry using the right permissions"
+            exit 2
+          fi 
           sudo sed -i 's/POLICY_ID/'$POLICY_ID'/g' /tmp/condition.json
           sudo sed -i "s/CONDITION_NAME/\"\"{{.ALERT_LOW_THROUGHPUT_NAME}}\"\"/g" /tmp/condition.json
           sudo sed -i "s/CONDITION_ID/\"\"$LOW_THROUGHPUT_CONDITION_ID\"\"/g" /tmp/condition.json
