Create a policy per application

diff --git a/recipes/newrelic/infrastructure/alerts/golden.yml b/recipes/newrelic/infrastructure/alerts/golden.yml
--- a/recipes/newrelic/infrastructure/alerts/golden.yml
+++ b/recipes/newrelic/infrastructure/alerts/golden.yml
@@ -46,31 +46,55 @@ install:
           )
           echo 'POLICY_RESULT:'$POLICY_RESULT
 
-          POLICY_ID=$(echo $POLICY_RESULT | ./newrelic utils jq '.policies[] | select(.name=="{{.ALERT_POLICY_NAME}}") | .id')
+          ALERT_POLICY_NAME=$(echo '{{.ALERT_POLICY_BASE_NAME}} {{.HOSTNAME}}')
+          echo 'ALERT_POLICY_NAME:'$ALERT_POLICY_NAME
+          JQ_MATCH=$(echo -n '.policies[] | select(.name=="'$ALERT_POLICY_NAME'") | .id')
+          EXEC=$(echo "echo -n '$POLICY_RESULT' | ./newrelic utils jq '"$JQ_MATCH"'")
+          if [ -f execJq.sh ]; then
+            rm -f execJq.sh
+          fi
+          $(echo $EXEC > execJq.sh)
+          POLICY_ID=$(bash execJq.sh)
           if [ -n "$POLICY_ID" ] && [ $POLICY_ID -gt 0 ] ; then
-            echo 'Alert policy found for '{{.ALERT_POLICY_NAME}}' name POLICY_ID:'$POLICY_ID
+            echo 'Alert policy found for '$ALERT_POLICY_NAME' name POLICY_ID:'$POLICY_ID
           else
-            echo 'No existing alert policy '{{.ALERT_POLICY_NAME}}' found, creating alert policy '{{.ALERT_POLICY_NAME}}
+            echo 'No existing alert policy '$ALERT_POLICY_NAME' found, creating alert policy '$ALERT_POLICY_NAME
+            if [ -f policy.json ]; then
+              rm -f policy.json
+            fi
+            sudo tee -a policy.json > /dev/null <<"EOT"
+          {
+            "policy": {
+              "incident_preference": "PER_POLICY",
+              "name": "ALERT_POLICY_NAME"
+            }
+          }
+          EOT
+            EXEC=$(echo "sed -i 's/ALERT_POLICY_NAME/"$ALERT_POLICY_NAME"/g' policy.json")
+            echo $EXEC > execJq.sh
+            $(bash execJq.sh)
             curl -X POST $NEW_RELIC_ALERT_POLICY_URL \
                 -H 'Api-Key:{{.NEW_RELIC_API_KEY}}' -H 'Auth-Type:User-Api-Key' \
                 -H 'Content-Type: application/json' \
-                -L -d \
-            '{
-              "policy": {
-                "incident_preference": "PER_POLICY",
-                "name": "{{.ALERT_POLICY_NAME}}"
-              }
-            }'
+                -L -d @policy.json
             POLICY_RESULT=$(curl -sX GET $NEW_RELIC_ALERT_POLICY_URL \
                 -H 'Api-Key:{{.NEW_RELIC_API_KEY}}' -H 'Auth-Type:User-Api-Key' \
                 -H 'Content-Type: application/json'
             )
             echo 'POLICY_RESULT:'$POLICY_RESULT
-            POLICY_ID=$(echo $POLICY_RESULT | ./newrelic utils jq '.policies[] | select(.name=="{{.ALERT_POLICY_NAME}}") | .id')
+
+            ALERT_POLICY_NAME=$(echo '{{.ALERT_POLICY_BASE_NAME}} {{.HOSTNAME}}')
+            JQ_MATCH=$(echo -n '.policies[] | select(.name=="'$ALERT_POLICY_NAME'") | .id')
+            EXEC=$(echo "echo -n '$POLICY_RESULT' | ./newrelic utils jq '"$JQ_MATCH"'")
+            if [ -f execJq.sh ]; then
+              rm -f execJq.sh
+            fi
+            $(echo $EXEC > execJq.sh)
+            POLICY_ID=$(bash execJq.sh)
             if [ -n "$POLICY_ID" ] && [ $POLICY_ID -gt 0 ] ; then
-              echo 'Alert policy found for '{{.ALERT_POLICY_NAME}}' name POLICY_ID:'$POLICY_ID
+              echo 'Alert policy found for '$ALERT_POLICY_NAME' name POLICY_ID:'$POLICY_ID
             else
-              echo 'Could not create a new alert policy for '{{.ALERT_POLICY_NAME}}' got POLICY_ID:'$POLICY_ID >> /dev/stderr
+              echo 'Could not create a new alert policy for '$ALERT_POLICY_NAME' got POLICY_ID:'$POLICY_ID >> /dev/stderr
               exit 10
             fi
           fi
@@ -113,8 +137,8 @@ install:
                   "select_value": "cpuPercent",
                   "comparison": "above",
                   "critical_threshold": {
-                      "value": 86,
-                      "duration_minutes": 6,
+                      "value": 80,
+                      "duration_minutes": 10,
                       "time_function": "all"
                   }
               }
@@ -192,6 +216,7 @@ install:
             do
               APP_NAME=$(echo -n "$APP_NAME" | sed s/^\"//g | sed s/\"\$//g)
               echo 'Processing APP_NAME:'$APP_NAME
+
               FILTER=$(echo -n 'filter[name]='$APP_NAME)
               APPLICATION_ID_RESULT=$(curl -sX GET $NEW_RELIC_API_URL'/v2/applications.json' \
                 -H 'Api-Key:{{.NEW_RELIC_API_KEY}}' -H 'Auth-Type:User-Api-Key' \
@@ -207,6 +232,60 @@ install:
               APPLICATION_ID=$(bash execJq.sh)
               if [ -n "$APPLICATION_ID" ] && [ $APPLICATION_ID -gt 0 ] ; then
                 echo 'Found APPLICATION_ID:'$APPLICATION_ID
+
+                ALERT_POLICY_NAME=$(echo '{{.ALERT_POLICY_BASE_NAME}} '$APP_NAME)
+                echo 'ALERT_POLICY_NAME:'$ALERT_POLICY_NAME
+                JQ_MATCH=$(echo -n '.policies[] | select(.name=="'$ALERT_POLICY_NAME'") | .id')
+                EXEC=$(echo "echo -n '$POLICY_RESULT' | ./newrelic utils jq '"$JQ_MATCH"'")
+                if [ -f execJq.sh ]; then
+                  rm -f execJq.sh
+                fi
+                $(echo $EXEC > execJq.sh)
+                POLICY_ID=$(bash execJq.sh)
+                if [ -n "$POLICY_ID" ] && [ $POLICY_ID -gt 0 ] ; then
+                  echo 'Alert policy found for '$ALERT_POLICY_NAME' name POLICY_ID:'$POLICY_ID
+                else
+                  echo 'No existing alert policy '$ALERT_POLICY_NAME' found, creating alert policy '$ALERT_POLICY_NAME
+                  if [ -f policy.json ]; then
+                    rm -f policy.json
+                  fi
+                  sudo tee -a policy.json > /dev/null <<"EOT"
+          {
+            "policy": {
+              "incident_preference": "PER_POLICY",
+              "name": "ALERT_POLICY_NAME"
+            }
+          }
+          EOT
+                  EXEC=$(echo "sed -i 's/ALERT_POLICY_NAME/"$ALERT_POLICY_NAME"/g' policy.json")
+                  echo $EXEC > execJq.sh
+                  $(bash execJq.sh)
+                  curl -X POST $NEW_RELIC_ALERT_POLICY_URL \
+                      -H 'Api-Key:{{.NEW_RELIC_API_KEY}}' -H 'Auth-Type:User-Api-Key' \
+                      -H 'Content-Type: application/json' \
+                      -L -d @policy.json
+                  POLICY_RESULT=$(curl -sX GET $NEW_RELIC_ALERT_POLICY_URL \
+                      -H 'Api-Key:{{.NEW_RELIC_API_KEY}}' -H 'Auth-Type:User-Api-Key' \
+                      -H 'Content-Type: application/json'
+                  )
+                  echo 'POLICY_RESULT:'$POLICY_RESULT
+
+                  ALERT_POLICY_NAME=$(echo '{{.ALERT_POLICY_BASE_NAME}} '$APP_NAME)
+                  JQ_MATCH=$(echo -n '.policies[] | select(.name=="'$ALERT_POLICY_NAME'") | .id')
+                  EXEC=$(echo "echo -n '$POLICY_RESULT' | ./newrelic utils jq '"$JQ_MATCH"'")
+                  if [ -f execJq.sh ]; then
+                    rm -f execJq.sh
+                  fi
+                  $(echo $EXEC > execJq.sh)
+                  POLICY_ID=$(bash execJq.sh)
+                  echo 'POLICY_ID:'$POLICY_ID
+                  if [ -n "$POLICY_ID" ] && [ $POLICY_ID -gt 0 ] ; then
+                    echo 'Alert policy found for '$ALERT_POLICY_NAME' name POLICY_ID:'$POLICY_ID
+                  else
+                    echo 'Could not create a new alert policy for '$ALERT_POLICY_NAME' got POLICY_ID:'$POLICY_ID >> /dev/stderr
+                    exit 10
+                  fi
+                fi
 
                 CONDITION_ID_RESULT=$(curl -sX GET $NEW_RELIC_API_URL'/v2/alerts_conditions.json?policy_id='$POLICY_ID \
                   -H 'Api-Key:{{.NEW_RELIC_API_KEY}}' -H 'Auth-Type:User-Api-Key' \
@@ -264,8 +343,8 @@ install:
           fi
 
       vars:
-        ALERT_POLICY_NAME:
-          sh: echo 'Golden Signal Policy '$(hostname)
+        ALERT_POLICY_BASE_NAME:
+          sh: echo 'Golden Signal Policy'
         ALERT_HIGH_CPU_CONDITION_NAME:
           sh: echo 'High CPU'
         ALERT_HIGH_ERROR_RATE_NAME:
