test commenting out write permission check for golden

diff --git a/recipes/newrelic/infrastructure/alerts/golden.yml b/recipes/newrelic/infrastructure/alerts/golden.yml
--- a/recipes/newrelic/infrastructure/alerts/golden.yml
+++ b/recipes/newrelic/infrastructure/alerts/golden.yml
@@ -82,11 +82,11 @@ install:
             exit 2
           fi
 
-          # check if the user has the write permissions 
-          if [ ! -w "/tmp" ]; then
-            echo "Error: You do not have write permission to the /tmp directory"
-            exit 2
-          fi
+          # # check if the user has the write permissions 
+          # if [ ! -w "/tmp" ]; then
+          #   echo "Error: You do not have write permission to the /tmp directory"
+          #   exit 2
+          # fi
 
           # Check if the filesystem containing the /tmp directory is full
           if [ $(df --output=avail /tmp | tail -n 1) -lt 1 ]; then
