fix(alerts): avoid creating empty policy

diff --git a/recipes/newrelic/infrastructure/alerts/golden.yml b/recipes/newrelic/infrastructure/alerts/golden.yml
--- a/recipes/newrelic/infrastructure/alerts/golden.yml
+++ b/recipes/newrelic/infrastructure/alerts/golden.yml
@@ -81,6 +81,38 @@ install:
             return 0
           fi
 
+          # Check if all required conditions exist under another policy with a different name to not create an empty 'Golden Signals' policy
+          if [ -f /tmp/conditionsSearch.json ]; then
+            sudo rm -f /tmp/conditionsSearch.json
+          fi
+          sudo tee -a /tmp/conditionsSearch.json > /dev/null <<"EOT"
+          {
+            "query": "{actor {account(id: {{.NEW_RELIC_ACCOUNT_ID}}) {alerts {nrqlConditionsSearch {totalCount nrqlConditions { description name id enabled expiration { closeViolationsOnExpiration expirationDuration openViolationOnExpiration } nrql { query } policyId runbookUrl type violationTimeLimitSeconds ... on AlertsNrqlBaselineCondition { id name nrql { query } baselineDirection description enabled expiration { closeViolationsOnExpiration expirationDuration openViolationOnExpiration } policyId runbookUrl type violationTimeLimitSeconds } } } } } } }"
+          }
+          EOT
+          CONDITIONS_LOOKUP_RESULT=$(curl -sX POST $NEW_RELIC_API_URL'/graphql' \
+              -H 'Api-Key:{{.NEW_RELIC_API_KEY}}' \
+              -L -H 'Content-Type: application/json' \
+              -d @/tmp/conditionsSearch.json
+          )
+          if [ -f /tmp/conditionsSearch.json ]; then
+            sudo rm -f /tmp/conditionsSearch.json
+          fi
+
+          HIGH_CPU_CONDITION_ID=$(echo $CONDITIONS_LOOKUP_RESULT | /usr/local/bin/newrelic utils jq 'first(.data.actor.account.alerts.nrqlConditionsSearch.nrqlConditions[] | select(.name=="{{.ALERT_HIGH_CPU_CONDITION_NAME}}") | .id)')
+          HIGH_CPU_CONDITION_ID=$([[ $HIGH_CPU_CONDITION_ID =~ 'null' ]] && echo 0 || echo "${HIGH_CPU_CONDITION_ID//\"/""}")
+          HIGH_ERROR_CONDITION_ID=$(echo $CONDITIONS_LOOKUP_RESULT | /usr/local/bin/newrelic utils jq 'first(.data.actor.account.alerts.nrqlConditionsSearch.nrqlConditions[] | select(.name=="{{.ALERT_HIGH_ERROR_RATE_NAME}}") | .id)')
+          HIGH_ERROR_CONDITION_ID=$([[ $HIGH_ERROR_CONDITION_ID =~ 'null' ]] && echo 0 || echo "${HIGH_ERROR_CONDITION_ID//\"/""}")
+          HIGH_RESPONSE_CONDITION_ID=$(echo $CONDITIONS_LOOKUP_RESULT | /usr/local/bin/newrelic utils jq 'first(.data.actor.account.alerts.nrqlConditionsSearch.nrqlConditions[] | select(.name=="{{.ALERT_HIGH_RESPONSE_TIME_NAME}}") | .id)')
+          HIGH_RESPONSE_CONDITION_ID=$([[ $HIGH_RESPONSE_CONDITION_ID =~ 'null' ]] && echo 0 || echo "${HIGH_RESPONSE_CONDITION_ID//\"/""}")
+          LOW_THROUGHPUT_CONDITION_ID=$(echo $CONDITIONS_LOOKUP_RESULT | /usr/local/bin/newrelic utils jq 'first(.data.actor.account.alerts.nrqlConditionsSearch.nrqlConditions[] | select(.name=="{{.ALERT_LOW_THROUGHPUT_NAME}}") | .id)')
+          LOW_THROUGHPUT_CONDITION_ID=$([[ $LOW_THROUGHPUT_CONDITION_ID =~ 'null' ]] && echo 0 || echo "${LOW_THROUGHPUT_CONDITION_ID//\"/""}")
+
+          if [[ $HIGH_CPU_CONDITION_ID -gt 0 && $HIGH_ERROR_CONDITION_ID -gt 0 && $HIGH_RESPONSE_CONDITION_ID -gt 0 && $LOW_THROUGHPUT_CONDITION_ID ]]; then
+            echo 'All Golden Alerts Conditions are already set up'
+            exit 0
+          fi
+
           echo 'Creating alert policy {{.ALERT_POLICY_NAME}}...'
           if [ -f /tmp/policy.json ]; then
             sudo rm -f /tmp/policy.json
