Ensure systemctl is available before attempting to install the infrastructure agent

diff --git a/recipes/newrelic/infrastructure/amazonlinux2.yml b/recipes/newrelic/infrastructure/amazonlinux2.yml
--- a/recipes/newrelic/infrastructure/amazonlinux2.yml
+++ b/recipes/newrelic/infrastructure/amazonlinux2.yml
@@ -72,6 +72,12 @@ install:
             echo "touch is required to run the newrelic install. Please install touch and re-run the installation." >> /dev/stderr
             exit 15
           fi
+        - |
+          IS_SYSTEMCTL_INSTALLED=$(which systemctl | wc -l)
+          if [ $IS_SYSTEMCTL_INSTALLED -eq 0 ] ; then
+            echo "systemctl is required to install the newrelic infrastructure agent. Installation cannot proceed on this linux version." >> /dev/stderr
+            exit 20
+          fi
 
     setup_license:
       cmds:
diff --git a/recipes/newrelic/infrastructure/ubuntu.yml b/recipes/newrelic/infrastructure/ubuntu.yml
--- a/recipes/newrelic/infrastructure/ubuntu.yml
+++ b/recipes/newrelic/infrastructure/ubuntu.yml
@@ -77,6 +77,14 @@ install:
             exit 15
           fi
         - |
+          IS_SYSTEMCTL_INSTALLED=$(which systemctl | wc -l)
+          if [ $IS_SYSTEMCTL_INSTALLED -eq 0 ] ; then
+            if [ {{.DISTRIB_RELEASE}} -gt 14.04 ]; then
+              echo "systemctl is required to install the newrelic infrastructure agent. Installation cannot proceed on this linux version." >> /dev/stderr
+              exit 20
+            fi
+          fi
+        - |
           IS_INFRA_AVAILABLE=$(curl -Is https://download.newrelic.com/infrastructure_agent/linux/apt/dists/{{.DEBIAN_CODENAME}}/InRelease | grep " 2[0-9][0-9] " | wc -l)
           if [ $IS_INFRA_AVAILABLE -eq 0 ] ; then
             echo "there is no newrelic infrastructure agent available for the distribution '{{.DEBIAN_CODENAME}}'." >> /dev/stderr
@@ -85,6 +93,8 @@ install:
       vars:
         DEBIAN_CODENAME:
           sh: awk -F= '/DISTRIB_CODENAME/ {print $2}' /etc/lsb-release
+        DISTRIB_RELEASE:
+          sh: awk -F= '/DISTRIB_RELEASE/ {print $2}' /etc/lsb-release
 
     setup_license:
       cmds:
