added sudo check to assert prereq

diff --git a/recipes/newrelic/infrastructure/amazonlinux.yml b/recipes/newrelic/infrastructure/amazonlinux.yml
--- a/recipes/newrelic/infrastructure/amazonlinux.yml
+++ b/recipes/newrelic/infrastructure/amazonlinux.yml
@@ -48,6 +48,12 @@ install:
             echo "grep is required to run the newrelic install. Please install grep and re-run the installation." >&2
             exit 10
           fi
+        - | 
+          IS_SUDO_USER=$(grep someuser /etc/sudoers 2>&1 || true) 
+          if [[ -n "$IS_SUDO_USER" ]]; then
+            echo "sudo privileges required to run the newrelic install. Please obtain sudo privileges and re-run the installation." >&2
+            exit 13
+          fi        
         - |
           IS_SED_INSTALLED=$(which sed | wc -l)
           if [ $IS_SED_INSTALLED -eq 0 ] ; then
