Ensure systemctl is up and running (handle WSL ubuntu)

diff --git a/recipes/newrelic/infrastructure/amazonlinux2.yml b/recipes/newrelic/infrastructure/amazonlinux2.yml
--- a/recipes/newrelic/infrastructure/amazonlinux2.yml
+++ b/recipes/newrelic/infrastructure/amazonlinux2.yml
@@ -78,6 +78,12 @@ install:
             echo "systemctl is required to install the newrelic infrastructure agent. Installation cannot proceed on this linux version." >> /dev/stderr
             exit 20
           fi
+        - |
+          IS_SYSTEMCTL_AVAILABLE=$(sudo systemctl status | grep -i running | wc -l)
+          if [ $IS_SYSTEMCTL_AVAILABLE -eq 0 ] ; then
+            echo "systemctl is required to install the newrelic infrastructure agent. System has not been booted with systemd as init system. Installation cannot proceed on this linux version." >> /dev/stderr
+            exit 20
+          fi
 
     setup_license:
       cmds:
diff --git a/recipes/newrelic/infrastructure/ubuntu.yml b/recipes/newrelic/infrastructure/ubuntu.yml
--- a/recipes/newrelic/infrastructure/ubuntu.yml
+++ b/recipes/newrelic/infrastructure/ubuntu.yml
@@ -85,6 +85,12 @@ install:
             fi
           fi
         - |
+          IS_SYSTEMCTL_AVAILABLE=$(sudo systemctl status | grep -i running | wc -l)
+          if [ $IS_SYSTEMCTL_AVAILABLE -eq 0 ] ; then
+            echo "systemctl is required to install the newrelic infrastructure agent. System has not been booted with systemd as init system. Installation cannot proceed on this linux version." >> /dev/stderr
+            exit 20
+          fi
+        - |
           IS_INFRA_AVAILABLE=$(curl -Is https://download.newrelic.com/infrastructure_agent/linux/apt/dists/{{.DEBIAN_CODENAME}}/InRelease | grep " 2[0-9][0-9] " | wc -l)
           if [ $IS_INFRA_AVAILABLE -eq 0 ] ; then
             echo "there is no newrelic infrastructure agent available for the distribution '{{.DEBIAN_CODENAME}}'." >> /dev/stderr
