chore: Add proxy support for ubuntu & debian infra (#882)

diff --git a/recipes/newrelic/infrastructure/centos_rhel.yml b/recipes/newrelic/infrastructure/centos_rhel.yml
--- a/recipes/newrelic/infrastructure/centos_rhel.yml
+++ b/recipes/newrelic/infrastructure/centos_rhel.yml
@@ -160,6 +160,14 @@ install:
           if [ ! -z "$HTTPS_PROXY" ]; then
             sed -i "/^proxy/d" /etc/newrelic-infra.yml
             echo 'proxy: {{.HTTPS_PROXY}}' >> /etc/newrelic-infra.yml
+
+            if ! grep -q '^proxy=' /etc/dnf/dnf.conf; then
+              echo "************************************************************"
+              echo "WARNING: proxy settings not detected in your dnf config"
+              echo "If installation fails with a timeout, add the following line to /etc/dnf/dnf.conf and retry:"
+              echo "proxy={{.HTTPS_PROXY}}"
+              echo "************************************************************"
+            fi
           fi
 
     install_infra:
