Validate we're not installing the infra agent on a docker or windows susbsystem linux

diff --git a/recipes/newrelic/infrastructure/centos_rhel.yml b/recipes/newrelic/infrastructure/centos_rhel.yml
--- a/recipes/newrelic/infrastructure/centos_rhel.yml
+++ b/recipes/newrelic/infrastructure/centos_rhel.yml
@@ -88,6 +88,18 @@ install:
             exit 15
           fi
         - |
+          IS_DOCKER_CONTAINER=$(sudo grep 'docker\|lxc' /proc/1/cgroup | wc -l)
+          if [ $IS_DOCKER_CONTAINER -gt 0 ] ; then
+            echo "The infrastructure agent cannot be installed on a docker container with this tool. Docker containers can be instrumented by following the steps on this documentation https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/linux-installation/docker-container-infrastructure-monitoring/" >> /dev/stderr
+            exit 18
+          fi
+        - |
+          IS_WSL_CONTAINER=$(sudo grep -i 'Microsoft' /proc/version | wc -l)
+          if [ $IS_WSL_CONTAINER -gt 0 ] ; then
+            echo "The infrastructure agent cannot be installed on Microsoft Windows Subsystem for Linux." >> /dev/stderr
+            exit 19
+          fi
+        - |
           IS_SYSTEMCTL_INSTALLED=$(which systemctl | wc -l)
           if [ $IS_SYSTEMCTL_INSTALLED -eq 0 ] ; then
             echo "systemctl is required to install the newrelic infrastructure agent. Installation cannot proceed on this linux version." >> /dev/stderr
