stop agent installation if brew is not installed

diff --git a/recipes/newrelic/infrastructure/darwin.yml b/recipes/newrelic/infrastructure/darwin.yml
--- a/recipes/newrelic/infrastructure/darwin.yml
+++ b/recipes/newrelic/infrastructure/darwin.yml
@@ -78,6 +78,14 @@ install:
             exit 15
           fi
         - |
+          # This check is temporary until the one below that offers to install brew is fixed. Currently it gets stuck
+          # and it doesn't show the message to offer to install brew
+          IS_BREW_INSTALLED=$(which brew | wc -l)
+          if [ $IS_BREW_INSTALLED -eq 0 ] ; then
+            echo "brew is required to run the newrelic install. Please install brew and re-run the installation." >&2
+            exit 131
+          fi
+        - |
           IS_BREW_INSTALLED=$(which brew | wc -l)
           if [ $IS_BREW_INSTALLED -eq 0 ] ; then
             while :; do
@@ -104,10 +112,6 @@ install:
               echo "brew install failed. Try to install it manually following instructions in https://brew.sh and re-run the installation."
               exit 16
             fi
-          fi
-          if [ "{{.V1_HOMEBREW_INSTALL_DIR}}" == "" ] ; then
-            echo "recipe needs to read HOMEBREW_PREFIX from brew. Ensure brew is installed correctly and re-run the installation" >&2
-            exit 16
           fi
         - |
           IS_CURL_INSTALLED=$(which curl | wc -l)
