Fix sed dialect

diff --git a/recipes/newrelic/infrastructure/darwin.yml b/recipes/newrelic/infrastructure/darwin.yml
--- a/recipes/newrelic/infrastructure/darwin.yml
+++ b/recipes/newrelic/infrastructure/darwin.yml
@@ -21,6 +21,11 @@ processMatch: []
 
 validationNrql: "SELECT count(*) from SystemSample where hostname like '{{.HOSTNAME}}' FACET entityGuid SINCE 10 minutes ago"
 
+preInstall:
+  info: |2
+      Note: EXPERIMENTAL RECIPE
+      This installation makes use of homebrew to install the infra agent
+
 install:
   version: "3"
   silent: true
@@ -30,48 +35,61 @@ install:
       cmds:
         - task: assert_pre_req
         - task: setup_license
-        # - task: install_infra
-        # - task: restart
+        - task: install_infra
+        # - task: start
         # - task: assert_agent_started
 
     assert_pre_req:
       cmds:
         - |
-          OSTYPE=$(uname)
-          if [[ "$OSTYPE" == "Darwin" ]]; then
-            echo "On Darwin"
-          else
-            echo "Darwin not detected"
-            exit 21
+          # FIXME check we're *not* running as root
+          IS_HOMEBREW_INSTALLED=$(which -s brew)
+          if [ $? -ne 0 ] ; then
+            echo "homebrew is required to run the newrelic install. Please install homebrew and re-run the installation." >> /dev/stderr
+            exit 10
           fi
+          brew update
+          # OSTYPE=$(uname)
+          # if [[ "$OSTYPE" == "Darwin" ]]; then
+          #   sudo -i -u $SUDO_USER command brew update
+          # else
+          #   echo "Attemept to run Darwin recipe on $OSTYPE - aborting"
+          #   exit 21
+          # fi
  
     setup_license:
       cmds:
         - |
           if [ -f /etc/newrelic-infra.yml ]; then
-            sed -i "/^staging/d" /etc/newrelic-infra.yml
+            sudo sed -i'.bak' -e '/^staging/d' /etc/newrelic-infra.yml
 
-            sed -i "s/^\(license_key: \).*/\1{{.NEW_RELIC_LICENSE_KEY}}/" /etc/newrelic-infra.yml
-            sed -i "s/^\(enable_process_metrics: \).*/\1true/" /etc/newrelic-infra.yml
+            sudo sed -i'.bak' -e "s/^\(license_key: \).*/\1{{.NEW_RELIC_LICENSE_KEY}}/" /etc/newrelic-infra.yml
+            sudo sed -i'.bak' -e 's/^\(enable_process_metrics: \).*/\1true/' /etc/newrelic-infra.yml
           else
+            # Because we need to use sudo on mac, we have to start a proper bash shell to avoid
+            # problems with output redirection
             sudo touch /etc/newrelic-infra.yml
-            sudo cat > /etc/newrelic-infra.yml <<EOT
-          license_key: {{.NEW_RELIC_LICENSE_KEY}}
-          enable_process_metrics: true
-          EOT
+            sudo bash -c "echo \"license_key: {{.NEW_RELIC_LICENSE_KEY}}\" >> /etc/newrelic-infra.yml"
+            sudo bash -c "echo 'enable_process_metrics: true' >> /etc/newrelic-infra.yml"
           fi
         - |
           if [ $(echo {{.NEW_RELIC_REGION}} | grep -i staging | wc -l) -gt 0 ]; then
-            sudo echo 'staging: true' >> /etc/newrelic-infra.yml
+            sudo bash -c "echo 'staging: true' >> /etc/newrelic-infra.yml"
           fi
 
     install_infra:
       cmds:
         - |
-          brew install ...
+          IS_INFRA_AGENT_INSTALLED=$(brew list newrelic-infra-agent)
+          if [ $? -ne 0 ] ; then
+            echo "Installing newrelic-infra-agent..."
+            brew install newrelic-infra-agent
+          else
+            echo "newrelic-infra-agent already installed"
+          fi
       silent: false
 
-    restart:
+    start:
       cmds:
         - |
           if [ {{.IS_SYSTEMCTL}} -gt 0 ]; then
