feat: check apt state as pre-req

diff --git a/recipes/newrelic/infrastructure/debian.yml b/recipes/newrelic/infrastructure/debian.yml
--- a/recipes/newrelic/infrastructure/debian.yml
+++ b/recipes/newrelic/infrastructure/debian.yml
@@ -114,6 +114,12 @@ install:
               exit 131
             fi
           fi
+        - |
+          APT_ERRS=$(sudo apt-get update -yq 2>&1 | grep "Err:" | wc -l )
+          if [ $APT_ERR_COUNT -gt 0 ] ; then
+            echo "there is an error with the apt state. $(sudo apt-get update -yq 2>&1 | grep "Err:")" >&2
+            exit 131
+          fi
       vars:
         DEBIAN_CODENAME:
           sh: awk -F= '/VERSION_CODENAME/ {print $2}' /etc/os-release
diff --git a/recipes/newrelic/infrastructure/ubuntu.yml b/recipes/newrelic/infrastructure/ubuntu.yml
--- a/recipes/newrelic/infrastructure/ubuntu.yml
+++ b/recipes/newrelic/infrastructure/ubuntu.yml
@@ -103,6 +103,12 @@ install:
             echo "there is no newrelic infrastructure agent available for the distribution '{{.DEBIAN_CODENAME}}'." >&2
             exit 131
           fi
+        - |
+          APT_ERRS=$(sudo apt-get update -yq 2>&1 | grep "Err:" | wc -l )
+          if [ $APT_ERR_COUNT -gt 0 ] ; then
+            echo "there is an error with the apt state. $(sudo apt-get update -yq 2>&1 | grep "Err:")" >&2
+            exit 131
+          fi
       vars:
         DEBIAN_CODENAME:
           sh: awk -F= '/DISTRIB_CODENAME/ {print $2}' /etc/lsb-release
