Rename kubernetes display texts

diff --git a/recipes/newrelic/infrastructure/kubernetes.yml b/recipes/newrelic/infrastructure/kubernetes.yml
--- a/recipes/newrelic/infrastructure/kubernetes.yml
+++ b/recipes/newrelic/infrastructure/kubernetes.yml
@@ -2,8 +2,8 @@
 # https://github.com/newrelic/open-install-library/blob/main/docs/recipe-spec/recipe-spec.md#schema-definition
 
 name: kubernetes-open-source-integration
-displayName: Kubernetes Open Source Integration
-description: New Relic install recipe for the Kubernetes Open Source integration
+displayName: Kubernetes Integration
+description: New Relic install recipe for the Kubernetes integration
 repository: https://github.com/newrelic/nri-kubernetes
 
 installTargets:
@@ -30,7 +30,7 @@ successLinkConfig:
 
 preInstall:
   info: |2
-    The Kubernetes Open Source Integration installation will use Helm if available.
+    The Kubernetes Integration installation will use Helm if available.
     If Helm is not available a manifest will be generated and applied using kubectl.
 
   requireAtDiscovery: |
@@ -38,7 +38,7 @@ preInstall:
 
     # Check the required tools
     if ! $SUDO which kubectl 1>/dev/null 2>&1; then
-      echo "kubectl is required to install the Kubernetes Open Source Integration." >&2
+      echo "kubectl is required to install the Kubernetes Integration." >&2
       exit 10
     fi
     if ! which curl 1>/dev/null 2>&1 ; then
@@ -341,7 +341,7 @@ install:
 
           # Show post install message
           echo ""
-          echo "The Kubernetes Open Sources Integration deploymented is complete. You can check the progress by running"
+          echo "The Kubernetes Integration deploymented is complete. You can check the progress by running"
           echo ""
           echo "     kubectl get pods -o wide -n ${NR_CLI_NAMESPACE}"
           echo ""
