Provide better error message in case kubectl cannot connect to the Kubernetes cluster.

diff --git a/recipes/newrelic/infrastructure/kubernetes.yml b/recipes/newrelic/infrastructure/kubernetes.yml
--- a/recipes/newrelic/infrastructure/kubernetes.yml
+++ b/recipes/newrelic/infrastructure/kubernetes.yml
@@ -101,20 +101,30 @@ install:
           fi
 
           # Check the Kubernetes version
-          KUBECTL_VERSION=$($SUDO $KUBECTL version --short)
+          KUBECTL_VERSION=$($SUDO $KUBECTL version --short 2>&1)
           CLIENT_MAJOR_VERSION=$(echo "${KUBECTL_VERSION}" | grep 'Client Version' | awk -F' v' '{ print $2; }' | awk -F. '{ print $1; }')
           CLIENT_MINOR_VERSION=$(echo "${KUBECTL_VERSION}" | grep 'Client Version' | awk -F' v' '{ print $2; }' | awk -F. '{ print $2; }')
           SERVER_MAJOR_VERSION=$(echo "${KUBECTL_VERSION}" | grep 'Server Version' | awk -F' v' '{ print $2; }' | awk -F. '{ print $1; }')
           SERVER_MINOR_VERSION=$(echo "${KUBECTL_VERSION}" | grep 'Server Version' | awk -F' v' '{ print $2; }' | awk -F. '{ print $2; }')
 
+          if [[ $SERVER_MAJOR_VERSION == "" && $SERVER_MINOR_VERSION == "" ]]; then
+            if echo $KUBECTL_VERSION | grep refused >/dev/null; then
+              echo "kubectl could not connect to the Kubernetes cluster. Check your kubectl configuration, make sure it can connect to your cluster and re-run this command." >&2
+              exit 21
+            else
+              echo "Failed to determine the Kubernetes server version from ${KUBECTL_VERSION}" >&2
+              exit 22
+            fi
+          fi
+
           if [[ "$CLIENT_MAJOR_VERSION" -lt 1 ]] || [[ "$CLIENT_MAJOR_VERSION" -eq 1 && "$CLIENT_MINOR_VERSION" -lt 10 ]]; then
             echo "kubectl v1.10 or higher is required, found v${CLIENT_MAJOR_VERSION}.${CLIENT_MINOR_VERSION}" >&2
-            exit 21
+            exit 23
           fi
 
           if [[ "$SERVER_MAJOR_VERSION" -lt 1 ]] || [[ "$SERVER_MAJOR_VERSION" -eq 1 && "$SERVER_MINOR_VERSION" -lt 16 ]]; then
             echo "Kubernetes v1.16 or higher is required, found v${SERVER_MAJOR_VERSION}.${SERVER_MINOR_VERSION}" >&2
-            exit 22
+            exit 24
           fi
 
           # Determine the cluster name if not provided
