helm 2 logic

diff --git a/recipes/newrelic/infrastructure/kubernetes.yml b/recipes/newrelic/infrastructure/kubernetes.yml
--- a/recipes/newrelic/infrastructure/kubernetes.yml
+++ b/recipes/newrelic/infrastructure/kubernetes.yml
@@ -30,8 +30,8 @@ successLinkConfig:
 
 preInstall:
   info: |2
-    The Kubernetes Integration installation will use Helm if available.
-    If Helm is not available a manifest will be generated and applied using kubectl.
+    The Kubernetes Integration installation will use Helm 3 if available.
+    If Helm 3 is not available a manifest will be generated and applied using kubectl.
 
   requireAtDiscovery: |
     SUDO=$(test ! -z "$SUDO_USER" && echo "sudo -u $SUDO_USER" || echo "")
@@ -343,8 +343,30 @@ install:
             fi
           fi
 
+
+          # Check for the presence of Helm.
+          # If Helm 3 is not found, revert to kubectl based install.
+          if ! $SUDO which helm 1>/dev/null 2>&1
+          then
+                  echo ""
+                  echo "Helm not found."
+                  echo "Reverting to kubectl install."
+                  echo ""
+                  KUBECTL_INSTALL=true
+
+          elif ! $SUDO helm version -c --short | grep v3 1> /dev/null 2>&1
+          then
+                  echo ""
+                  echo "Helm 3 not found.  You are using an unsupported version of helm."
+                  helm version -c --short
+                  echo "Reverting to kubectl install."
+                  echo ""
+                  KUBECTL_INSTALL=true
+          fi
+
           # Deploy the integration
-          if $SUDO which helm 1>/dev/null 2>&1; then
+          if $SUDO which helm 1>/dev/null 2>&1 && $SUDO helm version -c --short | grep v3 1> /dev/null 2>&1
+          then
             echo ""
             echo "Using helm to install the Kubernetes integration"
             echo ""
@@ -395,12 +417,19 @@ install:
             echo "Using kubectl to install the Kubernetes integration"
             echo ""
 
-            URL="https://k8s-config-generator.service.newrelic.com"
+            # Select k8s-config-generator service environment
+            if [[ "${NEW_RELIC_REGION}" == "STAGING" ]]; then
+              URL="https://k8s-config-generator.staging-service.newrelic.com"
+            else
+              URL="https://k8s-config-generator.service.newrelic.com"
+            fi
+
             if [[ "${NR_CLI_BETA}" == "true" ]]; then
               URL="${URL}/generate-beta"
             else
               URL="${URL}/generate"
             fi
+
             BODY="{\"global.cluster\":\"${NR_CLI_CLUSTERNAME}\""
             BODY="${BODY},\"global.namespace\":\"${NR_CLI_NAMESPACE}\""
             BODY="${BODY},\"newrelic-infrastructure.privileged\":\"${NR_CLI_PRIVILEGED}\""
@@ -413,6 +442,7 @@ install:
             if [[ "${NEW_RELIC_REGION}" == "STAGING" ]]; then
               BODY="${BODY},\"global.nrStaging\":true"
             fi
+
             if [[ "${NR_CLI_NEWRELIC_PIXIE}" == "true" && "${PIXIE_SUPPORTED}" == "true" ]]; then
               BODY="${BODY},\"newrelic-pixie.enabled\":true"
               BODY="${BODY},\"newrelic-pixie.apiKey\":\"${NR_CLI_PIXIE_API_KEY}\""
@@ -433,9 +463,16 @@ install:
                 fi
               fi
             fi
+
             BODY="${BODY}}"
-            curl -s -H "Content-Type: application/json" -d "${BODY}" "${URL}" > newrelic-k8s.yml
-            $SUDO $KUBECTL apply -f newrelic-k8s.yml
+            curl -s -H "Content-Type: application/json" -d "${BODY}" "${URL}" > ~/newrelic-k8s.yml
+
+            if [[ "${NR_CLI_PIXIE}" == "true" ]]; then
+              $SUDO $KUBECTL apply -f https://raw.githubusercontent.com/pixie-io/pixie/main/k8s/operator/helm/crds/olm_crd.yaml
+              $SUDO $KUBECTL apply -f https://raw.githubusercontent.com/pixie-io/pixie/main/k8s/operator/crd/base/px.dev_viziers.yaml
+            fi
+
+            $SUDO $KUBECTL apply -f ~/newrelic-k8s.yml
           fi
 
           # Wait on nrk8s-kubelet pod to be running
@@ -458,13 +495,24 @@ install:
             sleep 2
           done
 
+          # Set the color variable
+          green='\033[0;32m'
+          clear='\033[0m'
+
           # Show post install message
           echo ""
-          echo "The Kubernetes Integration deployment is complete. You can check the progress by running"
+          echo "--------------------------"
+          echo ""
+          echo "The Kubernetes Integration deployment is complete. You can check the progress by running:"
           echo ""
           echo "     kubectl get pods -o wide -n ${NR_CLI_NAMESPACE}"
           echo ""
 
-          if ! $SUDO which helm 1>/dev/null 2>&1; then
-            echo "Store the generated newrelic-k8s.yml file in a safe location in order to upgrade or remove the integration."
+          if $KUBECTL_INSTALL; then
+            printf "** Store the generated ${green}$HOME/newrelic-k8s.yml${clear} file in a safe location in order to upgrade or remove the integration. **"
+            echo ""
           fi
+
+          echo ""
+          echo "--------------------------"
+          echo ""
