update echo commands

diff --git a/recipes/newrelic/infrastructure/kubernetes.yml b/recipes/newrelic/infrastructure/kubernetes.yml
--- a/recipes/newrelic/infrastructure/kubernetes.yml
+++ b/recipes/newrelic/infrastructure/kubernetes.yml
@@ -444,7 +444,7 @@ install:
 
             KUBECTL_INSTALL=false
 
-            HELM_VERSION=$($SUDO helm version -c --short)
+            HELM_VERSION="$($SUDO helm version -c --short)"
             # Check if nri-bundle already installed, ask customer if they want uninstall before re-installation, and then move forward.
             GREEN='\033[0;32m'
             NC='\033[0m'
@@ -482,13 +482,13 @@ install:
 
             if [[ $($SUDO helm repo add newrelic https://helm-charts.newrelic.com) ]]; then
             else
-              echo “ERROR $? returned from: $SUDO helm repo add newrelic https://helm-charts.newrelic.com; helm version: $HELM_VERSION”
+              echo "ERROR $? returned from (helm-version: $HELM_VERSION): $SUDO helm repo add newrelic https://helm-charts.newrelic.com"
               exit 131
             fi
 
             if [[ $($SUDO helm repo update) ]] ; then
             else
-              echo “ERROR $? returned from: $SUDO helm repo update; helm version: $HELM_VERSION”
+              echo "ERROR $? returned from (helm-version: $HELM_VERSION): $SUDO helm repo update"
               exit 131
             fi
 
@@ -652,7 +652,7 @@ install:
 
             if [[ $($SUDO $KUBECTL apply -f $KUBECTL_YAML_DIR/newrelic-k8s.yml) ]]; then
             else
-              echo “ERROR $? returned from: $SUDO $KUBECTL apply -f $KUBECTL_YAML_DIR/newrelic-k8s.yml; helm version: $HELM_VERSION”
+              echo "ERROR $? returned from (helm-version: $HELM_VERSION): $SUDO $KUBECTL apply -f $KUBECTL_YAML_DIR/newrelic-k8s.yml"
               exit 131
             fi
           fi
