Adding few more dependency check and error message

diff --git a/recipes/newrelic/infrastructure/ubuntu.yml b/recipes/newrelic/infrastructure/ubuntu.yml
--- a/recipes/newrelic/infrastructure/ubuntu.yml
+++ b/recipes/newrelic/infrastructure/ubuntu.yml
@@ -59,10 +59,28 @@ install:
             exit 12
           fi
         - |
+          IS_CAT_INSTALLED=$(which cat | wc -l)
+          if [ $IS_CAT_INSTALLED -eq 0 ] ; then
+            echo "cat is required to run the newrelic install. Please install cat and re-run the installation." >> /dev/stderr
+            exit 13
+          fi
+        - |
+          IS_TEE_INSTALLED=$(which tee | wc -l)
+          if [ $IS_TEE_INSTALLED -eq 0 ] ; then
+            echo "tee is required to run the newrelic install. Please install tee and re-run the installation." >> /dev/stderr
+            exit 14
+          fi
+        - |
+          IS_TOUCH_INSTALLED=$(which touch | wc -l)
+          if [ $IS_TOUCH_INSTALLED -eq 0 ] ; then
+            echo "touch is required to run the newrelic install. Please install touch and re-run the installation." >> /dev/stderr
+            exit 15
+          fi
+        - |
           IS_INFRA_AVAILABLE=$(curl -Is https://download.newrelic.com/infrastructure_agent/linux/apt/dists/{{.DEBIAN_CODENAME}}/InRelease | grep " 200 " | wc -l)
           if [ $IS_INFRA_AVAILABLE -eq 0 ] ; then
             echo "there is no newrelic infrastructure agent available for the distribution '{{.DEBIAN_CODENAME}}'." >> /dev/stderr
-            exit 13
+            exit 21
           fi
       vars:
         DEBIAN_CODENAME:
