good with rhel script, need to update debian

diff --git a/recipes/newrelic/infrastructure/ohi/postgres/debian.yml b/recipes/newrelic/infrastructure/ohi/postgres/debian.yml
--- a/recipes/newrelic/infrastructure/ohi/postgres/debian.yml
+++ b/recipes/newrelic/infrastructure/ohi/postgres/debian.yml
@@ -115,32 +115,41 @@ install:
 
           if [[ "$NEW_RELIC_ASSUME_YES" != "true" ]]; then
             while [[ $TRIES -lt {{.MAX_RETRIES}} && "$CAN_CONNECT" == "7" ]]; do
-              printf "Postgres Port (default: 5432): "
+              printf "\nPlease enter the port number for your PostgreSQL instance: "
               read -r NR_CLI_DB_PORT
               NR_CLI_DB_PORT=${NR_CLI_DB_PORT:-5432}
               ((TRIES++))
               CAN_CONNECT=$(curl $NR_CLI_DB_HOSTNAME:$NR_CLI_DB_PORT 2>&1 1>/dev/null -s -S | awk -F'[()]' '{print $2}')
               CAN_CONNECT=${CAN_CONNECT:-0}
 
-              if [ $CAN_CONNECT == "6" ]; then
-                printf "\n[Error]: Provided host ($NR_CLI_DB_HOSTNAME) cannot be reached.\nSee https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/postgresql-monitoring-integration#comp-req for more info.\n" >&2
-                if [ ! $TRIES -lt {{.MAX_RETRIES}} ]; then exit 6; fi
-                echo "Please try again"
-              elif [ $CAN_CONNECT == "7" ]; then
-                printf "\n[Error]: Connections to port ($NR_CLI_DB_PORT) are being refused.\nSee https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/postgresql-monitoring-integration#comp-req for more info.\n" >&2
+              if [ $CAN_CONNECT == "7" ]; then
+                printf "\n\nUnable to connect your PostgreSQL instance using provided port.\n" >&2
                 if [ ! $TRIES -lt {{.MAX_RETRIES}} ]; then exit 7; fi
                 echo "Please try again"
-              else
-                break
               fi
             done
           fi
 
           # if it's generated default user, attempt to create 
           if [ "$NR_CLI_DB_USERNAME" -eq "newrelic" ] && [ "$NR_CLI_DB_PASSWORD" -eq "$GEN_PASSWORD" ]; then
-            sudo -u postgres psql -c "SELECT 1 FROM pg_roles WHERE rolname='$NR_CLI_DB_USERNAME'" | grep -q 1 || sudo -u postgres psql -c "CREATE USER $NR_CLI_DB_USERNAME" > /dev/null 2> /dev/null
-            sudo -u postgres psql -c "ALTER USER newrelic WITH PASSWORD '$NR_CLI_DB_PASSWORD'" >> /dev/null 2> /dev/null
+            sudo tee .script.sql > /dev/null <<EOT
+
+              BEGIN                                                                                                                                                                                                                │
+               IF NOT EXISTS (                                                                                                                                                                                                   │
+                  SELECT FROM pg_catalog.pg_roles  -- SELECT list can be empty for this                                                                                                                                          │
+                  WHERE  rolname = 'newrelic') THEN                                                                                                                                                                             │
+                  CREATE ROLE newrelic2  LOGIN PASSWORD "$GEN_PASSWORD";                                                                                                                                                           │
+               END IF;                                                                                                                                                                                                           │
+               ALTER USER newrelic2 WITH PASSWORD '$GEN_PASSWORD';                                                                                                                                                                  │
+               GRANT SELECT ON pg_stat_database TO \"$NR_CLI_DB_USERNAME\"" 
+               GRANT SELECT ON pg_stat_database_conflicts TO \"$NR_CLI_DB_USERNAME\""
+               GRANT SELECT ON pg_stat_bgwriter TO \"$NR_CLI_DB_USERNAME\""
+             END5
+
+            EOT
           fi
+          
+          exit 12345
 
           IS_DATABASE_VALID=$(PGPASSWORD=$NR_CLI_DB_PASSWORD psql -U $NR_CLI_DB_USERNAME -w $NR_CLI_DATABASE -h $NR_CLI_DB_HOSTNAME -p $NR_CLI_DB_PORT -c "select version();" 2>&1 | grep -i PostgreSQL | grep -v grep | wc -l)
 
diff --git a/recipes/newrelic/infrastructure/ohi/postgres/rhel.yml b/recipes/newrelic/infrastructure/ohi/postgres/rhel.yml
--- a/recipes/newrelic/infrastructure/ohi/postgres/rhel.yml
+++ b/recipes/newrelic/infrastructure/ohi/postgres/rhel.yml
@@ -40,9 +40,9 @@ successLinkConfig:
 
 preInstall:
   info: |2
-      To capture data from the PostgreSQL integration, we need to create a new PostgreSQL user with specific permissions (READ).
+      To capture data from the PostgreSQL integration, we need to create a newrelic user with specific permissions (READ).
       The installation will create a strong randomly generated password for that new user.
-      This installation may prompt for a pre-created user and password if the automatic user creation task failed.
+      This installation may prompt for your PostgreSQL root user password in order to create this new user.
       More information regarding the prerequisites can be found at https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/postgresql-monitoring-integration#comp-req
 
 install:
@@ -117,81 +117,59 @@ install:
           CAN_CONNECT=$(curl $NR_CLI_DB_HOSTNAME:$NR_CLI_DB_PORT 2>&1 1>/dev/null -s -S | awk -F'[()]' '{print $2}')
           CAN_CONNECT=${CAN_CONNECT:-0}
 
-          if [[ "$CAN_CONNECT" == "6" ]] || [[ "$CAN_CONNECT" == "7" ]] ; then
-            if [[ "$NEW_RELIC_ASSUME_YES" != "true" ]]; then
-              while [ $TRIES -lt {{.MAX_RETRIES}} ]; do
-                printf "Postgres Port (default: 5432): "
-                read -r NR_CLI_DB_PORT
-                NR_CLI_DB_PORT=${NR_CLI_DB_PORT:-5432}
-                ((TRIES++))
-                CAN_CONNECT=$(curl $NR_CLI_DB_HOSTNAME:$NR_CLI_DB_PORT 2>&1 1>/dev/null -s -S | awk -F'[()]' '{print $2}')
-                CAN_CONNECT=${CAN_CONNECT:-0}
+          if [[ "$NEW_RELIC_ASSUME_YES" != "true" ]]; then
+            while [[ $TRIES -lt {{.MAX_RETRIES}} && "$CAN_CONNECT" == "7" ]]; do
+              printf "\nPlease enter the port number for your PostgreSQL instance: "
+              read -r NR_CLI_DB_PORT
+              ((TRIES++))
+              CAN_CONNECT=$(curl $NR_CLI_DB_HOSTNAME:$NR_CLI_DB_PORT 2>&1 1>/dev/null -s -S | awk -F'[()]' '{print $2}')
+              CAN_CONNECT=${CAN_CONNECT:-0}
 
-                if [ $CAN_CONNECT == "6" ]; then
-                  printf "\n[Error]: Provided host ($NR_CLI_DB_HOSTNAME) cannot be reached.\nSee https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/postgresql-monitoring-integration#comp-req for more info.\n" >&2
-                  if [ ! $TRIES -lt {{.MAX_RETRIES}} ]; then exit 6; fi
-                  echo "Please try again"
-                elif [ $CAN_CONNECT == "7" ]; then
-                  printf "\n[Error]: Connections to port ($NR_CLI_DB_PORT) are being refused.\nSee https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/postgresql-monitoring-integration#comp-req for more info.\n" >&2
-                  if [ ! $TRIES -lt {{.MAX_RETRIES}} ]; then exit 7; fi
-                  echo "Please try again"
-                else
-                  break
-                fi
-              done
+              if [ $CAN_CONNECT == "7" ]; then
+                printf "\n\nUnable to connect your PostgreSQL instance using provided port.\n" >&3
+                if [ ! $TRIES -lt {{.MAX_RETRIES}} ]; then exit 7; fi
+                echo "Please try again"
+              fi
+            done
+          fi
+          
+          try_create_user () {
+            # if it's generated default user, attempt to create 
+            if [ "$NR_CLI_DB_USERNAME" -eq "newrelic" ] && [ "$NR_CLI_DB_PASSWORD" -eq "$GEN_PASSWORD" ]; then
+              sudo rm -f .nr_script.sql >&2
+              sudo tee .nr_script.sql > /dev/null <<EOT
+          DO
+          \$do\$
+          BEGIN
+            IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE  rolname = 'newrelic') THEN
+              CREATE ROLE newrelic LOGIN PASSWORD '$GEN_PASSWORD';
+            END IF;
+            ALTER USER newrelic WITH PASSWORD '$GEN_PASSWORD';
+            GRANT SELECT ON pg_stat_database TO \"$NR_CLI_DB_USERNAME\";
+            GRANT SELECT ON pg_stat_database_conflicts TO \"$NR_CLI_DB_USERNAME\";
+            GRANT SELECT ON pg_stat_bgwriter TO \"$NR_CLI_DB_USERNAME\";
+          END
+          \$do\$;
+
+          EOT
+              sql="$(<".nr_script.sql")"
+              sudo -u postgres psql -t -A -c "${sql}" > /dev/null 2>&1 || true
+              sudo rm -f .nr_script.sql > /dev/null 2>&1
             fi
-          fi
-
-          echo env >&2
-          # if it's generated default user, attempt to create 
-          if [ "$NR_CLI_DB_USERNAME" -eq "newrelic" ] && [ "$NR_CLI_DB_PASSWORD" -eq "$GEN_PASSWORD" ]; then
-            sudo -i -u postgres psql -c "SELECT 1 FROM pg_roles WHERE rolname='$NR_CLI_DB_USERNAME'" | grep -q 1 || sudo -i -u postgres psql -c "CREATE USER $NR_CLI_DB_USERNAME"  > /dev/null 2> /dev/null
-            sudo -i -u postgres psql -c "ALTER USER newrelic WITH PASSWORD '$NR_CLI_DB_PASSWORD'"  > /dev/null 2> /dev/null
-          fi
-
-          IS_DATABASE_VALID=$(PGPASSWORD=$NR_CLI_DB_PASSWORD psql -U $NR_CLI_DB_USERNAME -w $NR_CLI_DATABASE -h $NR_CLI_DB_HOSTNAME -p $NR_CLI_DB_PORT -c "select version();" 2>&1 | grep -i PostgreSQL | grep -v grep | wc -l)
-
-          # if default failed, prompt user
-          if [ $IS_DATABASE_VALID -eq 0 ] ; then
-            TRIES=0
-            if [[ "$NEW_RELIC_ASSUME_YES" != "true" ]]; then
-              while [ $TRIES -lt {{.MAX_RETRIES}} ]; do
-                printf "Postgres Username: "
-                read -r NR_CLI_DB_USERNAME
-                printf "Postgres Password: "
-                stty -echo
-                read -r NR_CLI_DB_PASSWORD
-                stty echo
-                printf "\nPostgres Database (default: postgres): "
-                read -r NR_CLI_DATABASE
-                NR_CLI_DATABASE=${NR_CLI_DATABASE:-postgres}
-                ((TRIES++))
-                if [ "$NR_CLI_DB_USERNAME" == "" ] || [ "$NR_CLI_DB_PASSWORD" == "" ]; then
-                  printf "\n[Error]: Please provide a valid Username and Password. Fields cannot be blank.\n" >&2
-                  if [ ! $TRIES -lt {{.MAX_RETRIES}} ]; then exit 4; else continue; fi
-                  echo "Please try again"
-                  continue
-                fi
-
-                IS_DATABASE_VALID=$(PGPASSWORD=$NR_CLI_DB_PASSWORD psql -U $NR_CLI_DB_USERNAME -w $NR_CLI_DATABASE -h $NR_CLI_DB_HOSTNAME -p $NR_CLI_DB_PORT -c "select version();" 2>&1 | grep -i PostgreSQL | grep -v grep | wc -l)
-
-                if [ $IS_DATABASE_VALID -eq 0 ] ; then
-                  printf "\n[Error]: The provided database name is not accessible with the provided username and password and port.\nSee https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/postgresql-monitoring-integration#comp-req for more info.\n" >&2
-                  if [ ! $TRIES -lt {{.MAX_RETRIES}} ]; then exit 2; else continue; fi
-                  echo "Please try again"
-                fi
-                break
-              done
-              printf "\nConnectivity and User Credentials are valid!\n\n"
-            fi
-          fi
-
-          IS_DATABASE_VALID=$(PGPASSWORD=$NR_CLI_DB_PASSWORD psql -U $NR_CLI_DB_USERNAME -w $NR_CLI_DATABASE -h $NR_CLI_DB_HOSTNAME -p $NR_CLI_DB_PORT -c "select version();" 2>&1 | grep -i PostgreSQL | grep -v grep | wc -l)
-          if [ $IS_DATABASE_VALID -ne 0 ] ; then
-            # grant the user permissions
-            sudo -i -u postgres psql -c "GRANT SELECT ON pg_stat_database TO \"$NR_CLI_DB_USERNAME\"" > /dev/null 2> /dev/null
-            sudo -i -u postgres psql -c "GRANT SELECT ON pg_stat_database_conflicts TO \"$NR_CLI_DB_USERNAME\"" > /dev/null 2> /dev/null
-            sudo -i -u postgres psql -c "GRANT SELECT ON pg_stat_bgwriter TO \"$NR_CLI_DB_USERNAME\"" > /dev/null 2> /dev/nul 
+            IS_DATABASE_VALID=$(PGPASSWORD=$NR_CLI_DB_PASSWORD psql -U $NR_CLI_DB_USERNAME -w $NR_CLI_DATABASE -h $NR_CLI_DB_HOSTNAME -p $NR_CLI_DB_PORT -c "select version();" 2>&1 | grep -i PostgreSQL | grep -v grep | wc -l)
+            IS_DATABASE_VALID=${IS_DATABASE_VALID:-0}
+          }
+          
+          try_create_user
+          TRIES=0
+          while [[ $TRIES -lt {{.MAX_RETRIES}} && $IS_DATABASE_VALID -eq "0" ]]; do
+            ((TRIES++))
+            printf "\n\nUnable to create the required newrelic user.  PostgreSQL account password is required.  Please try again.\n\n" >&3
+            try_create_user
+          done
+          
+          if [[ $IS_DATABASE_VALID -eq "0" ]]; then
+            exit 4;
           fi
 
           if [ "$NR_CLI_DB_USERNAME" == "" ]; then
