Added check for non-default port in non-interactive mode

diff --git a/recipes/newrelic/infrastructure/ohi/postgres/debian.yml b/recipes/newrelic/infrastructure/ohi/postgres/debian.yml
--- a/recipes/newrelic/infrastructure/ohi/postgres/debian.yml
+++ b/recipes/newrelic/infrastructure/ohi/postgres/debian.yml
@@ -127,6 +127,11 @@ install:
                 echo "Please try again"
               fi
             done
+          else 
+            if [[ "$CAN_CONNECT" == "7" ]]; then 
+              printf "\n\nUnable to connect your PostgreSQL instance using provided port.\n" >&2
+              exit 7 
+            fi
           fi
           
           TRIES=0
