[TODO]

diff --git a/recipes/newrelic/infrastructure/ohi/postgres/debian.yml b/recipes/newrelic/infrastructure/ohi/postgres/debian.yml
--- a/recipes/newrelic/infrastructure/ohi/postgres/debian.yml
+++ b/recipes/newrelic/infrastructure/ohi/postgres/debian.yml
@@ -113,29 +113,27 @@ install:
           CAN_CONNECT=$(curl $NR_CLI_DB_HOSTNAME:$NR_CLI_DB_PORT 2>&1 1>/dev/null -s -S | awk -F'[()]' '{print $2}')
           CAN_CONNECT=${CAN_CONNECT:-0}
 
-          if [[ "$CAN_CONNECT" == "6" ]] || [[ "$CAN_CONNECT" == "7" ]] ; then
-            if [[ "$NEW_RELIC_ASSUME_YES" != "true" ]]; then
-              while [ $TRIES -lt {{.MAX_RETRIES}} ]; do
-                printf "Postgres Port (default: 5432): "
-                read -r NR_CLI_DB_PORT
-                NR_CLI_DB_PORT=${NR_CLI_DB_PORT:-5432}
-                ((TRIES++))
-                CAN_CONNECT=$(curl $NR_CLI_DB_HOSTNAME:$NR_CLI_DB_PORT 2>&1 1>/dev/null -s -S | awk -F'[()]' '{print $2}')
-                CAN_CONNECT=${CAN_CONNECT:-0}
+          if [[ "$NEW_RELIC_ASSUME_YES" != "true" ]]; then
+            while [[ $TRIES -lt {{.MAX_RETRIES}} && "$CAN_CONNECT" == "7" ]]; do
+              printf "Postgres Port (default: 5432): "
+              read -r NR_CLI_DB_PORT
+              NR_CLI_DB_PORT=${NR_CLI_DB_PORT:-5432}
+              ((TRIES++))
+              CAN_CONNECT=$(curl $NR_CLI_DB_HOSTNAME:$NR_CLI_DB_PORT 2>&1 1>/dev/null -s -S | awk -F'[()]' '{print $2}')
+              CAN_CONNECT=${CAN_CONNECT:-0}
 
-                if [ $CAN_CONNECT == "6" ]; then
-                  printf "\n[Error]: Provided host ($NR_CLI_DB_HOSTNAME) cannot be reached.\nSee https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/postgresql-monitoring-integration#comp-req for more info.\n" >&2
-                  if [ ! $TRIES -lt {{.MAX_RETRIES}} ]; then exit 6; fi
-                  echo "Please try again"
-                elif [ $CAN_CONNECT == "7" ]; then
-                  printf "\n[Error]: Connections to port ($NR_CLI_DB_PORT) are being refused.\nSee https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/postgresql-monitoring-integration#comp-req for more info.\n" >&2
-                  if [ ! $TRIES -lt {{.MAX_RETRIES}} ]; then exit 7; fi
-                  echo "Please try again"
-                else
-                  break
-                fi
-              done
-            fi
+              if [ $CAN_CONNECT == "6" ]; then
+                printf "\n[Error]: Provided host ($NR_CLI_DB_HOSTNAME) cannot be reached.\nSee https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/postgresql-monitoring-integration#comp-req for more info.\n" >&2
+                if [ ! $TRIES -lt {{.MAX_RETRIES}} ]; then exit 6; fi
+                echo "Please try again"
+              elif [ $CAN_CONNECT == "7" ]; then
+                printf "\n[Error]: Connections to port ($NR_CLI_DB_PORT) are being refused.\nSee https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/postgresql-monitoring-integration#comp-req for more info.\n" >&2
+                if [ ! $TRIES -lt {{.MAX_RETRIES}} ]; then exit 7; fi
+                echo "Please try again"
+              else
+                break
+              fi
+            done
           fi
 
           # if it's generated default user, attempt to create 
