Adding validation for required field and files when SSL/trust are used

diff --git a/recipes/newrelic/infrastructure/ohi/postgres/rhel.yml b/recipes/newrelic/infrastructure/ohi/postgres/rhel.yml
--- a/recipes/newrelic/infrastructure/ohi/postgres/rhel.yml
+++ b/recipes/newrelic/infrastructure/ohi/postgres/rhel.yml
@@ -94,6 +94,23 @@ install:
             echo "[Error]: The provided database name is not accessible with the provided username and password and port. See https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/postgresql-monitoring-integration#comp-req for more info." >> /dev/stderr
             exit 2
           fi
+        - |
+          if [ {{.NR_CLI_SSL}} == true ]; then
+            if [ ! -f {{.NR_CLI_CLIENT_CERT_FILE}} ]; then
+              echo "[Error]: SSL is true but no client certificate file exist at '{{.NR_CLI_CLIENT_CERT_FILE}}''. See https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/postgresql-monitoring-integration#comp-req for more info." >> /dev/stderr
+              exit 11
+            fi
+            if [ ! -f {{.NR_CLI_CERT_KEY}} ]; then
+              echo "[Error]: SSL is true but no PEM key file exist at '{{.NR_CLI_CERT_KEY}}''. See https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/postgresql-monitoring-integration#comp-req for more info." >> /dev/stderr
+              exit 12
+            fi
+          fi
+          if [ {{.NR_CLI_TRUST_SERVER_CERTIFICATE}} == true ]; then
+            if [ ! -f {{.NR_CLI_CERT_AUTH_FILE}} ]; then
+              echo "[Error]: Trust certificate is true but no certificate authority file exist at '{{.NR_CLI_CERT_AUTH_FILE}}''. See https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/postgresql-monitoring-integration#comp-req for more info." >> /dev/stderr
+              exit 13
+            fi
+          fi
 
     setup:
       label: "Installing PostgreSQL integration..."
@@ -110,7 +127,7 @@ install:
           fi
           sudo touch /etc/newrelic-infra/integrations.d/postgresql-config.yml;
         - |
-          if [ {{.NR_CLI_SSL}} == false ]; then
+          if [ {{.NR_CLI_SSL}} == true ]; then
             sudo tee -a /etc/newrelic-infra/integrations.d/postgresql-config.yml > /dev/null <<"EOT"
           integration_name: com.newrelic.postgresql
           instances:
@@ -124,7 +141,11 @@ install:
                 port: {{.NR_CLI_PORT}}
                 collection_list: 'ALL'
                 collect_db_lock_metrics: false
-                enable_ssl: {{.NR_CLI_SSL}}
+                enable_ssl: true
+                trust_server_certificate: {{.NR_CLI_TRUST_SERVER_CERTIFICATE}}
+                ssl_root_cert_location: {{.NR_CLI_CERT_AUTH_FILE}}
+                ssl_cert_location: {{.NR_CLI_CLIENT_CERT_FILE}}
+                ssl_key_location: {{.NR_CLI_CERT_KEY}}
                 timeout: 10
           EOT
           else
@@ -141,11 +162,7 @@ install:
                 port: {{.NR_CLI_PORT}}
                 collection_list: 'ALL'
                 collect_db_lock_metrics: false
-                enable_ssl: {{.NR_CLI_SSL}}
-                trust_server_certificate: {{.NR_CLI_TRUST_SERVER_CERTIFICATE}}
-                ssl_root_cert_location: {{.NR_CLI_CERT_AUTH_FILE}}
-                ssl_cert_location: {{.NR_CLI_CLIENT_CERT_FILE}}
-                ssl_key_location: {{.NR_CLI_CERT_KEY}}
+                enable_ssl: false
                 timeout: 10
           EOT
           fi
