fix(logs): add checks for empty or missing log files input vars for debian

diff --git a/recipes/newrelic/infrastructure/logs/debian-logs.yml b/recipes/newrelic/infrastructure/logs/debian-logs.yml
--- a/recipes/newrelic/infrastructure/logs/debian-logs.yml
+++ b/recipes/newrelic/infrastructure/logs/debian-logs.yml
@@ -99,16 +99,54 @@ install:
           echo -e "verbose: 3\nlog_format: json" | sudo tee -a /etc/newrelic-infra.yml > /dev/null
           sudo sed -i '/^$/d' /etc/newrelic-infra.yml
         - |
-          echo "logs:" | sudo tee /etc/newrelic-infra/logging.d/logging.yml > /dev/null
-          for i in $(echo {{.LOG_FILES}} | sed "s/,/ /g"); do
-            if [ -f $i ]; then
-              NAME=$(basename $i)
-              echo -e "  - name: $NAME\n    file: $i" | sudo tee -a /etc/newrelic-infra/logging.d/logging.yml > /dev/null
-            else
-              echo "ERROR log file $i not found"
+          # Trim whitespace from LOG_FILES input value
+          logFiles=$(echo {{.LOG_FILES}} | sed 's/ *.//')
+          discoveredLogFiles=$(echo {{.DISCOVERED_LOG_FILES}} | sed 's/ *.//')
+
+          logsStringLength=${#logFiles}
+          discoveredLogsStringLength=${#discoveredLogFiles}
+
+          if [ $logsStringLength -eq 0 ] && [ $discoveredLogsStringLength -eq 0 ]; then
+            echo "No log file(s) provided or discovered. Cannot proceed. Exiting installation." > /dev/stderr
+            exit 20
+          fi
+
+          # Keep a count of the valid log files the integration will use.
+          foundLogFilesCount=0
+
+          if [ $logsStringLength -eq 0 ]; then
+            echo "No log file(s) provided by user." > /dev/stderr
+          else
+            echo "logs:" | sudo tee /etc/newrelic-infra/logging.d/logging.yml > /dev/null
+            for i in $(echo {{.LOG_FILES}} | sed "s/,/ /g"); do
+              if [ -f $i ]; then
+                NAME=$(basename $i)
+                echo -e "  - name: $NAME\n    file: $i" | sudo tee -a /etc/newrelic-infra/logging.d/logging.yml > /dev/null
+                echo "SUCCESS log file $i found"
+
+                # Increment found log files count
+                foundLogFilesCount=$((foundLogFilesCount+1))
+              else
+                echo "WARN log file $i not found"
+              fi
+            done
+
+            # If the user provides log files that don't exist and we haven't discovered any log files,
+            # we cannot proceed with the installation.
+            if [ $foundLogFilesCount -eq 0 ]&& [ $discoveredLogsStringLength -eq 0 ]; then
+              echo "ERROR Provided log files do not exist: $logFiles. No log file(s) found or discovered. Cannot proceed. Exiting installation." > /dev/stderr
+              exit 20
             fi
-          done
-        - echo -e "{{.DISCOVERED_LOG_FILES}}" | sudo tee /etc/newrelic-infra/logging.d/discovered.yml > /dev/null
+          fi
+        - |
+          discoveredLogFiles="{{.DISCOVERED_LOG_FILES}}"
+          discoveredLogsStringLength=${#discoveredLogFiles}
+
+          if [ $discoveredLogsStringLength -eq 0 ]; then
+            echo "No log file(s) discovered." > /dev/stderr
+          else
+            echo -e "{{.DISCOVERED_LOG_FILES}}" | sudo tee /etc/newrelic-infra/logging.d/discovered.yml > /dev/null
+          fi
 
     restart:
       cmds:
