Put back debian log file handling. Trigger error when no log files configured

diff --git a/recipes/newrelic/infrastructure/logs/debian-logs.yml b/recipes/newrelic/infrastructure/logs/debian-logs.yml
--- a/recipes/newrelic/infrastructure/logs/debian-logs.yml
+++ b/recipes/newrelic/infrastructure/logs/debian-logs.yml
@@ -117,7 +117,7 @@ install:
 
           if [ $logsStringLength -gt 0 ]; then
             echo "logs:" | sudo tee /etc/newrelic-infra/logging.d/logging.yml > /dev/null
-            for i in $(echo {{.LOG_FILES}}); do
+            for i in $(echo {{.LOG_FILES}} | sed "s/,/ /g"); do
               if [ -f $i ]; then
                 NAME=$(basename $i)
                 echo -e "  - name: $NAME\n    file: $i" | sudo tee -a /etc/newrelic-infra/logging.d/logging.yml > /dev/null
@@ -126,17 +126,17 @@ install:
                 foundLogFilesCount=$((foundLogFilesCount+1))
               fi
             done
-
-            # If the user provides log files that don't exist and we haven't discovered any log files,
-            # we cannot proceed with the installation.
-            if [ $foundLogFilesCount -eq 0 ]; then
-              echo "ERROR Provided log files do not exist: $logFiles. No log file(s) found. Cannot proceed. Exiting installation." >> /dev/stderr
-              exit 16
-            fi
           fi
-        - |
+
           discoveredLogFiles="{{.DISCOVERED_LOG_FILES}}"
           discoveredLogsStringLength=${#discoveredLogFiles}
+
+          # If the user provides log files that don't exist and we haven't discovered any log files,
+          # we cannot proceed with the installation.
+          if [ $foundLogFilesCount -eq 0 ] && [ $discoveredLogsStringLength -eq 0 ]; then
+            echo "ERROR Provided log files do not exist: $logFiles. No log file(s) found or discovered. Cannot proceed. Exiting installation." >> /dev/stderr
+            exit 16
+          fi
           if [ $discoveredLogsStringLength -gt 0 ]; then
             echo -e "{{.DISCOVERED_LOG_FILES}}" | sudo tee /etc/newrelic-infra/logging.d/discovered.yml > /dev/null
           fi
