chore(infra): Allow root installs without sudo (#687)
* chore(infra): asserting sudo/root only and removing sudo package usage in calls

diff --git a/recipes/newrelic/infrastructure/logs/linux-logs.yml b/recipes/newrelic/infrastructure/logs/linux-logs.yml
--- a/recipes/newrelic/infrastructure/logs/linux-logs.yml
+++ b/recipes/newrelic/infrastructure/logs/linux-logs.yml
@@ -51,6 +51,7 @@ validationNrql: "SELECT count(*) from Log where hostname like '{{.HOSTNAME}}%' F
 install:
   version: "3"
   silent: true
+
   tasks:
     default:
       cmds:
@@ -61,6 +62,12 @@ install:
 
     assert_pre_req:
       cmds:
+        - |
+          IS_ROOT_OR_SUDO=$([ ! -z "$SUDO_USER"] || [ $(whoami) = "root" ] && echo "true" || echo "false") # Assert root or sudo user
+          if [ "$IS_ROOT_OR_SUDO" = "false" ]; then
+            echo "This newrelic install must be run under sudo or root" >&2
+            exit 3
+          fi
         - |
           # Map of tool names to the associated error code
           required_tools_and_error_codes="grep:10 sed:11 tee:14 touch:15"
@@ -80,17 +87,17 @@ install:
     init:
       cmds:
         - |
-          sudo mkdir -p "/etc/newrelic-infra/logging.d"
+          mkdir -p "/etc/newrelic-infra/logging.d"
         - |
           if [ -f /etc/newrelic-infra/logging.d/logging.yml ]; then
-            sudo rm /etc/newrelic-infra/logging.d/logging.yml;
+            rm /etc/newrelic-infra/logging.d/logging.yml;
           fi
-          sudo touch /etc/newrelic-infra/logging.d/logging.yml;
+          touch /etc/newrelic-infra/logging.d/logging.yml;
         - |
           if [ -f /etc/newrelic-infra/logging.d/discovered.yml ]; then
-            sudo rm /etc/newrelic-infra/logging.d/discovered.yml;
+            rm /etc/newrelic-infra/logging.d/discovered.yml;
           fi
-          sudo touch /etc/newrelic-infra/logging.d/discovered.yml;
+          touch /etc/newrelic-infra/logging.d/discovered.yml;
 
     setup:
       cmds:
@@ -125,7 +132,7 @@ install:
             done
           fi
 
-          file_exist=$(sudo find /var/lib/docker/containers -name "*.log" 2>1 | wc -l)
+          file_exist=$(find /var/lib/docker/containers -name "*.log" 2>1 | wc -l)
           if [ $file_exist -gt 0 ]; then
             target_log_files+=("/var/lib/docker/containers/*/*.log")
           fi
@@ -137,40 +144,40 @@ install:
 
           target_log_files+=({{.NEW_RELIC_CLI_LOG_FILE_PATH}})
 
-          echo "logs:" | sudo tee /etc/newrelic-infra/logging.d/logging.yml > /dev/null
+          echo "logs:" | tee /etc/newrelic-infra/logging.d/logging.yml > /dev/null
           for log_file in "${target_log_files[@]}"
           do
             if [ "$log_file" == "/var/lib/docker/containers/*/*.log" ]; then
-              echo -e "  - name: containers\n    file: /var/lib/docker/containers/*/*.log" | sudo tee -a /etc/newrelic-infra/logging.d/logging.yml > /dev/null
+              echo -e "  - name: containers\n    file: /var/lib/docker/containers/*/*.log" | tee -a /etc/newrelic-infra/logging.d/logging.yml > /dev/null
             else
               NAME=$(basename $log_file)
-              echo -e "  - name: $NAME" | sudo tee -a /etc/newrelic-infra/logging.d/logging.yml > /dev/null
-              echo -e "    file: $log_file" | sudo tee -a /etc/newrelic-infra/logging.d/logging.yml > /dev/null
+              echo -e "  - name: $NAME" | tee -a /etc/newrelic-infra/logging.d/logging.yml > /dev/null
+              echo -e "    file: $log_file" | tee -a /etc/newrelic-infra/logging.d/logging.yml > /dev/null
               if [[ "$NAME" == "newrelic-cli.log" ]]; then
-                echo -e "    attributes:\n      newrelic-cli: true" | sudo tee -a /etc/newrelic-infra/logging.d/logging.yml > /dev/null
+                echo -e "    attributes:\n      newrelic-cli: true" | tee -a /etc/newrelic-infra/logging.d/logging.yml > /dev/null
               fi
             fi
           done
 
           if [ ${#target_discovered_log_files[@]} -gt 0 ]; then
-            echo "logs:" | sudo tee /etc/newrelic-infra/logging.d/discovered.yml > /dev/null
+            echo "logs:" | tee /etc/newrelic-infra/logging.d/discovered.yml > /dev/null
 
             # index is incremented to facilitate dynamic name values for each discovered log file path
             index=0
             for filePath in $(echo -n $discoveredLogFiles | sed "s/,/ /g"); do
 
-              echo -e "  - name: configured-logs-$index" | sudo tee -a /etc/newrelic-infra/logging.d/discovered.yml > /dev/null
-              echo -e "    file: $filePath" | sudo tee -a /etc/newrelic-infra/logging.d/discovered.yml > /dev/null
+              echo -e "  - name: configured-logs-$index" | tee -a /etc/newrelic-infra/logging.d/discovered.yml > /dev/null
+              echo -e "    file: $filePath" | tee -a /etc/newrelic-infra/logging.d/discovered.yml > /dev/null
 
               if [[ $filePath == *"nginx/error"* ]]; then
-                echo -e "    attributes:\n      logtype: nginx-error" | sudo tee -a /etc/newrelic-infra/logging.d/discovered.yml > /dev/null
+                echo -e "    attributes:\n      logtype: nginx-error" | tee -a /etc/newrelic-infra/logging.d/discovered.yml > /dev/null
               fi
               if [[ $filePath == *"nginx/access"* ]]; then
-                echo -e "    attributes:\n      logtype: nginx" | sudo tee -a /etc/newrelic-infra/logging.d/discovered.yml > /dev/null
+                echo -e "    attributes:\n      logtype: nginx" | tee -a /etc/newrelic-infra/logging.d/discovered.yml > /dev/null
               fi
 
               if [[ $filePath == *"mysql/error"* ]]; then
-                echo -e "    attributes:\n      logtype: mysql-error" | sudo tee -a /etc/newrelic-infra/logging.d/discovered.yml > /dev/null
+                echo -e "    attributes:\n      logtype: mysql-error" | tee -a /etc/newrelic-infra/logging.d/discovered.yml > /dev/null
               fi
 
               index=$((index+1))
@@ -183,9 +190,9 @@ install:
         - |
           sleep 10
         - |
-          echo "Log configuration:" | sudo tee -a {{.NEW_RELIC_CLI_LOG_FILE_PATH}} > /dev/null
-          sudo cat /etc/newrelic-infra/logging.d/logging.yml | sudo tee -a {{.NEW_RELIC_CLI_LOG_FILE_PATH}} > /dev/null
-          echo "Log installation completed" | sudo tee -a {{.NEW_RELIC_CLI_LOG_FILE_PATH}} > /dev/null
+          echo "Log configuration:" | tee -a {{.NEW_RELIC_CLI_LOG_FILE_PATH}} > /dev/null
+          cat /etc/newrelic-infra/logging.d/logging.yml | tee -a {{.NEW_RELIC_CLI_LOG_FILE_PATH}} > /dev/null
+          echo "Log installation completed" | tee -a {{.NEW_RELIC_CLI_LOG_FILE_PATH}} > /dev/null
 
 postInstall:
   info: |2
