chore(infra): allow root installs without sudo for logs integration

diff --git a/recipes/newrelic/infrastructure/logs/linux-logs.yml b/recipes/newrelic/infrastructure/logs/linux-logs.yml
--- a/recipes/newrelic/infrastructure/logs/linux-logs.yml
+++ b/recipes/newrelic/infrastructure/logs/linux-logs.yml
@@ -51,6 +51,11 @@ validationNrql: "SELECT count(*) from Log where hostname like '{{.HOSTNAME}}%' F
 install:
   version: "3"
   silent: true
+
+  variables:
+    SUDO:
+      sh: $([[ -z "$SUDO_USER" && $(whoami) = "root" ]] && echo "" || echo "sudo") # Allows root, non-sudo installs
+
   tasks:
     default:
       cmds:
@@ -80,17 +85,17 @@ install:
     init:
       cmds:
         - |
-          sudo mkdir -p "/etc/newrelic-infra/logging.d"
+          $SUDO mkdir -p "/etc/newrelic-infra/logging.d"
         - |
           if [ -f /etc/newrelic-infra/logging.d/logging.yml ]; then
-            sudo rm /etc/newrelic-infra/logging.d/logging.yml;
+            $SUDO rm /etc/newrelic-infra/logging.d/logging.yml;
           fi
-          sudo touch /etc/newrelic-infra/logging.d/logging.yml;
+          $SUDO touch /etc/newrelic-infra/logging.d/logging.yml;
         - |
           if [ -f /etc/newrelic-infra/logging.d/discovered.yml ]; then
-            sudo rm /etc/newrelic-infra/logging.d/discovered.yml;
+            $SUDO rm /etc/newrelic-infra/logging.d/discovered.yml;
           fi
-          sudo touch /etc/newrelic-infra/logging.d/discovered.yml;
+          $SUDO touch /etc/newrelic-infra/logging.d/discovered.yml;
 
     setup:
       cmds:
@@ -125,7 +130,7 @@ install:
             done
           fi
 
-          file_exist=$(sudo find /var/lib/docker/containers -name "*.log" 2>1 | wc -l)
+          file_exist=$($SUDO find /var/lib/docker/containers -name "*.log" 2>1 | wc -l)
           if [ $file_exist -gt 0 ]; then
             target_log_files+=("/var/lib/docker/containers/*/*.log")
           fi
@@ -137,40 +142,40 @@ install:
 
           target_log_files+=({{.NEW_RELIC_CLI_LOG_FILE_PATH}})
 
-          echo "logs:" | sudo tee /etc/newrelic-infra/logging.d/logging.yml > /dev/null
+          echo "logs:" | $SUDO tee /etc/newrelic-infra/logging.d/logging.yml > /dev/null
           for log_file in "${target_log_files[@]}"
           do
             if [ "$log_file" == "/var/lib/docker/containers/*/*.log" ]; then
-              echo -e "  - name: containers\n    file: /var/lib/docker/containers/*/*.log" | sudo tee -a /etc/newrelic-infra/logging.d/logging.yml > /dev/null
+              echo -e "  - name: containers\n    file: /var/lib/docker/containers/*/*.log" | $SUDO tee -a /etc/newrelic-infra/logging.d/logging.yml > /dev/null
             else
               NAME=$(basename $log_file)
-              echo -e "  - name: $NAME" | sudo tee -a /etc/newrelic-infra/logging.d/logging.yml > /dev/null
-              echo -e "    file: $log_file" | sudo tee -a /etc/newrelic-infra/logging.d/logging.yml > /dev/null
+              echo -e "  - name: $NAME" | $SUDO tee -a /etc/newrelic-infra/logging.d/logging.yml > /dev/null
+              echo -e "    file: $log_file" | $SUDO tee -a /etc/newrelic-infra/logging.d/logging.yml > /dev/null
               if [[ "$NAME" == "newrelic-cli.log" ]]; then
-                echo -e "    attributes:\n      newrelic-cli: true" | sudo tee -a /etc/newrelic-infra/logging.d/logging.yml > /dev/null
+                echo -e "    attributes:\n      newrelic-cli: true" | $SUDO tee -a /etc/newrelic-infra/logging.d/logging.yml > /dev/null
               fi
             fi
           done
 
           if [ ${#target_discovered_log_files[@]} -gt 0 ]; then
-            echo "logs:" | sudo tee /etc/newrelic-infra/logging.d/discovered.yml > /dev/null
+            echo "logs:" | $SUDO tee /etc/newrelic-infra/logging.d/discovered.yml > /dev/null
 
             # index is incremented to facilitate dynamic name values for each discovered log file path
             index=0
             for filePath in $(echo -n $discoveredLogFiles | sed "s/,/ /g"); do
 
-              echo -e "  - name: configured-logs-$index" | sudo tee -a /etc/newrelic-infra/logging.d/discovered.yml > /dev/null
-              echo -e "    file: $filePath" | sudo tee -a /etc/newrelic-infra/logging.d/discovered.yml > /dev/null
+              echo -e "  - name: configured-logs-$index" | $SUDO tee -a /etc/newrelic-infra/logging.d/discovered.yml > /dev/null
+              echo -e "    file: $filePath" | $SUDO tee -a /etc/newrelic-infra/logging.d/discovered.yml > /dev/null
 
               if [[ $filePath == *"nginx/error"* ]]; then
-                echo -e "    attributes:\n      logtype: nginx-error" | sudo tee -a /etc/newrelic-infra/logging.d/discovered.yml > /dev/null
+                echo -e "    attributes:\n      logtype: nginx-error" | $SUDO tee -a /etc/newrelic-infra/logging.d/discovered.yml > /dev/null
               fi
               if [[ $filePath == *"nginx/access"* ]]; then
-                echo -e "    attributes:\n      logtype: nginx" | sudo tee -a /etc/newrelic-infra/logging.d/discovered.yml > /dev/null
+                echo -e "    attributes:\n      logtype: nginx" | $SUDO tee -a /etc/newrelic-infra/logging.d/discovered.yml > /dev/null
               fi
 
               if [[ $filePath == *"mysql/error"* ]]; then
-                echo -e "    attributes:\n      logtype: mysql-error" | sudo tee -a /etc/newrelic-infra/logging.d/discovered.yml > /dev/null
+                echo -e "    attributes:\n      logtype: mysql-error" | $SUDO tee -a /etc/newrelic-infra/logging.d/discovered.yml > /dev/null
               fi
 
               index=$((index+1))
@@ -183,9 +188,9 @@ install:
         - |
           sleep 10
         - |
-          echo "Log configuration:" | sudo tee -a {{.NEW_RELIC_CLI_LOG_FILE_PATH}} > /dev/null
-          sudo cat /etc/newrelic-infra/logging.d/logging.yml | sudo tee -a {{.NEW_RELIC_CLI_LOG_FILE_PATH}} > /dev/null
-          echo "Log installation completed" | sudo tee -a {{.NEW_RELIC_CLI_LOG_FILE_PATH}} > /dev/null
+          echo "Log configuration:" | $SUDO tee -a {{.NEW_RELIC_CLI_LOG_FILE_PATH}} > /dev/null
+          $SUDO cat /etc/newrelic-infra/logging.d/logging.yml | $SUDO tee -a {{.NEW_RELIC_CLI_LOG_FILE_PATH}} > /dev/null
+          echo "Log installation completed" | $SUDO tee -a {{.NEW_RELIC_CLI_LOG_FILE_PATH}} > /dev/null
 
 postInstall:
   info: |2
