Use consistent error code when validation fails

diff --git a/recipes/newrelic/infrastructure/logs/logs.yml b/recipes/newrelic/infrastructure/logs/logs.yml
--- a/recipes/newrelic/infrastructure/logs/logs.yml
+++ b/recipes/newrelic/infrastructure/logs/logs.yml
@@ -30,6 +30,7 @@ install:
       cmds:
         - task: assert_pre_req
         - task: setup
+        - task: restart
 
     assert_pre_req:
       cmds:
@@ -75,6 +76,16 @@ install:
             echo "The infrastructure agent is required to install this integration, we recommend going through our guided install path for this pre-requisite which can be found here:  https://docs.newrelic.com/docs/new-relic-guided-installation-overview" >> /dev/stderr
             exit 1
           fi
+        - |
+          # Trim whitespace from LOG_FILES input value
+          logFiles=$(echo {{.LOG_FILES}} | sed 's/ *.//')
+          discoveredLogFiles=$(echo {{.DISCOVERED_LOG_FILES}} | sed 's/ *.//')
+          logsStringLength=${#logFiles}
+          discoveredLogsStringLength=${#discoveredLogFiles}
+          if [ $logsStringLength -eq 0 ] && [ $discoveredLogsStringLength -eq 0 ]; then
+            echo "No log file(s) provided or discovered. Cannot proceed. Exiting installation." >> /dev/stderr
+            exit 16
+          fi
 
     setup:
       cmds:
@@ -96,52 +107,44 @@ install:
           # Trim whitespace from LOG_FILES input value
           logFiles=$(echo {{.LOG_FILES}} | sed 's/ *.//')
           discoveredLogFiles=$(echo {{.DISCOVERED_LOG_FILES}} | sed 's/ *.//')
-
           logsStringLength=${#logFiles}
           discoveredLogsStringLength=${#discoveredLogFiles}
-
-          if [ $logsStringLength -eq 0 ] && [ $discoveredLogsStringLength -eq 0 ]; then
-            echo "No log file(s) provided or discovered. Cannot proceed. Exiting installation." > /dev/stderr
-            exit 16
-          fi
 
           # Keep a count of the valid log files the integration will use.
           foundLogFilesCount=0
 
-          if [ $logsStringLength -eq 0 ]; then
-            echo "No log file(s) provided by user." > /dev/stderr
-          else
+          if [ $logsStringLength -gt 0 ]; then
             echo "logs:" | sudo tee /etc/newrelic-infra/logging.d/logging.yml > /dev/null
             for i in $(echo {{.LOG_FILES}} | sed "s/,/ /g"); do
               if [ -f $i ]; then
                 NAME=$(basename $i)
-                echo -e "  - name: $NAME\n    file: $i" | sudo tee -a /etc/newrelic-infra/logging.d/logging.yml > /dev/null
-                echo "SUCCESS log file $i found"
+                echo -e "  - name: $NAME\n    file: $i" | sudo tee -a /etc/newrelic-infra/logging.d/logging.yml >> /dev/stderr
 
                 # Increment found log files count
                 foundLogFilesCount=$((foundLogFilesCount+1))
               else
-                echo "WARN log file $i not found"
+                echo "log file $i not found, skipping this file"
               fi
             done
 
             # If the user provides log files that don't exist and we haven't discovered any log files,
             # we cannot proceed with the installation.
             if [ $foundLogFilesCount -eq 0 ]&& [ $discoveredLogsStringLength -eq 0 ]; then
-              echo "ERROR Provided log files do not exist: $logFiles. No log file(s) found or discovered. Cannot proceed. Exiting installation." > /dev/stderr
+              echo "ERROR Provided log files do not exist: $logFiles. No log file(s) found or discovered. Cannot proceed. Exiting installation." >> /dev/stderr
               exit 16
             fi
           fi
         - |
           discoveredLogFiles="{{.DISCOVERED_LOG_FILES}}"
           discoveredLogsStringLength=${#discoveredLogFiles}
-
-          if [ $discoveredLogsStringLength -eq 0 ]; then
-            echo "No log file(s) discovered." > /dev/stderr
-          else
+          if [ $discoveredLogsStringLength -gt 0 ]; then
             echo -e "{{.DISCOVERED_LOG_FILES}}" | sudo tee /etc/newrelic-infra/logging.d/discovered.yml > /dev/null
           fi
-        - sudo systemctl restart newrelic-infra.service
+
+    restart:
+      cmds:
+        - |
+          sudo systemctl restart newrelic-infra.service
 
 postInstall:
   info: |2
