Add a check to make sure input fields are not undefined

diff --git a/recipes/newrelic/infrastructure/logs/logs.yml b/recipes/newrelic/infrastructure/logs/logs.yml
--- a/recipes/newrelic/infrastructure/logs/logs.yml
+++ b/recipes/newrelic/infrastructure/logs/logs.yml
@@ -77,6 +77,16 @@ install:
             exit 1
           fi
         - |
+          # First check on empty inputs
+          logFiles=$(echo {{.LOG_FILES}})
+          discoveredLogFiles=$(echo {{.DISCOVERED_LOG_FILES}})
+          logsStringLength=${#logFiles}
+          discoveredLogsStringLength=${#discoveredLogFiles}
+          if [ $logsStringLength -eq 0 ] && [ $discoveredLogsStringLength -eq 0 ]; then
+            echo "No log file(s) input provided or discovered. Cannot proceed. Exiting installation." >> /dev/stderr
+            exit 16
+          fi
+        - |
           # Trim whitespace from LOG_FILES input value
           logFiles=$(echo {{.LOG_FILES}} | sed 's/ *.//')
           discoveredLogFiles=$(echo {{.DISCOVERED_LOG_FILES}} | sed 's/ *.//')
