Fixed: infra agent install overwrites config files

diff --git a/recipes/newrelic/infrastructure/logs/logs.yml b/recipes/newrelic/infrastructure/logs/logs.yml
--- a/recipes/newrelic/infrastructure/logs/logs.yml
+++ b/recipes/newrelic/infrastructure/logs/logs.yml
@@ -94,61 +94,58 @@ install:
     setup:
       cmds:
         - |
-          sudo mkdir -p "/etc/newrelic-infra/logging.d"
-        - |
-          if [ -f /etc/newrelic-infra/logging.d/logging.yml ]; then
-            sudo rm /etc/newrelic-infra/logging.d/logging.yml;
-          fi
+          if [ ! -f /etc/newrelic-infra/logging.d/logging.yml ]; then
+            sudo mkdir -p "/etc/newrelic-infra/logging.d"
+            sudo touch /etc/newrelic-infra/logging.d/logging.yml
 
-          sudo touch /etc/newrelic-infra/logging.d/logging.yml;
-        - |
-          # Enable infra-agent logs to New Relic
-          sudo sed -i "s,.*verbose:.*,," /etc/newrelic-infra.yml
-          sudo sed -i "s,.*log_format:.*,," /etc/newrelic-infra.yml
-          echo -e "verbose: 3\nlog_format: json" | sudo tee -a /etc/newrelic-infra.yml > /dev/null
-          sudo sed -i '/^$/d' /etc/newrelic-infra.yml
-        - |
-          logFiles=$(echo -n "{{.LOG_FILES}}")
-          logsStringLength=${#logFiles}
+            logFiles=$(echo -n "{{.LOG_FILES}}")
+            logsStringLength=${#logFiles}
 
-          # Keep a count of the valid log files the integration will use.
-          foundLogFilesCount=0
+            # Keep a count of the valid log files the integration will use.
+            foundLogFilesCount=0
 
-          if [ $logsStringLength -gt 0 ]; then
-            echo "logs:" | sudo tee /etc/newrelic-infra/logging.d/logging.yml > /dev/null
-            for i in $(echo -n {{.LOG_FILES}} | sed "s/,/ /g"); do
-              if [ -f $i ]; then
-                NAME=$(basename $i)
-                echo -e "  - name: $NAME\n    file: $i" | sudo tee -a /etc/newrelic-infra/logging.d/logging.yml > /dev/null
+            if [ $logsStringLength -gt 0 ]; then
+              echo "logs:" | sudo tee /etc/newrelic-infra/logging.d/logging.yml > /dev/null
+              for i in $(echo -n {{.LOG_FILES}} | sed "s/,/ /g"); do
+                if [ -f $i ]; then
+                  NAME=$(basename $i)
+                  echo -e "  - name: $NAME\n    file: $i" | sudo tee -a /etc/newrelic-infra/logging.d/logging.yml > /dev/null
 
-                # Increment found log files count
-                foundLogFilesCount=$((foundLogFilesCount+1))
-              fi
-            done
-          fi
+                  # Increment found log files count
+                  foundLogFilesCount=$((foundLogFilesCount+1))
+                fi
+              done
+            fi
 
-          discoveredLogFiles=$(echo -n "{{.NR_DISCOVERED_LOG_FILES | trim}}")
-          discoveredLogsStringLength=${#discoveredLogFiles}
+            discoveredLogFiles=$(echo -n "{{.NR_DISCOVERED_LOG_FILES | trim}}")
+            discoveredLogsStringLength=${#discoveredLogFiles}
 
-          # If the user provides log files that don't exist and we haven't discovered any log files,
-          # we cannot proceed with the installation.
-          if [ $foundLogFilesCount -eq 0 ] && { [ $discoveredLogsStringLength -eq 0 ] || [ "$discoveredLogFiles" = "logs: []" ]; }; then
-            echo "ERROR Provided log files do not exist: $logFiles. No log file(s) found or discovered. Cannot proceed. Exiting installation." >> /dev/stderr
-            exit 16
-          fi
+            # If the user provides log files that don't exist and we haven't discovered any log files,
+            # we cannot proceed with the installation.
+            if [ $foundLogFilesCount -eq 0 ] && { [ $discoveredLogsStringLength -eq 0 ] || [ "$discoveredLogFiles" = "logs: []" ]; }; then
+              echo "ERROR Provided log files do not exist: $logFiles. No log file(s) found or discovered. Cannot proceed. Exiting installation." >> /dev/stderr
+              exit 16
+            fi
 
-          # Disable glob expansion (necessary for discovered logs)
-          set -f
+            # Disable glob expansion (necessary for discovered logs)
+            set -f
 
-          # index is incremented to facilitate dynamic name values for each discovered log file path
-          index=0
-          if [ $discoveredLogsStringLength -gt 0 ]; then
-            echo "logs:" | sudo tee /etc/newrelic-infra/logging.d/discovered.yml > /dev/null
+            # index is incremented to facilitate dynamic name values for each discovered log file path
+            index=0
+            if [ $discoveredLogsStringLength -gt 0 ]; then
+              echo "logs:" | sudo tee /etc/newrelic-infra/logging.d/discovered.yml > /dev/null
 
-            for filePath in $(echo -n $discoveredLogFiles | sed "s/,/ /g"); do
-              echo -e "  - name: configured-logs-$index\n    file: $filePath" | sudo tee -a /etc/newrelic-infra/logging.d/discovered.yml > /dev/null
-              index=$((index+1))
-            done
+              for filePath in $(echo -n $discoveredLogFiles | sed "s/,/ /g"); do
+                echo -e "  - name: configured-logs-$index\n    file: $filePath" | sudo tee -a /etc/newrelic-infra/logging.d/discovered.yml > /dev/null
+                index=$((index+1))
+              done
+            fi
+
+            # Enable infra-agent logs to New Relic
+            sudo sed -i "s,.*verbose:.*,," /etc/newrelic-infra.yml
+            sudo sed -i "s,.*log_format:.*,," /etc/newrelic-infra.yml
+            echo -e "verbose: 3\nlog_format: json" | sudo tee -a /etc/newrelic-infra.yml > /dev/null
+            sudo sed -i '/^$/d' /etc/newrelic-infra.yml
           fi
 
     restart:
