1. Updated debian recipe

diff --git a/recipes/newrelic/infrastructure/ohi/memcached/debian.yml b/recipes/newrelic/infrastructure/ohi/memcached/debian.yml
--- a/recipes/newrelic/infrastructure/ohi/memcached/debian.yml
+++ b/recipes/newrelic/infrastructure/ohi/memcached/debian.yml
@@ -37,21 +37,6 @@ logMatch:
 # installed is successfully sending data to New Relic
 validationNrql: "SELECT count(*) from MemcachedSample where hostname like '{{.HOSTNAME}}%' FACET entityGuid SINCE 10 minutes ago"
 
-# Prompts for input from the user. These variables then become
-# available to go-task in the form of {{.VAR_NAME}}
-inputVars:
-  - name: "NR_CLI_DB_USERNAME"
-    prompt: "SASL Username (if applicable)"
-  - name: "NR_CLI_DB_PASSWORD"
-    prompt: "SASL Password (if applicable)"
-    secret: true
-  - name: "NR_CLI_HOST"
-    prompt: "Memcached Hostname (default: localhost)"
-    default: "localhost"
-  - name: "NR_CLI_PORT"
-    prompt: "Memcached Port (default: 11211)"
-    default: 11211
-
 preInstall:
   info: |2
       To capture data from the Memcached integration, you'll first need to meet these prerequisites:
@@ -81,6 +66,7 @@ install:
     setup:
       label: "Installing Memcached integration..."
       cmds:
+        - sudo apt-get install libmemcached-tools -y
         - |
           sudo mkdir -p "/etc/newrelic-infra/integrations.d"
         - |
@@ -93,37 +79,101 @@ install:
             sudo rm /etc/newrelic-infra/integrations.d/memcached-config.yml;
           fi
         - |
-          if [ -z {{.NR_CLI_DB_USERNAME}} ] && [ -z {{.NR_CLI_DB_PASSWORD}} ]; then
-            sudo tee /etc/newrelic-infra/integrations.d/memcached-config.yml > /dev/null <<"EOT"
+          
+          # try get values from env
+          NR_CLI_DB_USERNAME={{.NR_CLI_DB_USERNAME}}
+          NR_CLI_DB_PASSWORD={{.NR_CLI_DB_PASSWORD}}
+          NR_CLI_HOST={{.NR_CLI_HOST}}
+          NR_CLI_PORT={{.NR_CLI_PORT}}
+
+          # Set default values for variables
+          NR_CLI_HOST=${NR_CLI_HOST:-localhost}
+          NR_CLI_PORT=${NR_CLI_PORT:-11211}
+          MAX_RETRIES=3
+          TRIES=0 
+          CAN_CONNECT=$(curl $NR_CLI_HOST:$NR_CLI_PORT 2>&1 1>/dev/null -s -S | awk -F'[()]' '{print $2}')
+
+          while [[ $TRIES -lt $MAX_RETRIES  && ( $CAN_CONNECT == "6" || $CAN_CONNECT == "7" ) ]]; do
+            printf "\Memcached Hostname (default: localhost): "
+            read -r NR_CLI_HOST
+            NR_CLI_HOST=${NR_CLI_HOST:-localhost}
+            printf "Memcached Port (default: 11211): "
+            read -r NR_CLI_DB_PORT
+            NR_CLI_DB_PORT=${NR_CLI_DB_PORT:-11211}
+            ((TRIES++))
+
+            CAN_CONNECT=$(curl $NR_CLI_HOST:$NR_CLI_PORT 2>&1 1>/dev/null -s -S | awk -F'[()]' '{print $2}')
+
+            if [ $CAN_CONNECT == "6" ]; then
+              printf "\n[Error]: Provided host ($NR_CLI_DB_HOSTNAME) cannot be reached.\nSee https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/postgresql-monitoring-integration#comp-req for more info.\n" >&2
+              if [ ! $TRIES -lt $MAX_RETRIES ]; then exit 6; fi
+              echo "Please try again"
+            elif [ $CAN_CONNECT == "7" ]; then
+              printf "\n[Error]: Connections to port ($NR_CLI_DB_PORT) are being refused.\nSee https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/postgresql-monitoring-integration#comp-req for more info.\n" >&2
+              if [ ! $TRIES -lt $MAX_RETRIES ]; then exit 7; fi
+              echo "Please try again"
+            else
+              break
+            fi
+          done
+          
+          CAN_CONNECT=""
+          if [ -z "$NR_CLI_DB_USERNAME" ] && [ -z "$NR_CLI_DB_PASSWORD" ]; then
+            CAN_CONNECT=$(memcstat --servers="$NR_CLI_HOST" | grep uptime | wc -l)
+          else
+            CAN_CONNECT=$(memcstat --servers="$NR_CLI_HOST" --username="$NR_CLI_DB_USERNAME" --password="$NR_CLI_DB_PASSWORD" | grep uptime | wc -l)
+          fi
+
+          TRIES=0 
+          while [[ $TRIES -lt $MAX_RETRIES &&  $CAN_CONNECT -eq 0 ]]; do
+            printf "Memcached Username: "
+            read -r NR_CLI_DB_USERNAME
+            printf "Memcached Password: "
+            stty -echo
+            read -r NR_CLI_DB_PASSWORD
+            stty echo
+            ((TRIES++))
+
+            CAN_CONNECT=$(memcstat --servers="$NR_CLI_HOST" --username="$NR_CLI_DB_USERNAME" --password="$NR_CLI_DB_PASSWORD" | grep uptime | wc -l)
+            
+            if [ $CAN_CONNECT -eq 0 ] ; then
+              printf "\n[Error]: Memcached server is not accessible with the provided username, password.\nSee https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/postgresql-monitoring-integration#comp-req for more info.\n" >&2
+              if [ ! $TRIES -lt $MAX_RETRIES ]; then exit 2; else continue; fi
+              echo "Please try again"
+            fi
+          done
+
+          if [ -z $NR_CLI_DB_USERNAME ] && [ -z $NR_CLI_DB_PASSWORD ]; then
+            sudo tee /etc/newrelic-infra/integrations.d/memcached-config.yml > /dev/null <<EOT
           integrations:
             - name: nri-memcached
               env:
                 # Hostname of the memcached instance.
                 # Defaults to localhost.
-                HOST: {{.NR_CLI_HOST}}
+                HOST: $NR_CLI_HOST
                 # Port memcached is running on.
                 # Defaults to 11211
-                PORT: {{.NR_CLI_PORT}}
+                PORT: $NR_CLI_PORT
               inventory_source: config/memcached
               interval: 15
           EOT
           else
-            sudo tee /etc/newrelic-infra/integrations.d/memcached-config.yml > /dev/null <<"EOT"
+            sudo tee /etc/newrelic-infra/integrations.d/memcached-config.yml > /dev/null <<EOT
           integrations:
             - name: nri-memcached
               env:
                 # Hostname of the memcached instance.
                 # Defaults to localhost.
-                HOST: {{.NR_CLI_HOST}}
+                HOST: $NR_CLI_HOST
                 # Port memcached is running on.
                 # Defaults to 11211
-                PORT: {{.NR_CLI_PORT}}
+                PORT: $NR_CLI_PORT
                 # Memcached SASL username. Only required if
                 # authentication is enabled.
-                USERNAME: {{.NR_CLI_DB_USERNAME}}
+                USERNAME: $NR_CLI_DB_USERNAME
                 # Memcached SASL password. Only required if
                 # authentication is enabled.
-                PASSWORD: {{.NR_CLI_DB_PASSWORD}}
+                PASSWORD: $NR_CLI_DB_PASSWORD
               inventory_source: config/memcached
               interval: 15
           EOT
