1. Remove prompt for host 2. Update messages for fail to connect

diff --git a/recipes/newrelic/infrastructure/ohi/memcached/rhel.yml b/recipes/newrelic/infrastructure/ohi/memcached/rhel.yml
--- a/recipes/newrelic/infrastructure/ohi/memcached/rhel.yml
+++ b/recipes/newrelic/infrastructure/ohi/memcached/rhel.yml
@@ -91,13 +91,7 @@ install:
           TRIES=0 
           CAN_CONNECT=$(curl $NR_CLI_HOST:$NR_CLI_PORT 2>&1 1>/dev/null -s -S | awk -F'[()]' '{print $2}')
           
-          while [[ $TRIES -lt $MAX_RETRIES  && ( $CAN_CONNECT == "6" || $CAN_CONNECT == "7" ) ]]; do
-            if [ $CAN_CONNECT == "6" ]; then 
-              printf "\nMemcached Hostname (default: localhost): "
-              read -r NR_CLI_HOST
-              NR_CLI_HOST=${NR_CLI_HOST:-localhost}
-            fi
-
+          while [[ $TRIES -lt $MAX_RETRIES && $CAN_CONNECT == "7" ]]; do
             printf "\nMemcached Port (default: 11211): "
             read -r NR_CLI_DB_PORT
             NR_CLI_DB_PORT=${NR_CLI_DB_PORT:-11211}
@@ -105,16 +99,10 @@ install:
 
             CAN_CONNECT=$(curl $NR_CLI_HOST:$NR_CLI_PORT 2>&1 1>/dev/null -s -S | awk -F'[()]' '{print $2}')
 
-            if [ $CAN_CONNECT == "6" ]; then
-              printf "\n[Error]: Provided host ($NR_CLI_DB_HOSTNAME) cannot be reached.\nSee https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/postgresql-monitoring-integration#comp-req for more info.\n" >&2
-              if [ ! $TRIES -lt $MAX_RETRIES ]; then exit 6; fi
-              echo "Please try again"
-            elif [ $CAN_CONNECT == "7" ]; then
-              printf "\n[Error]: Connections to port ($NR_CLI_DB_PORT) are being refused.\nSee https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/postgresql-monitoring-integration#comp-req for more info.\n" >&2
+            if [ $CAN_CONNECT == "7" ]; then
+              printf "\n\nFail to connect to Memcached on localhost using port $NR_CLI_DB_PORT.  Please enter the port number for your Memcached instance.\n" >&2
               if [ ! $TRIES -lt $MAX_RETRIES ]; then exit 7; fi
               echo "Please try again"
-            else
-              break
             fi
           done
           
@@ -138,7 +126,7 @@ install:
             CAN_CONNECT=$(memstat --servers="$NR_CLI_HOST" --username="$NR_CLI_DB_USERNAME" --password="$NR_CLI_DB_PASSWORD" | grep uptime | wc -l)
             
             if [ $CAN_CONNECT -eq 0 ] ; then
-              printf "\n[Error]: Memcached server is not accessible with the provided username, password.\nSee https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/postgresql-monitoring-integration#comp-req for more info.\n" >&2
+              printf "\n\nFail to connect to Memcached using provided username and password.  Please enter the username and password for your Memcached instance.\n" >&2
               if [ ! $TRIES -lt $MAX_RETRIES ]; then exit 2; else continue; fi
               echo "Please try again"
             fi
