Message and prompt updated

diff --git a/recipes/newrelic/infrastructure/ohi/memcached/rhel.yml b/recipes/newrelic/infrastructure/ohi/memcached/rhel.yml
--- a/recipes/newrelic/infrastructure/ohi/memcached/rhel.yml
+++ b/recipes/newrelic/infrastructure/ohi/memcached/rhel.yml
@@ -92,7 +92,7 @@ install:
           CAN_CONNECT=$(curl $NR_CLI_HOST:$NR_CLI_PORT 2>&1 1>/dev/null -s -S | awk -F'[()]' '{print $2}')
           
           while [[ $TRIES -lt $MAX_RETRIES && $CAN_CONNECT == "7" ]]; do
-            printf "\nMemcached Port (default: 11211): "
+            printf "\nPlease enter the port number for your Memcached instance: "
             read -r NR_CLI_DB_PORT
             NR_CLI_DB_PORT=${NR_CLI_DB_PORT:-11211}
             ((TRIES++))
@@ -100,7 +100,7 @@ install:
             CAN_CONNECT=$(curl $NR_CLI_HOST:$NR_CLI_PORT 2>&1 1>/dev/null -s -S | awk -F'[()]' '{print $2}')
 
             if [ $CAN_CONNECT == "7" ]; then
-              printf "\n\nPlease enter the port number for your Memcached instance.\n" >&2
+              printf "\n\nUnable to connect your Memcached instance using provided port.\n" >&2
               if [ ! $TRIES -lt $MAX_RETRIES ]; then exit 7; fi
               echo "Please try again"
             fi
@@ -115,9 +115,9 @@ install:
 
           TRIES=0 
           while [[ $TRIES -lt $MAX_RETRIES && $CAN_CONNECT -eq 0 ]]; do
-            printf "\nMemcached Username: "
+            printf "\nPlease enter the username for your Memcached instance: "
             read -r NR_CLI_DB_USERNAME
-            printf "Memcached Password: "
+            printf "Please enter the password for your Memcached instance: "
             stty -echo
             read -r NR_CLI_DB_PASSWORD
             stty echo
@@ -126,7 +126,7 @@ install:
             CAN_CONNECT=$(memstat --servers="$NR_CLI_HOST" --username="$NR_CLI_DB_USERNAME" --password="$NR_CLI_DB_PASSWORD" | grep uptime | wc -l)
             
             if [ $CAN_CONNECT -eq 0 ] ; then
-              printf "\n\nPlease enter the username and password for your Memcached instance.\n" >&2
+              printf "\n\nUnable to connect your Memcached instance using provided username and password.\n" >&2
               if [ ! $TRIES -lt $MAX_RETRIES ]; then exit 2; else continue; fi
               echo "Please try again"
             fi
