Redis install (#603)
* [VIRTUOSO-1713] - Improve install for Redis Linux
1. Remove prompt for hostname, always default localhost
2. Will try to install with default, only prompting when default fails
3. Fix issue where the condition for checking correct password is failing
  - Using grep instead of checking for exact string "PONG"

diff --git a/recipes/newrelic/infrastructure/ohi/redis/rhel.yml b/recipes/newrelic/infrastructure/ohi/redis/rhel.yml
--- a/recipes/newrelic/infrastructure/ohi/redis/rhel.yml
+++ b/recipes/newrelic/infrastructure/ohi/redis/rhel.yml
@@ -87,24 +87,23 @@ install:
           # Set Defaults
           NR_CLI_HOSTNAME=${NR_CLI_HOSTNAME:-'localhost'}
           NR_CLI_PORT=${NR_CLI_PORT:-'6379'}
+          CLI_RESPONSE=""
 
           if [[ "$NEW_RELIC_ASSUME_YES" != "true" ]]; then
             while [ $TRIES -lt {{.MAX_RETRIES}} ]; do
-              printf "\nRedis Hostname (default: localhost): "
-              read -r NR_CLI_HOSTNAME
-              NR_CLI_HOSTNAME=${NR_CLI_HOSTNAME:-localhost}
-              printf "Redis Port (default: 6379): "
-              read -r NR_CLI_PORT
-              NR_CLI_PORT=${NR_CLI_PORT:-6379}
-              ((TRIES++))
 
               CLI_RESPONSE=$(redis-cli -h "$NR_CLI_HOSTNAME" -p "$NR_CLI_PORT" -a "$NR_CLI_PASSWORD" PING 2>&1)
               if [ $(echo $CLI_RESPONSE | grep "Could not connect" | wc -l) -gt 0 ] ; then
-                printf "\n[Error]: Could not connect to Redis server. Check hostname and port.\nSee https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/redis-monitoring-integration/#config for more info.\n" >&2
+                printf "\n[Error]: Could not connect to Redis server with default port 6379. Please provide a port number.\nSee https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/redis-monitoring-integration/#config for more info.\n" >&2
+                printf "Redis Port (default: 6379): "
+                read -r NR_CLI_PORT
+                NR_CLI_PORT=${NR_CLI_PORT:-6379}
+                ((TRIES++))
                 if [ ! $TRIES -lt {{.MAX_RETRIES}} ]; then exit 2; else continue; fi
                 echo "Please try again"
               fi
-              if [ $(echo $CLI_RESPONSE | grep "Authentication required" | wc -l) -gt 0 ] ; then
+
+              if [ $(echo $CLI_RESPONSE | grep "NOAUTH" | wc -l) -gt 0 ] ; then
                 TRIES=0
                 while [ $TRIES -lt {{.MAX_RETRIES}} ]; do
                   printf "Redis Password: "
@@ -115,7 +114,7 @@ install:
                   ((TRIES++))
 
                   CLI_RESPONSE=$(redis-cli -h "$NR_CLI_HOSTNAME" -p "$NR_CLI_PORT" -a "$NR_CLI_PASSWORD" PING 2>&1)
-                  if [ "$CLI_RESPONSE" != "PONG" ] ; then
+                  if [ $(echo $CLI_RESPONSE | grep "PONG" | wc -l) -eq 0 ] ; then
                     printf "\n[Error]: Could not authenticate on Redis server. Check password.\nSee https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/redis-monitoring-integration/#config for more info.\n" >&2
                     if [ ! $TRIES -lt {{.MAX_RETRIES}} ]; then exit 3; else continue; fi
                     echo "Please try again"
@@ -123,8 +122,6 @@ install:
                   break
                 done
               fi
-              printf "\nKeyspace Metrics (expected: single-line JSON format): "
-              read -r NR_CLI_KEYS
               break
             done
           fi
@@ -183,7 +180,7 @@ install:
                 INVENTORY: true
                 HOSTNAME: $NR_CLI_HOSTNAME
                 PORT: $NR_CLI_PORT
-                PASSWORD: $NR_CLI_PASSWORD
+                PASSWORD: $NR_CLI_PASSWORd
 
                 # New users should leave this property as 'true', to identify the
                 # monitored entities as 'remote'. Setting this property to 'false' (the
