feat(rabbitmq-rhel): add conditional to check if rabbitmq plugin is installed

diff --git a/recipes/newrelic/infrastructure/ohi/rabbitmq/rhel.yml b/recipes/newrelic/infrastructure/ohi/rabbitmq/rhel.yml
--- a/recipes/newrelic/infrastructure/ohi/rabbitmq/rhel.yml
+++ b/recipes/newrelic/infrastructure/ohi/rabbitmq/rhel.yml
@@ -70,6 +70,7 @@ install:
     default:
       cmds:
         - taks: assert_pre_req
+        - tasks: rabbitmq_plugin_installed
         - task: setup
 
     assert_pre_req:
@@ -78,6 +79,15 @@ install:
           SERVICE_EXIST=$(sudo systemctl status newrelic-infra.service | grep "Active" | wc -l)
           if [ $SERVICE_EXIST -eq 0 ]; then
             echo "The newrelic-infra agent service is NOT installed on the host, but is required to install this integration." >> /dev/stderr
+            exit 1
+          fi
+
+    rabbitmq_plugin_installed:
+      cmds:
+        - |
+          PLUGIN_EXIST=$(sudo cat /etc/rabbitmq/enabled_plugins | grep "rabbitmq_management" | wc -l)
+          if [ $PLUGIN_EXIST -eq 0 ]; then
+            echo "The RabbitMQ Management plugin is NOT installed on the host, but is required to install this integration." >> /dev/stderr
             exit 1
           fi
 
