ohi(mongo): both no-auth, auth-scram working/tested

diff --git a/recipes/newrelic/infrastructure/ohi/mongodb/debian.yml b/recipes/newrelic/infrastructure/ohi/mongodb/debian.yml
--- a/recipes/newrelic/infrastructure/ohi/mongodb/debian.yml
+++ b/recipes/newrelic/infrastructure/ohi/mongodb/debian.yml
@@ -72,7 +72,8 @@ install:
     NR_CLI_DB_HOSTNAME: '{{.NR_CLI_DB_HOSTNAME | default "localhost"}}'
     NR_CLI_DB_PORT: '{{.NR_CLI_DB_PORT | default "27017"}}'
     NR_CLI_DB_USERNAME: '{{.NR_CLI_DB_USERNAME | default "newrelic"}}'
-    NR_CLI_DB_PASSWORD: '{{.NR_CLI_DB_PASSWORD | default "$(echo -n $(date +%s | sha256sum | base64 | head -c 16))"}}oO0'
+    NR_CLI_DB_PASSWORD:
+      sh: if [ -z {{.NR_CLI_DB_PASSWORD}} ]; then echo -n $(date +%s | sha256sum | base64 | head -c 16)oO0; else echo {{.NR_CLI_DB_PASSWORD}}; fi
     NR_CLI_DB_CLUSTERNAME: '{{.NR_CLI_DB_CLUSTERNAME | default "mongocluster"}}'
     NR_CLI_DB_AUTH: '{{.NR_CLI_DB_AUTH | default "admin"}}'
     NR_CLI_SSL: '{{.NR_CLI_SSL}}'
@@ -84,7 +85,10 @@ install:
       cmds:
         - task: assert_pre_req
         - task: setup_no_auth
-        - task: setup_auth
+        - task: setup_auth_scram
+          vars:
+            MAX_RETRIES: 3
+        - task: setup_auth_ssl
           vars:
             MAX_RETRIES: 3
         - task: restart
@@ -158,14 +162,19 @@ install:
           EOT
 
           # Check open mongodb and check/configure requirements
-          CAN_CONNECT=$(mongo --host {{.NR_CLI_DB_HOSTNAME}} --port {{.NR_CLI_DB_PORT}} --eval 'db.adminCommand( { listDatabases: 1 } )' | grep -e '\"ok\" : 1' | wc -l)
+          CAN_CONNECT=$(mongo --host {{.NR_CLI_DB_HOSTNAME}} --port {{.NR_CLI_DB_PORT}} --eval 'db.adminCommand( { listDatabases: 1 } )' \
+                      | grep -e '\"ok\" : 1' | wc -l)
+
           if [ $CAN_CONNECT -gt 0 ]; then
-            MONGO_MONITORING_ROLE_EXISTS=$(mongo {{.NR_CLI_DB_AUTH}} --host {{.NR_CLI_DB_HOSTNAME}} --port {{.NR_CLI_DB_PORT}} --eval 'db.getRole("listCollections")' | grep -e '\"role\" : \"listCollections\"' | wc -l)
+            MONGO_MONITORING_ROLE_EXISTS=$(mongo {{.NR_CLI_DB_AUTH}} --host {{.NR_CLI_DB_HOSTNAME}} --port {{.NR_CLI_DB_PORT}} \
+                                        --eval 'db.getRole("listCollections")' | grep -e '\"role\" : \"listCollections\"' | wc -l)
 
             if [ $MONGO_MONITORING_ROLE_EXISTS -gt 0 ]; then
               echo "Required role already present"
             else
-              SETUP_ROLE=$(mongo {{.NR_CLI_DB_AUTH}} --host {{.NR_CLI_DB_HOSTNAME}} --port {{.NR_CLI_DB_PORT}} < /tmp/mongo-role.js | grep -e '\"role\" : \"listCollections\"' | wc -l)
+              SETUP_ROLE=$(mongo {{.NR_CLI_DB_AUTH}} --host {{.NR_CLI_DB_HOSTNAME}} --port {{.NR_CLI_DB_PORT}} < /tmp/mongo-role.js \
+                         | grep -e '\"role\" : \"listCollections\"' | wc -l)
+
               if [ $SETUP_ROLE -gt 0 ]; then
                 echo "Required role created"
               else
@@ -174,17 +183,25 @@ install:
               fi
             fi
 
-            MONGO_MONITORING_USER_EXISTS=$(mongo {{.NR_CLI_DB_AUTH}} --host {{.NR_CLI_DB_HOSTNAME}} --port {{.NR_CLI_DB_PORT}} --eval "db.getUser('{{.NR_CLI_DB_USERNAME}}')" | grep -e "\"_id\" : \"{{.NR_CLI_DB_AUTH}}\.{{.NR_CLI_DB_USERNAME}}\"" | wc -l)
+            MONGO_MONITORING_USER_EXISTS=$(mongo {{.NR_CLI_DB_AUTH}} --host {{.NR_CLI_DB_HOSTNAME}} --port {{.NR_CLI_DB_PORT}} \
+                                        --eval "db.getUser('{{.NR_CLI_DB_USERNAME}}')" \
+                                        | grep -e "\"_id\" : \"{{.NR_CLI_DB_AUTH}}\.{{.NR_CLI_DB_USERNAME}}\"" | wc -l)
 
             if [ $MONGO_MONITORING_USER_EXISTS -gt 0 ]; then
               echo "Required user already present, attempting to update its password"
-              USER_UPDATE_FAILED=$(mongo {{.NR_CLI_DB_AUTH}} --host {{.NR_CLI_DB_HOSTNAME}} --port {{.NR_CLI_DB_PORT}} --eval "db.changeUserPassword('{{.NR_CLI_DB_USERNAME}}', '{{.NR_CLI_DB_PASSWORD}}')" | grep -i "Error: Updating user failed" | wc -l)
+
+              USER_UPDATE_FAILED=$(mongo {{.NR_CLI_DB_AUTH}} --host {{.NR_CLI_DB_HOSTNAME}} --port {{.NR_CLI_DB_PORT}} \
+                                --eval "db.changeUserPassword('{{.NR_CLI_DB_USERNAME}}', '{{.NR_CLI_DB_PASSWORD}}')" \
+                                | grep -i "Error: Updating user failed" | wc -l)
+
               if [ $USER_UPDATE_FAILED -gt 0 ]; then
                 echo "Could not update password for {{.NR_CLI_DB_USERNAME}}"
                 exit 3
               fi
             else 
-              SETUP_MONGO_MONITORING_USER=$(mongo {{.NR_CLI_DB_AUTH}} --host {{.NR_CLI_DB_HOSTNAME}} --port {{.NR_CLI_DB_PORT}} < /tmp/mongo-user.js | grep -i "Successfully added user" | wc -l)
+              SETUP_MONGO_MONITORING_USER=$(mongo {{.NR_CLI_DB_AUTH}} --host {{.NR_CLI_DB_HOSTNAME}} --port {{.NR_CLI_DB_PORT}} < /tmp/mongo-user.js \
+                                         | grep -i "Successfully added user" | wc -l)
+
               if [ $SETUP_MONGO_MONITORING_USER -gt 0 ]; then
                 echo "Required user created"
               else
@@ -197,7 +214,7 @@ install:
             touch /tmp/mongo_ok
           fi
 
-    setup_auth:
+    setup_auth_scram:
       cmds:
         - |
           # If previous no-auth setup task was successful, skip this one
@@ -205,31 +222,148 @@ install:
             exit 0
           fi
 
-          #TODO check if assume yes, if assume yes, just exit here with error
           if [ ${NEW_RELIC_ASSUME_YES,,} == "true" ]; then
             exit 3
           fi
 
-          CAN_CONNECT=$(mongo --host {{.NR_CLI_DB_HOSTNAME}} --port {{.NR_CLI_DB_PORT}} --eval 'db.adminCommand( { listDatabases: 1 } )' | grep -e '\"ok\" : 1' | wc -l)
-          if [[ $CAN_CONNECT -eq 0 ]]; then
-            read -r -p "Is SSL/TLS used to connect to Mongo Database? (Y/N) " USING_SSL
+          echo ""
+          read -r -p "Using regular SCRAM Username/Password authentication to connect to MongoDB? (Y/N) " USING_SCRAM
+
+          if [[ ${USING_SCRAM,,} =~ "^(y|ye|yes)$" ]]; then
+            # SCRAM Use Case
+            TRIES=0
+            echo -e "\nPlease provide MongoDB SCRAM credentials"
+            while [ $TRIES -lt {{.MAX_RETRIES}} ]; do
+              ((TRIES++))
+              read -r -p "MongoDB Username? " MONGO_USERNAME
+              stty -echo  # To securely read password; 'read -s $VAR' showed 'illegal -s option' when tried
+              read -r -p "MongoDB Password? " MONGO_PASSWORD
+              stty echo
+              echo ""
+              read -r -p "MongoDB Port? (Default 27017) " MONGO_PORT
+              MONGO_PORT=${MONGO_PORT:-27017}
+
+              CAN_CONNECT=$(mongo --host {{.NR_CLI_DB_HOSTNAME}} --port {{.NR_CLI_DB_PORT}} --username $MONGO_USERNAME \
+                          --password $MONGO_PASSWORD --authenticationDatabase {{.NR_CLI_DB_AUTH}} --eval "db.adminCommand( { listDatabases: 1 } )" \
+                          | grep -e '\"ok\" : 1' | wc -l)
+
+              if [ $CAN_CONNECT -eq 0 ]; then
+                echo "Could not connect to {{.NR_CLI_DB_HOSTNAME}}:{{.NR_CLI_DB_PORT}}, db {{.NR_CLI_DB_AUTH}}"
+              else
+                echo "Connected!"           
+                break
+              fi
+            done
+
+            if [ $TRIES -eq {{.MAX_RETRIES}} ]; then
+              echo "Max connection attempts reached"
+              exit 3
+            else
+              MONGO_MONITORING_ROLE_EXISTS=$(mongo {{.NR_CLI_DB_AUTH}} --host {{.NR_CLI_DB_HOSTNAME}} --port $MONG_PORT --username $MONGO_USERNAME \
+                                           --password $MONGO_PASSWORD --authenticationDatabase {{.NR_CLI_DB_AUTH}} --eval 'db.getRole("listCollections")' \
+                                           | grep -e '\"role\" : "listCollections"' | wc -l)
+              
+              if [ $MONGO_MONITORING_ROLE_EXISTS -gt 0 ]; then
+                echo "Required role already present"
+              else
+                SETUP_ROLE=$(mongo {{.NR_CLI_DB_AUTH}} --host {{.NR_CLI_DB_HOSTNAME}} --port $MONGO_PORT --username $MONGO_USERNAME \
+                           --password $MONGO_PASSWORD --authenticationDatabase {{.NR_CLI_DB_AUTH}} < /tmp/mongo-role.js \
+                           | grep -e '\"role\" : \"listCollections\"' | wc -l)
+
+                if [ $SETUP_ROLE -gt 0 ]; then
+                  echo "Required role created"
+                fi
+              fi
+
+              MONGO_MONITORING_USER_EXISTS=$(mongo {{.NR_CLI_DB_AUTH}} --host {{.NR_CLI_DB_HOSTNAME}} --port $MONGO_PORT --username $MONGO_USERNAME \
+                                           --password $MONGO_PASSWORD --authenticationDatabase {{.NR_CLI_DB_AUTH}} --eval "db.getUser('{{.NR_CLI_DB_USERNAME}}')" \
+                                           | grep -e "\"_id\" : \"{{.NR_CLI_DB_AUTH}}\.{{.NR_CLI_DB_USERNAME}}\"" | wc -l)
+
+              if [ $MONGO_MONITORING_USER_EXISTS -gt 0 ]; then
+                echo "Required user already present, attempting to update its password"
+
+                USER_UPDATE_FAILED=$(mongo {{.NR_CLI_DB_AUTH}} --host {{.NR_CLI_DB_HOSTNAME}} --port $MONGO_PORT --username $MONGO_USERNAME \
+                                   --password $MONGO_PASSWORD --authenticationDatabase {{.NR_CLI_DB_AUTH}} \
+                                   --eval "db.changeUserPassword('{{.NR_CLI_DB_USERNAME}}', '{{.NR_CLI_DB_PASSWORD}}')" \
+                                   | grep -i "Error: Updating user failed" | wc -l)
+
+                if [ $USER_UPDATE_FAILED -gt 0 ]; then
+                  echo "Could not update password for {{.NR_CLI_DB_USERNAME}}"
+                  exit 3
+                fi
+              else 
+                SETUP_MONGO_MONITORING_USER=$(mongo {{.NR_CLI_DB_AUTH}} --host {{.NR_CLI_DB_HOSTNAME}} --port $MONGO_PORT --username $MONGO_USERNAME \
+                                           --password $MONGO_PASSWORD --authenticationDatabase {{.NR_CLI_DB_AUTH}} < /tmp/mongo-user.js \
+                                           | grep -i "Successfully added user" | wc -l)
+
+                if [ $SETUP_MONGO_MONITORING_USER -gt 0 ]; then
+                  echo "Required user created"
+                else
+                  echo "Could not create required role/user on {{.NR_CLI_DB_HOSTNAME}}:$MONGO_PORT, db {{.NR_CLI_DB_AUTH}}"
+                  exit 3
+                fi
+              fi
+
+              tee /etc/newrelic-infra/integrations.d/mongodb-config.yml > /dev/null <<-EOT
+              integrations:
+                - name: nri-mongodb
+                  env:
+                    # The mongo server to connect to
+                    HOST: {{.NR_CLI_DB_HOSTNAME}}
+                    # The port mongo is running on
+                    PORT: $MONGO_PORT
+                    # The username of the user created to monitor the cluster.
+                    # This user should exist on the cluster as a whole as well
+                    # as on each of the individual mongodb instances.
+                    USERNAME: {{.NR_CLI_DB_USERNAME}}
+                    # The password for the monitoring user
+                    PASSWORD: {{.NR_CLI_DB_PASSWORD}}
+                    # The database on which the monitoring user is stored
+                    AUTH_SOURCE: {{.NR_CLI_DB_AUTH}}
+                    # A user-defined cluster name. Required.
+                    CLUSTER_NAME: {{.NR_CLI_DB_CLUSTERNAME}}
+                    # Connect using SSL
+                    SSL: false
+                  inventory_source: config/mongodb
+                  interval: 15
+          EOT
+              # Let other tasks know this one was successful
+              touch /tmp/mongo_scram_ok
+            fi
           fi
 
+    setup_auth_ssl:
+      cmds:
+        - |
+          # If previous no-auth setup task was successful, skip this one
+          if [ -f /tmp/mongo_ok ] || [ -f /tmp/mongo_scram_ok ]; then
+            exit 0
+          fi
+
+          if [ ${NEW_RELIC_ASSUME_YES,,} == "true" ]; then
+            exit 3
+          fi
+
+          read -r -p "Using SSL/TLS authentication to connect to MongoDB? (Y/N) " USING_SSL
+
           if [[ ${USING_SSL,,} =~ "^(y|ye|yes)$" ]]; then
-            # Use SSL Case
+            # SSL/TLS Use Case
             TRIES=0
             while [ $TRIES -lt {{.MAX_RETRIES}} ]; do
               ((TRIES++))
-              read -r -p "Certificate Hostname? (Default localhost) " HOST
+              read -r -p "Localhost's Certificate Hostname? " HOST
               HOST=${HOST:-localhost}
               read -r -p "Port? (Default 27017) " PORT 
               PORT=${PORT:-27017}
               read -r -p "SSL CA Certificate Path? " CA_CERT_PATH
               read -r -p "Client Certificate PEM file Path? " CLIENT_CERT_PATH
+
               if [[ -z $HOST || -z $NR_CLI_DB_PORT || -z $CA_CERT_PATH || -z $CLIENT_CERT_PATH ]]; then
                 echo "Please provided all the required certificate information"
               else
-                CAN_CONNECT=$(mongo --ssl --host $HOST:$PORT --sslPEMKeyFile $CLIENT_CERT_PATH --sslCAFile $CA_CERT_PATH --eval "db.runCommand({ connectionStatus: 1 })" | grep -e '\"ok\" : 1' | wc -l)
+                CAN_CONNECT=$(mongo --ssl --host $HOST:$PORT --sslPEMKeyFile $CLIENT_CERT_PATH --sslCAFile $CA_CERT_PATH \
+                           --eval "db.runCommand({ connectionStatus: 1 })" | grep -e '\"ok\" : 1' | wc -l)
+
                 if [ $CAN_CONNECT -gt 0 ]; then
                   echo "Connected!"
                   break
@@ -242,16 +376,13 @@ install:
               exit 3
             else
               # SSL-based integration setup: Re-write mongodb-config.yml to include SSL-related fields
-              # mkdir -p "/etc/newrelic-infra/integrations.d"
-              # apt-get -o Acquire::Check-Valid-Until=false update -yq
-              # apt-get install nri-mongodb -y
               tee /etc/newrelic-infra/integrations.d/mongodb-config.yml > /dev/null <<-EOT
               integrations:
                 - name: nri-mongodb
                   env:
-                    # The mongos to connect to
+                    # The mongo server to connect to
                     HOST: $HOST
-                    # The port the mongos is running on
+                    # The port mongo is running on
                     PORT: $PORT
                     # The database on which the monitoring user is stored
                     AUTH_SOURCE: {{.NR_CLI_DB_AUTH}}
@@ -266,87 +397,6 @@ install:
                   inventory_source: config/mongodb
                   interval: 15
           EOT
-            fi
-            exit 0
-          else
-            # SCRAM Use Case
-            TRIES=0
-            echo "Please provide MongoDB SCRAM credentials"
-            while [ $TRIES -lt {{.MAX_RETRIES}} ]; do
-              ((TRIES++))
-              read -r -p "MongoDB Username? " MONGO_USERNAME
-              stty -echo  # To securely read password; 'read -s $VAR' showed 'illegal -s option' when tried
-              read -r -p "MongoDB Password? " MONGO_PASSWORD
-              stty echo
-              read -r -p "MongoDB Port? (Default 27017) " MONGO_PORT
-              MONGO_PORT=${MONGO_PORT:-27017}
-
-              CAN_CONNECT=$(mongo --host {{.NR_CLI_DB_HOSTNAME}} --port {{.NR_CLI_DB_PORT}} --username $MONGO_USERNAME --password $MONGO_PASSWORD --authenticationDatabase {{.NR_CLI_DB_AUTH}} --eval "db.adminCommand( { listDatabases: 1 } )" | grep -e '\"ok\" : 1' | wc -l)
-
-              if [ $CAN_CONNECT -eq 0 ]; then
-                echo "Could not connect to $NR_CLI_DB_HOSTNAME$:$NR_CLI_DB_PORT$, db $NR_CLI_DB_AUTH"
-              else
-                echo "Connected!"           
-                break
-              fi
-            done
-
-            if [ $TRIES -eq {{.MAX_RETRIES}} ]; then
-              echo "Max connection attempts reached"
-              exit 3
-
-              MONGO_MONITORING_ROLE_EXISTS=$(mongo {{.NR_CLI_DB_AUTH}} --host {{.NR_CLI_DB_HOSTNAME}} --port $MONG_PORT --username $MONGO_USERNAME --password $MONGO_PASSWORD --authenticationDatabase {{.NR_CLI_DB_AUTH}} --eval 'db.getRole("listCollections")' | grep -e '\"role\" : "litsCollections"' | wc -l)
-              if [ $MONGO_MONITORING_ROLE_EXISTS -gt 0 ]; then
-                echo "Required role already present"
-              else
-                SETUP_ROLE=$(mongo {{.NR_CLI_DB_AUTH}} --host {{.NR_CLI_DB_HOSTNAME}} --port $MONGO_PORT --username $MONGO_USERNAME --password $MONGO_PASSWORD --authenticationDatabase {{.NR_CLI_DB_AUTH}} < /tmp/mongo-role.js | grep -e '\"role\" : \"listCollections\"' | wc -l)
-                if [ $SETUP_ROLE -gt 0 ]; then
-                  echo "Required role created"
-                fi
-              fi
-              MONGO_MONITORING_USER_EXISTS=$(mongo {{.NR_CLI_DB_AUTH}} --host {{.NR_CLI_DB_HOSTNAME}} --port $MONGO_PORT --username $MONGO_USERNAME --password $MONGO_PASSWORD --authenticationDatabase {{.NR_CLI_DB_AUTH}} --eval "db.getUser('$MONGO_MONITORING_USERNAME')" | grep -e "\"_id\" : \"$NR_CLI_DB_AUTH\.$MONGO_MONITORING_USERNAME\"" | wc -l)
-              if [ $MONGO_MONITORING_USER_EXISTS -gt 0 ]; then
-                echo "Required user already present, attempting to update its password"
-                USER_UPDATE_FAILED=$(mongo {{.NR_CLI_DB_AUTH}} --host {{.NR_CLI_DB_HOSTNAME}} --port $MONGO_PORT --username $MONGO_USERNAME --password $MONGO_PASSWORD --authenticationDatabase {{.NR_CLI_DB_AUTH}} --eval "db.changeUserPassword('$MONGO_MONITORING_USERNAME', '$MONGO_MONITORING_PASSWORD')" | grep -i "Error: Updating user failed" | wc -l)
-                if [ $USER_UPDATE_FAILED -gt 0 ]; then
-                  echo "Could not update password for $MONGO_MONITORING_USERNAME"
-                  exit 3
-                fi
-              else 
-                SETUP_MONGO_MONITORING_USER=$(mongo {{.NR_CLI_DB_AUTH}} --host {{.NR_CLI_DB_HOSTNAME}} --port $MONGO_PORT --username $MONGO_USERNAME --password $MONGO_PASSWORD --authenticationDatabase {{.NR_CLI_DB_AUTH}} < /tmp/mongo-user.js | grep -i "Successfully added user" | wc -l)
-                if [ $SETUP_MONGO_MONITORING_USER -gt 0 ]; then
-                  echo "Required user created"
-                else
-                  echo "Could not create required role/user on $NR_CLI_DB_HOSTNAME:$NR_CLI_DB_PORT, db $NR_CLI_DB_AUTH"
-                  exit 3
-                fi
-              fi
-
-              tee /etc/newrelic-infra/integrations.d/mongodb-config.yml > /dev/null <<-EOT
-              integrations:
-                - name: nri-mongodb
-                  env:
-                    # The mongos to connect to
-                    HOST: {{.NR_CLI_DB_HOSTNAME}}
-                    # The port the mongos is running on
-                    PORT: $MONGO_PORT
-                    # The username of the user created to monitor the cluster.
-                    # This user should exist on the cluster as a whole as well
-                    # as on each of the individual mongods.
-                    USERNAME: {{.NR_CLI_DB_USERNAME}}
-                    # The password for the monitoring user
-                    PASSWORD: {{.NR_CLI_DB_PASSWORD}}
-                    # The database on which the monitoring user is stored
-                    AUTH_SOURCE: {{.NR_CLI_DB_AUTH}}
-                    # A user-defined cluster name. Required.
-                    CLUSTER_NAME: {{.NR_CLI_DB_CLUSTERNAME}}
-                    # Connect using SSL
-                    SSL: false
-                  inventory_source: config/mongodb
-                  interval: 15
-          EOT
-
-              exit 0
             fi
           fi
 
@@ -377,8 +427,11 @@ install:
           if [ -f /tmp/mongo-user.js ]; then
             rm -f /tmp/mongo-user.js 
           fi
-          if [ -f /tmp/mongo-ok ]; then
-            rm -f /tmp/mongo-ok
+          if [ -f /tmp/mongo_ok ]; then
+            rm -f /tmp/mongo_ok
+          fi
+          if [ -f /tmp/mongo_scram_ok ]; then
+            rm -f /tmp/mongo_scram_ok
           fi
 
 postInstall:
