chore/install: Re-enable mongo ecipe

diff --git a/recipes/newrelic/infrastructure/ohi/mongodb/debian.yml b/recipes/newrelic/infrastructure/ohi/mongodb/debian.yml
--- a/recipes/newrelic/infrastructure/ohi/mongodb/debian.yml
+++ b/recipes/newrelic/infrastructure/ohi/mongodb/debian.yml
@@ -49,9 +49,6 @@ preInstall:
       listCollections roles to the new user.
       Note: username, password, and similar user-specific values must be replaced.
 
-      In the MongoDB shell run the following command
-      > rs.initiate()
-
       Switch to the admin database
       > use admin
 
@@ -62,11 +59,12 @@ preInstall:
       > db.createUser({ user: "username", pwd: "password", roles: [ "clusterMonitor", "listCollections" ]})
 
   requireAtDiscovery: |
-    MONGODB_EXISTS=$(mongo --eval 'db.runCommand({ connectionStatus: 1 })' | grep "ok" | wc -l)
-    if [ $MONGODB_EXISTS -eq 0 ]; then
-      exit 132
-    fi
-    exit 1
+    # TODO: Fix this. If Auth or SSL enable, this required discovery step fails
+    # MONGODB_EXISTS=$(mongo --eval 'db.runCommand({ connectionStatus: 1 })' | grep -e '\"ok\" : 1' | wc -l)
+    # if [ $MONGODB_EXISTS -eq 0 ]; then
+    #   exit 132
+    # fi
+    exit 0
 
 install:
   version: "3"
@@ -74,12 +72,331 @@ install:
   tasks:
     default:
       cmds:
-        - task: setup
+        - task: assert_pre_req
+        - task: mongo_pre_req
+        - task: assert_input
+          vars:
+            MAX_RETRIES: 3
+        - task: restart
+        - task: cleanup
 
-    setup:
+    assert_pre_req:
       cmds:
         - |
-          exit 131
+          IS_INFRA_INSTALLED=$(sudo ps aux | grep newrelic-infra-service | grep -v grep | wc -l)
+          if [ $IS_INFRA_INSTALLED -eq 0 ] ; then
+            echo "The infrastructure agent is required to install this integration, we recommend going through our guided install path for this pre-requisite which can be found here:  https://docs.newrelic.com/docs/full-stack-observability/observe-everything/get-started/new-relic-guided-install-overview" >&2
+            exit 1
+          fi
+        - |
+          # Map of tool names to the associated error code
+          REQUIRED_TOOLS_AND_ERROR_CODES="date:41 sha256sum:42 base64:43 head:44"
+
+          for tuple in $REQUIRED_TOOLS_AND_ERROR_CODES; do
+            tool=$(echo ${tuple} |cut -d':' -f1)
+            code=$(echo ${tuple} |cut -d':' -f2)
+
+            IS_TOOL_INSTALLED=$(which ${tool} | wc -l)
+            if [ "$IS_TOOL_INSTALLED" -eq 0 ]
+            then
+              echo -e "{{.RED}}This installation requires '${tool}' to be installed.{{.NOCOLOR}}" >> /dev/stderr
+              exit ${code}
+            fi
+          done
+        - | 
+          IS_MONGO_SHELL_INSTALLED=$(which mongo | wc -l)
+          if [ $IS_MONGO_SHELL_INSTALLED -eq 0 ]; then
+            echo "Mongo shell is required to run the newrelic install" # TODO: Prompt to install if not present?
+            exit 46
+          fi
+
+    mongo_pre_req:
+      cmds:
+        - |
+          if [ -f /tmp/mongo-role.js ]; then
+            rm -f /tmp/mongo-role.js 
+          fi
+          tee -a /tmp/mongo-role.js > /dev/null <<-"EOT"
+            use admin
+            db.createRole({ role: "listCollections", privileges: [{ resource: { db: "", collection: "" }, actions: [ "listCollections" ] }], roles: [] })
+          EOT
+          if [ -f /tmp/mongo-user.js ]; then
+            rm -f /tmp/mongo-user.js 
+          fi
+          tee -a /tmp/mongo-user.js > /dev/null <<-"EOT"
+            use admin
+            db.createUser({ user: "MONGO_MONITORING_USERNAME", pwd: "MONGO_MONITORING_PASSWORD", roles: [ "clusterMonitor", "listCollections" ] })
+          EOT
+      
+    assert_input:
+      cmds:
+        - |
+          NEW_RELIC_ASSUME_YES="{{.NEW_RELIC_ASSUME_YES}}" # TODO: Implement NEW_RELIC_ASSUME_YES
+          NR_CLI_DB_HOSTNAME="{{.NR_CLI_DB_HOSTNAME}}"
+          NR_CLI_DB_PORT="{{.NR_CLI_DB_PORT}}"
+          NR_CLI_DB_USERNAME="{{.NR_CLI_DB_USERNAME}}"
+          NR_CLI_DB_PASSWORD="{{.NR_CLI_DB_PASSWORD}}"
+          NR_CLI_DB_CLUSTERNAME="{{.NR_CLI_DB_CLUSTERNAME}}"
+          NR_CLI_DB_AUTH="{{.NR_CLI_DB_AUTH}}"
+          NR_CLI_SSL="{{.NR_CLI_SSL}}"
+          NR_CLI_CLIENT_CERT_FILE="{{.NR_CLI_CLIENT_CERT_FILE}}"
+          NR_CLI_CERT_AUTH_FILE="{{.NR_CLI_CERT_AUTH_FILE}}"
+
+          # MongoDB defaults
+          NR_CLI_DB_HOSTNAME=${NR_CLI_DB_HOSTNAME:-localhost}
+          NR_CLI_DB_PORT=${NR_CLI_DB_PORT:-27017}
+          NR_CLI_DB_CLUSTERNAME=${NR_CLI_DB_CLUSTERNAME:-mongocluster}
+          NR_CLI_DB_AUTH=${NR_CLI_DB_AUTH:-admin}
+
+          MONGO_MONITORING_USERNAME=newrelic
+          MONGO_MONITORING_PASSWORD=$(echo -n $(date +%s | sha256sum | base64 | head -c 16); echo "oO0$")
+
+          sed -i -e "s/MONGO_MONITORING_USERNAME/$MONGO_MONITORING_USERNAME/g" \
+                 -e "s/MONGO_MONITORING_PASSWORD/$MONGO_MONITORING_PASSWORD/g" \
+                 /tmp/mongo-user.js
+
+          # Setup integration's config file for mongodb without/with SCRAM authentication enabled cases
+          mkdir -p "/etc/newrelic-infra/integrations.d"
+          apt-get -o Acquire::Check-Valid-Until=false update -yq
+          apt-get install nri-mongodb -y
+          if [ -f /etc/newrelic-infra/integrations.d/mongodb-config.yml ]; then
+            rm /etc/newrelic-infra/integrations.d/mongodb-config.yml;
+          fi
+          tee /etc/newrelic-infra/integrations.d/mongodb-config.yml > /dev/null <<-"EOT"
+          integrations:
+            - name: nri-mongodb
+              env:
+                # The mongos to connect to
+                HOST: NR_CLI_DB_HOSTNAME
+                # The port the mongos is running on
+                PORT: NR_CLI_DB_PORT
+                # The username of the user created to monitor the cluster.
+                # This user should exist on the cluster as a whole as well
+                # as on each of the individual mongods.
+                USERNAME: MONGO_MONITORING_USERNAME
+                # The password for the monitoring user
+                PASSWORD: MONGO_MONITORING_PASSWORD
+                # The database on which the monitoring user is stored
+                AUTH_SOURCE: NR_CLI_DB_AUTH
+                # A user-defined cluster name. Required.
+                CLUSTER_NAME: NR_CLI_DB_CLUSTERNAME
+                # Connect using SSL
+                SSL: false
+              inventory_source: config/mongodb
+              interval: 15
+          EOT
+
+          # Check open mongodb and configure requirements
+          CAN_CONNECT=$(mongo --host $NR_CLI_DB_HOSTNAME --port $NR_CLI_DB_PORT --eval 'db.adminCommand( { listDatabases: 1 } )' | grep -e '\"ok\" : 1' | wc -l)
+          if [ $CAN_CONNECT -gt 0 ]; then
+            # No Auth Use Case
+            MONGO_MONITORING_ROLE_EXISTS=$(mongo $NR_CLI_DB_AUTH --host $NR_CLI_DB_HOSTNAME --port $NR_CLI_DB_PORT --eval 'db.getRole("listCollections")' | grep -e '\"role\" : "litsCollections"' | wc -l)
+            if [ $MONGO_MONITORING_ROLE_EXISTS -gt 0 ]; then
+              echo "Required role already present"
+            else
+              SETUP_ROLE=$(mongo $NR_CLI_DB_AUTH --host $NR_CLI_DB_HOSTNAME --port $NR_CLI_DB_PORT < /tmp/mongo-role.js | grep -e '\"role\" : \"listCollections\"' | wc -l)
+              if [ $SETUP_ROLE -gt 0 ]; then
+                echo "Required role created"
+              fi
+            fi
+            MONGO_MONITORING_USER_EXISTS=$(mongo $NR_CLI_DB_AUTH --host $NR_CLI_DB_HOSTNAME --port $NR_CLI_DB_PORT --eval "db.getUser('$MONGO_MONITORING_USERNAME')" | grep -e "\"_id\" : \"$NR_CLI_DB_AUTH\.$MONGO_MONITORING_USERNAME\"" | wc -l)
+            if [ $MONGO_MONITORING_USER_EXISTS -gt 0 ]; then
+              echo "Required user already present, attempting to update its password"
+              USER_UPDATE_FAILED=$(mongo $NR_CLI_DB_AUTH --host $NR_CLI_DB_HOSTNAME --port $NR_CLI_DB_PORT --eval "db.changeUserPassword('$MONGO_MONITORING_USERNAME', '$MONGO_MONITORING_PASSWORD')" | grep -i "Error: Updating user failed" | wc -l)
+              if [ $USER_UPDATE_FAILED -gt 0 ]; then
+                echo "Could not update password for $MONGO_MONITORING_USERNAME"
+                exit 3
+              fi
+            else 
+              SETUP_MONGO_MONITORING_USER=$(mongo $NR_CLI_DB_AUTH --host $NR_CLI_DB_HOSTNAME --port $NR_CLI_DB_PORT < /tmp/mongo-user.js | grep -i "Successfully added user" | wc -l)
+              if [ $SETUP_MONGO_MONITORING_USER -gt 0 ]; then
+                echo "Required user created"
+              else
+                echo "Could not create required role/user on $NR_CLI_DB_HOSTNAME:$NR_CLI_DB_PORT, db $NR_CLI_DB_AUTH"
+                exit 3
+              fi
+            fi
+
+            sed -i -e "s/NR_CLI_DB_HOSTNAME/$NR_CLI_DB_HOSTNAME/g" \
+                   -e "s/NR_CLI_DB_PORT/$NR_CLI_DB_PORT/g" \
+                   -e "s/MONGO_MONITORING_USERNAME/$MONGO_MONITORING_USERNAME/g" \
+                   -e "s/MONGO_MONITORING_PASSWORD/$MONGO_MONITORING_PASSWORD/g" \
+                   -e "s/NR_CLI_DB_AUTH/$NR_CLI_DB_AUTH/g" \
+                   -e "s/NR_CLI_DB_CLUSTERNAME/$NR_CLI_DB_CLUSTERNAME/g" \
+                   /etc/newrelic-infra/integrations.d/mongodb-config.yml
+            exit 0
+          fi
+
+          if [[ $CAN_CONNECT -eq 0 ]]; then
+            read -r -p "Using SSL/TLS? (Y/N) " USING_SSL
+          fi
+
+          if [[ ${USING_SSL,,} =~ "^(y|ye|yes)$" ]]; then
+            # Use SSL Case
+            TRIES=0
+            while [ $TRIES -lt {{.MAX_RETRIES}} ]; do
+              ((TRIES++))
+              read -r -p "Hostname? (Matching Certificate) " HOST
+              read -r -p "Port? (Default 27017) " PORT 
+              NR_CLI_DB_PORT=${PORT:-27017}
+              read -r -p "SSL CA Certificate Path? " CA_CERT_PATH
+              read -r -p "Client Certificate Path? " CLIENT_CERT_PATH
+              if [[ -z $HOST || -z $NR_CLI_DB_PORT || -z $CA_CERT_PATH || -z $CLIENT_CERT_PATH ]]; then
+                echo "Need all values"
+              else
+                CAN_CONNECT=$(mongo --ssl --host $HOST:$NR_CLI_DB_PORT --sslPEMKeyFile $CLIENT_CERT_PATH --sslCAFile $CA_CERT_PATH --eval "db.runCommand({ connectionStatus: 1 })" | grep -e '\"ok\" : 1' | wc -l)
+                if [ $CAN_CONNECT -gt 0 ]; then
+                  echo "Connected!"
+                  break
+                fi
+              fi
+            done
+
+            if [ $TRIES -eq {{.MAX_RETRIES}} ]; then
+              echo "Max connection attempts reached"
+              exit 3
+            else
+              # SSL-based integration setup: Re-write mongodb-config.yml to include SSL-related fields
+              # mkdir -p "/etc/newrelic-infra/integrations.d"
+              # apt-get -o Acquire::Check-Valid-Until=false update -yq
+              # apt-get install nri-mongodb -y
+              if [ -f /etc/newrelic-infra/integrations.d/mongodb-config.yml ]; then
+                rm /etc/newrelic-infra/integrations.d/mongodb-config.yml;
+              fi
+              tee /etc/newrelic-infra/integrations.d/mongodb-config.yml > /dev/null <<-"EOT"
+              integrations:
+                - name: nri-mongodb
+                  env:
+                    # The mongos to connect to
+                    HOST: NR_CLI_DB_HOSTNAME
+                    # The port the mongos is running on
+                    PORT: NR_CLI_DB_PORT
+                    # The username of the user created to monitor the cluster.
+                    # This user should exist on the cluster as a whole as well
+                    # as on each of the individual mongods.
+                    USERNAME: MONGO_MONITORING_USERNAME
+                    # The password for the monitoring user
+                    PASSWORD: MONGO_MONITORING_PASSWORD
+                    # The database on which the monitoring user is stored
+                    AUTH_SOURCE: NR_CLI_DB_AUTH
+                    # A user-defined cluster name. Required.
+                    CLUSTER_NAME: NR_CLI_DB_CLUSTERNAME
+                    # Connect using SSL
+                    SSL: true
+                    # Path to the CA certs file
+                    SSL_CA_CERTS: NR_CLI_CERT_AUTH_FILE
+                    # Client Certificate to present to the server (optional)
+                    PEM_KEY_FILE: NR_CLI_CLIENT_CERT_FILE
+                  inventory_source: config/mongodb
+                  interval: 15
+          EOT
+              sed -i -e "s/NR_CLI_DB_HOSTNAME/$HOST/g" \
+                    -e "s/NR_CLI_DB_PORT/$NR_CLI_DB_PORT/g" \
+                    -e "s/MONGO_MONITORING_USERNAME//g" \
+                    -e "s/MONGO_MONITORING_PASSWORD//g" \
+                    -e "s/NR_CLI_DB_AUTH/$NR_CLI_DB_AUTH/g" \
+                    -e "s/NR_CLI_DB_CLUSTERNAME/$NR_CLI_DB_CLUSTERNAME/g" \
+                    -e "s|NR_CLI_CERT_AUTH_FILE|$CA_CERT_PATH|g" \
+                    -e "s|NR_CLI_CLIENT_CERT_FILE|$CLIENT_CERT_PATH|g" \
+                    /etc/newrelic-infra/integrations.d/mongodb-config.yml
+            fi
+            exit 0
+          else
+            # SCRAM Use Case
+            TRIES=0
+            echo "Please, provide MongoDB SCRAM credentials"
+            while [ $TRIES -lt {{.MAX_RETRIES}} ]; do
+              ((TRIES++))
+              read -r -p "MongoDB Username? " MONGO_USERNAME
+              stty -echo  # To securely read password; 'read -s $VAR' showed 'illegal -s option' when tried
+              read -r -p "MongoDB Password? " MONGO_PASSWORD
+              stty echo
+              read -r -p "MongoDB Port? (Default 27017) " MONGO_PORT
+              NR_CLI_DB_PORT=${MONGO_PORT:-27017}
+
+              CAN_CONNECT=$(mongo --host $NR_CLI_DB_HOSTNAME --port $NR_CLI_DB_PORT --username $MONGO_USERNAME --password $MONGO_PASSWORD --authenticationDatabase $NR_CLI_DB_AUTH --eval "db.adminCommand( { listDatabases: 1 } )" | grep -e '\"ok\" : 1' | wc -l)
+
+              if [ $CAN_CONNECT -eq 0 ]; then
+                echo "Could not connect to $NR_CLI_DB_HOSTNAME$:$NR_CLI_DB_PORT$, db $NR_CLI_DB_AUTH"
+              else
+                echo "Connected!"           
+                break
+              fi
+            done
+
+            if [ $TRIES -eq {{.MAX_RETRIES}} ]; then
+              echo "Max connection attempts reached"
+              exit 3
+            else
+              sed -i -e "s/MONGO_MONITORING_USERNAME/$MONGO_MONITORING_USERNAME/g" \
+                     -e "s/MONGO_MONITORING_PASSWORD/$MONGO_MONITORING_PASSWORD/g" \
+                     /tmp/mongo-user.js
+
+              MONGO_MONITORING_ROLE_EXISTS=$(mongo $NR_CLI_DB_AUTH --host $NR_CLI_DB_HOSTNAME --port $NR_CLI_DB_PORT --username $MONGO_USERNAME --password $MONGO_PASSWORD --authenticationDatabase $NR_CLI_DB_AUTH --eval 'db.getRole("listCollections")' | grep -e '\"role\" : "litsCollections"' | wc -l)
+              if [ $MONGO_MONITORING_ROLE_EXISTS -gt 0 ]; then
+                echo "Required role already present"
+              else
+                SETUP_ROLE=$(mongo $NR_CLI_DB_AUTH --host $NR_CLI_DB_HOSTNAME --port $NR_CLI_DB_PORT --username $MONGO_USERNAME --password $MONGO_PASSWORD --authenticationDatabase $NR_CLI_DB_AUTH < /tmp/mongo-role.js | grep -e '\"role\" : \"listCollections\"' | wc -l)
+                if [ $SETUP_ROLE -gt 0 ]; then
+                  echo "Required role created"
+                fi
+              fi
+              MONGO_MONITORING_USER_EXISTS=$(mongo $NR_CLI_DB_AUTH --host $NR_CLI_DB_HOSTNAME --port $NR_CLI_DB_PORT --username $MONGO_USERNAME --password $MONGO_PASSWORD --authenticationDatabase $NR_CLI_DB_AUTH --eval "db.getUser('$MONGO_MONITORING_USERNAME')" | grep -e "\"_id\" : \"$NR_CLI_DB_AUTH\.$MONGO_MONITORING_USERNAME\"" | wc -l)
+              if [ $MONGO_MONITORING_USER_EXISTS -gt 0 ]; then
+                echo "Required user already present, attempting to update its password"
+                USER_UPDATE_FAILED=$(mongo $NR_CLI_DB_AUTH --host $NR_CLI_DB_HOSTNAME --port $NR_CLI_DB_PORT --username $MONGO_USERNAME --password $MONGO_PASSWORD --authenticationDatabase $NR_CLI_DB_AUTH --eval "db.changeUserPassword('$MONGO_MONITORING_USERNAME', '$MONGO_MONITORING_PASSWORD')" | grep -i "Error: Updating user failed" | wc -l)
+                if [ $USER_UPDATE_FAILED -gt 0 ]; then
+                  echo "Could not update password for $MONGO_MONITORING_USERNAME"
+                  exit 3
+                fi
+              else 
+                SETUP_MONGO_MONITORING_USER=$(mongo $NR_CLI_DB_AUTH --host $NR_CLI_DB_HOSTNAME --port $NR_CLI_DB_PORT --username $MONGO_USERNAME --password $MONGO_PASSWORD --authenticationDatabase $NR_CLI_DB_AUTH < /tmp/mongo-user.js | grep -i "Successfully added user" | wc -l)
+                if [ $SETUP_MONGO_MONITORING_USER -gt 0 ]; then
+                  echo "Required user created"
+                else
+                  echo "Could not create required role/user on $NR_CLI_DB_HOSTNAME:$NR_CLI_DB_PORT, db $NR_CLI_DB_AUTH"
+                  exit 3
+                fi
+              fi
+
+              sed -i -e "s/NR_CLI_DB_HOSTNAME/$NR_CLI_DB_HOSTNAME/g" \
+                     -e "s/NR_CLI_DB_PORT/$NR_CLI_DB_PORT/g" \
+                     -e "s/MONGO_MONITORING_USERNAME/$MONGO_MONITORING_USERNAME/g" \
+                     -e "s/MONGO_MONITORING_PASSWORD/$MONGO_MONITORING_PASSWORD/g" \
+                     -e "s/NR_CLI_DB_AUTH/$NR_CLI_DB_AUTH/g" \
+                     -e "s/NR_CLI_DB_CLUSTERNAME/$NR_CLI_DB_CLUSTERNAME/g" \
+                     /etc/newrelic-infra/integrations.d/mongodb-config.yml
+              exit 0
+            fi
+          fi
+
+    restart:
+      cmds:
+        - |
+          if [ {{.IS_SYSTEMCTL}} -gt 0 ]; then
+            sudo systemctl restart newrelic-infra
+          else 
+            if [ {{.IS_INITCTL}} -gt 0 ]; then
+              sudo initctl restart newrelic-infra
+            else
+              sudo /etc/init.d/newrelic-infra restart
+            fi
+          fi
+      vars:
+        IS_SYSTEMCTL:
+          sh: command -v systemctl | wc -l
+        IS_INITCTL:
+          sh: command -v initctl | wc -l
+
+    cleanup:
+      cmds:
+        - |
+          if [ -f /tmp/mongo-role.js ]; then
+            rm -f /tmp/mongo-role.js 
+          fi
+          if [ -f /tmp/mongo-user.js ]; then
+            rm -f /tmp/mongo-user.js 
+          fi
 
 postInstall:
   info: |2
