Make input vars consistent for mongodb. Remove not needed parameters and validate SSL input vars when required.

diff --git a/recipes/newrelic/infrastructure/ohi/mongodb/rhel.yml b/recipes/newrelic/infrastructure/ohi/mongodb/rhel.yml
--- a/recipes/newrelic/infrastructure/ohi/mongodb/rhel.yml
+++ b/recipes/newrelic/infrastructure/ohi/mongodb/rhel.yml
@@ -48,15 +48,12 @@ inputVars:
     prompt: "MongoDB Port (default: 27017)"
     default: 27017
   - name: "NR_CLI_SSL"
-    prompt: "Use SSL to connect? (y/n)"
-  - name: "NR_CLI_CERT_AUTH_FILE"
-    prompt: "Certificate Authority file (if applicable)"
-  - name: "NR_CLI_SKIP_SSL_VERIFY"
-    prompt: "Verify certificate? (y/n)"
+    prompt: "Use SSL to connect? (false/true)"
+    default: false
   - name: "NR_CLI_CLIENT_CERT_FILE"
     prompt: "Client Certificate file (if applicable)"
-  - name: "NR_CLI_CERT_PASSPHRASE"
-    prompt: "Passphrase to decrypt the PEM key file (if applicable)"
+  - name: "NR_CLI_CERT_AUTH_FILE"
+    prompt: "Certificate Authority file (if applicable)"
 
 preInstall:
   info: |2
@@ -106,6 +103,17 @@ install:
             echo "Cannot estabilish connection to mongodb, please verify that it's installed correctly."
             exit 2
           fi
+        - |
+          if [ {{.NR_CLI_SSL}} == true ]; then
+            if [ ! -f {{.NR_CLI_CLIENT_CERT_FILE}} ]; then
+              echo "[Error]: SSL is true but no client certificate file exist at '{{.NR_CLI_CLIENT_CERT_FILE}}'. See https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/mongodb-monitoring-integration#comp-req for more info." >> /dev/stderr
+              exit 11
+            fi
+            if [ ! -f {{.NR_CLI_CERT_AUTH_FILE}} ]; then
+              echo "[Error]: Trust certificate is true but no certificate authority file exist at '{{.NR_CLI_CERT_AUTH_FILE}}'. See https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/mongodb-monitoring-integration#comp-req for more info." >> /dev/stderr
+              exit 13
+            fi
+          fi
 
     setup:
       label: "Installing MongoDB integration..."
@@ -121,66 +129,65 @@ install:
             sudo rm /etc/newrelic-infra/integrations.d/mongodb-config.yml;
           fi
         - |
-          if [ "{{.NR_CLI_SSL}}" == "y" ]; then
-            if [ "{{.NR_CLI_SKIP_SSL_VERIFY}}" == "n" ]; then
-              sudo tee /etc/newrelic-infra/integrations.d/mongodb-config.yml > /dev/null <<"EOT"
+          if [ {{.NR_CLI_SSL}} == true ]; then
+            sudo tee /etc/newrelic-infra/integrations.d/mongodb-config.yml > /dev/null <<"EOT"
           integration_name: com.newrelic.mongodb
           instances:
             - name: all
               command: all
               arguments:
-                host: {{.NR_CLI_HOSTNAME}}
-                port: {{.NR_CLI_PORT}}
-                username: {{.NR_CLI_USERNAME}}
-                password: {{.NR_CLI_PASSWORD}}
-                auth_source: {{.NR_CLI_AUTH}}
-                cluster_name: {{.NR_CLI_CLUSTERNAME}}
+                # The mongos to connect to
+                host: {{.NR_CLI_DB_HOSTNAME}}
+                # The port the mongos is running on
+                port: {{.NR_CLI_DB_PORT}}
+                # The username of the user created to monitor the cluster.
+                # This user should exist on the cluster as a whole as well
+                # as on each of the individual mongods.
+                username: {{.NR_CLI_DB_USERNAME}}
+                # The password for the monitoring user
+                password: {{.NR_CLI_DB_PASSWORD}}
+                # The database on which the monitoring user is stored
+                auth_source: {{.NR_CLI_DB_AUTH}}
+                # A user-defined cluster name. Required.
+                cluster_name: {{.NR_CLI_DB_CLUSTERNAME}}
+                # Connect using SSL
                 ssl: true
-                ssl_insecure_skip_verify: true
+                # Path to the CA certs file
                 ssl_ca_certs: {{.NR_CLI_CERT_AUTH_FILE}}
+                # Client Certificate to present to the server (optional)
                 pem_key_file: {{.NR_CLI_CLIENT_CERT_FILE}}
-                passphrase: {{.NR_CLI_CERT_PASSPHRASE}}
+                # A JSON map of database names to an array of collection names. If empty,
+                # defaults to all databases and collections. If the list of collections is null,
+                # collects all collections for the database.
                 filters: '{"admin":null}'
-                concurrent_collections: 50
           EOT
-            else
-              sudo tee /etc/newrelic-infra/integrations.d/mongodb-config.yml > /dev/null <<"EOT"
+          else
+            sudo tee /etc/newrelic-infra/integrations.d/mongodb-config.yml > /dev/null <<"EOT"
           integration_name: com.newrelic.mongodb
           instances:
             - name: all
               command: all
               arguments:
-                host: {{.NR_CLI_HOSTNAME}}
-                port: {{.NR_CLI_PORT}}
-                username: {{.NR_CLI_USERNAME}}
-                password: {{.NR_CLI_PASSWORD}}
-                auth_source: {{.NR_CLI_AUTH}}
-                cluster_name: {{.NR_CLI_CLUSTERNAME}}
-                ssl: true
-                ssl_insecure_skip_verify: false
-                ssl_ca_certs: {{.NR_CLI_CERT_AUTH_FILE}}
-                filters: '{"admin":null}'
-                concurrent_collections: 50
-          EOT
-            fi
-            else
-              sudo tee /etc/newrelic-infra/integrations.d/mongodb-config.yml > /dev/null <<"EOT"
-          integration_name: com.newrelic.mongodb
-          instances:
-            - name: all
-              command: all
-              arguments:
-                host: {{.NR_CLI_HOSTNAME}}
-                port: {{.NR_CLI_PORT}}
-                username: {{.NR_CLI_USERNAME}}
-                password: {{.NR_CLI_PASSWORD}}
-                auth_source: {{.NR_CLI_AUTH}}
-                cluster_name: {{.NR_CLI_CLUSTERNAME}}
+                # The mongos to connect to
+                host: {{.NR_CLI_DB_HOSTNAME}}
+                # The port the mongos is running on
+                port: {{.NR_CLI_DB_PORT}}
+                # The username of the user created to monitor the cluster.
+                # This user should exist on the cluster as a whole as well
+                # as on each of the individual mongods.
+                username: {{.NR_CLI_DB_USERNAME}}
+                # The password for the monitoring user
+                password: {{.NR_CLI_DB_PASSWORD}}
+                # The database on which the monitoring user is stored
+                auth_source: {{.NR_CLI_DB_AUTH}}
+                # A user-defined cluster name. Required.
+                cluster_name: {{.NR_CLI_DB_CLUSTERNAME}}
+                # Connect using SSL
                 ssl: false
-                ssl_insecure_skip_verify: true
-                ssl_ca_certs: /sample/path/to/ca_certs
+                # A JSON map of database names to an array of collection names. If empty,
+                # defaults to all databases and collections. If the list of collections is null,
+                # collects all collections for the database.
                 filters: '{"admin":null}'
-                concurrent_collections: 50
           EOT
           fi
 
