refactor(recipes): fixed suse password, added checks to the recipe

diff --git a/recipes/newrelic/mysql/debian.yml b/recipes/newrelic/mysql/debian.yml
--- a/recipes/newrelic/mysql/debian.yml
+++ b/recipes/newrelic/mysql/debian.yml
@@ -61,6 +61,7 @@ install:
     default:
       cmds:
         - task: create_user_notification
+        - task: assert_pre_req
         - task: setup
         - task: restart
         
@@ -71,6 +72,23 @@ install:
           sudo mysql -e \"CREATE USER 'newrelic'@'localhost' IDENTIFIED BY 'YOUR_SELECTED_PASSWORD';\"\n
           sudo mysql -e \"GRANT REPLICATION CLIENT ON *.* TO 'newrelic'@'localhost' WITH MAX_USER_CONNECTIONS 5;\"\n
           sudo mysql -e \"GRANT SELECT ON *.* TO 'newrelic'@'localhost' WITH MAX_USER_CONNECTIONS 5;\""
+
+    assert_pre_req:
+      cmds:
+        - |
+          SERVICE_EXIST=$(sudo systemctl status newrelic-infra.service | grep "Active" | wc -l)
+          if [ $SERVICE_EXIST -eq 0 ]; then
+            echo "The newrelic-infra agent service is NOT installed on the host, but is required to install this integration." >> /dev/stderr
+            exit 1
+          fi
+        - |
+          CHECK_DB=$(mysql -u{{.NR_CLI_DB_USERNAME}} -p{{.NR_CLI_DB_PASSWORD}} -e "SHOW GRANTS FOR CURRENT_USER" | grep 'GRANT SELECT' | awk '{print $2, $3}')
+          EXPECTED=$(echo 'SELECT, REPLICATION')
+          if [ "$CHECK_DB" != "$EXPECTED" ] ; then
+            echo -e "[Error]: Provided user has no access to the desired database.\n - See https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/mysql-monitoring-integration#config for more info."
+            exit 2
+          fi
+
     setup:
       label: "Installing mysql integration..."
       cmds:
@@ -88,11 +106,7 @@ install:
           sudo cp /etc/newrelic-infra/integrations.d/mysql-config.yml.sample /etc/newrelic-infra/integrations.d/mysql-config.yml;
 
         - | 
-          # Check if the provided user can access database.
-          CHECK_DB=$(mysql -u{{.NR_CLI_DB_USERNAME}} -p{{.NR_CLI_DB_PASSWORD}} -e "SHOW GRANTS FOR CURRENT_USER" | grep 'GRANT SELECT' | awk '{print $2, $3}')
-          EXPECTED=$(echo 'SELECT, REPLICATION')
-          if [ "$CHECK_DB" == "$EXPECTED" ] ; then
-            sudo tee /etc/newrelic-infra/integrations.d/mysql-config.yml > /dev/null <<"EOT"
+          sudo tee /etc/newrelic-infra/integrations.d/mysql-config.yml > /dev/null <<"EOT"
           integration_name: com.newrelic.mysql
 
           instances: 
@@ -109,10 +123,7 @@ install:
                 extended_myisam_metrics: true
                 remote_monitoring: true
           EOT
-          else
-            echo -e "[Error]: Provided user has no access to the desired database.\n - See https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/mysql-monitoring-integration#config for more info."
-            exit 1;
-          fi
+
     restart:
       cmds:
         - sudo systemctl restart newrelic-infra.service
