mend
chore: attempt to create user automatically

diff --git a/recipes/newrelic/infrastructure/ohi/mysql/debian.yml b/recipes/newrelic/infrastructure/ohi/mysql/debian.yml
--- a/recipes/newrelic/infrastructure/ohi/mysql/debian.yml
+++ b/recipes/newrelic/infrastructure/ohi/mysql/debian.yml
@@ -96,28 +96,36 @@ install:
             NR_CLI_DB_PASSWORD=$(echo -n $(date +%s | sha256sum | base64 | head -c 16); echo "oO0$")
           fi
 
-          # Get and validate Port
-          if [[ "$NEW_RELIC_ASSUME_YES" != "true" ]]; then
-            TRIES=0
-            while [ $TRIES -lt {{.MAX_RETRIES}} ]; do
-              printf "MySQL port (default: 3306): "
-              read -r NR_CLI_DB_PORT
-              NR_CLI_DB_PORT=${NR_CLI_DB_PORT:-3306}
-              ((TRIES++))
-              CAN_CONNECT=$(curl $NR_CLI_DB_HOSTNAME:$NR_CLI_DB_PORT 2>&1 1>/dev/null -s -S | awk -F'[()]' '{print $2}')
-              CAN_CONNECT=${CAN_CONNECT:-0}
+          # Check to see if default port works, or prompt if non-interactive
+          CAN_CONNECT=$(curl $NR_CLI_DB_HOSTNAME:$NR_CLI_DB_PORT 2>&1 1>/dev/null -s -S | awk -F'[()]' '{print $2}')
+          CAN_CONNECT=${CAN_CONNECT:-0}
+          if [ $CAN_CONNECT != "0" ]; then 
+            if [[ "$NEW_RELIC_ASSUME_YES" != "true" ]]; then
+              # Get and validate Port
+              TRIES=0
+              while [ $TRIES -lt {{.MAX_RETRIES}} ]; do
+                printf "Enter the MySQL port (default: 3306): "
+                read -r NR_CLI_DB_PORT
+                NR_CLI_DB_PORT=${NR_CLI_DB_PORT:-3306}
+                ((TRIES++))
+                CAN_CONNECT=$(curl $NR_CLI_DB_HOSTNAME:$NR_CLI_DB_PORT 2>&1 1>/dev/null -s -S | awk -F'[()]' '{print $2}')
+                CAN_CONNECT=${CAN_CONNECT:-0}
 
-              if [ $CAN_CONNECT == "6" ]; then
-                printf "\n[Error]: Provided host ($NR_CLI_DB_HOSTNAME) cannot be reached.\nThis installation must be run on the host running MySql\nSee https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/mysql-monitoring-integration#config for more info.\n" >&2
-                exit 6;
-              elif [ $CAN_CONNECT == "7" ]; then
-                printf "\n[Error]: Connections to the port ($NR_CLI_DB_PORT) are being refused.\nSee https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/mysql-monitoring-integration#config for more info.\n" >&2
-                if [ ! $TRIES -lt {{.MAX_RETRIES}} ]; then exit 7; fi
-                echo "Please try again"
-              else
-                break
-              fi
-            done
+                if [ $CAN_CONNECT == "6" ]; then
+                  printf "\n[Error]: Provided host ($NR_CLI_DB_HOSTNAME) cannot be reached.\nThis installation must be run on the host running MySql\nSee https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/mysql-monitoring-integration#config for more info.\n" >&2
+                  exit 6;
+                elif [ $CAN_CONNECT == "7" ]; then
+                  printf "\n[Error]: Connections to the port ($NR_CLI_DB_PORT) are being refused.\nSee https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/mysql-monitoring-integration#config for more info.\n" >&2
+                  if [ ! $TRIES -lt {{.MAX_RETRIES}} ]; then exit 7; fi
+                  echo "Please try again"
+                else
+                  break
+                fi
+              done
+            else
+              printf "\n[Error]: Connections to the port ($NR_CLI_DB_PORT) are being refused.\nPlease re-run this installation and enter a valid port for the MySql instance when prompted.\n" >&2
+              exit 5;
+            fi
           fi
 
           # Attempt to create required user
