feat(mysql): add maridb support in mysql debain recipie

diff --git a/recipes/newrelic/infrastructure/ohi/mysql/debian.yml b/recipes/newrelic/infrastructure/ohi/mysql/debian.yml
--- a/recipes/newrelic/infrastructure/ohi/mysql/debian.yml
+++ b/recipes/newrelic/infrastructure/ohi/mysql/debian.yml
@@ -28,6 +28,7 @@ keywords:
 # Examine Infrastructure events for correlated data
 processMatch:
   - mysqld
+  - mariadbd
 
 preInstall:
   requireAtDiscovery: |
@@ -133,6 +134,9 @@ install:
           if [[ "$NEW_RELIC_MYSQL_PASSWORD" == "" ]]; then
             NEW_RELIC_MYSQL_PASSWORD=$(echo -n $(date +%s | sha256sum | base64 | head -c 16); echo "oO0$")
           fi
+
+          # Detect if MariaDB is being used
+          IS_MARIADB=$(mysql --version | grep -i mariadb | wc -l)
           
           # Check the Query monitoring status in previous installation
           QUERY_MONITORING_PREVIOUSLY_ENABLED=0
@@ -238,16 +242,26 @@ install:
               read -r USERNAME
               USERNAME=${USERNAME:-root}
           
-              printf "Enter password: "
+              printf "Enter password (leave blank if none): "
               stty -echo
               read -r NEW_RELIC_MYSQL_ROOT_PASSWORD
               stty echo
               printf "\n"
+              
+              # Defaults to socket-based authentication for MariaDB if no password is provided, otherwise uses password-based authentication.
+              # For more details, see: https://mariadb.com/kb/en/authentication-plugin-unix-socket/
+              if [[ -z "$NEW_RELIC_MYSQL_ROOT_PASSWORD" && $IS_MARIADB -eq 1 ]]; then
+                # Use socket-based authentication for MariaDB if no password is provided
+                sudo mysql -u "$USERNAME" < /tmp/sql-drop-user.sql &> /dev/null ||:
+                EXEC_OUTPUT=$(eval sudo mysql -u "$USERNAME" < /tmp/sql-create-user.sql 2>&1)
+              else
+                # Use password-based authentication for other cases
+                sudo mysql -u "$USERNAME" --port "$NEW_RELIC_MYSQL_PORT" -p"$NEW_RELIC_MYSQL_ROOT_PASSWORD" < /tmp/sql-drop-user.sql &> /dev/null ||:
+                EXEC_OUTPUT=$(eval sudo mysql -u "$USERNAME" --port "$NEW_RELIC_MYSQL_PORT" -p"$NEW_RELIC_MYSQL_ROOT_PASSWORD" < /tmp/sql-create-user.sql 2>&1)
+              fi
 
-              sudo mysql -u $USERNAME --port $NEW_RELIC_MYSQL_PORT -p$NEW_RELIC_MYSQL_ROOT_PASSWORD < /tmp/sql-drop-user.sql &> /dev/null ||:
-              EXEC_OUTPUT=$(eval sudo mysql -u $USERNAME --port $NEW_RELIC_MYSQL_PORT -p$NEW_RELIC_MYSQL_ROOT_PASSWORD < /tmp/sql-create-user.sql 2>&1)
-              echo "MySqlOutput:"$EXEC_OUTPUT | sudo tee -a {{.NEW_RELIC_CLI_LOG_FILE_PATH}} > /dev/null
-              SQL_OUTPUT_ERROR=$(echo -n $EXEC_OUTPUT | grep "ERROR" | wc -l)
+              echo "MySqlOutput: $EXEC_OUTPUT" | sudo tee -a {{.NEW_RELIC_CLI_LOG_FILE_PATH}} > /dev/null
+              SQL_OUTPUT_ERROR=$(echo -n "$EXEC_OUTPUT" | grep "ERROR" | wc -l)
               ((TRIES++))
             done
 
