feat: Implement db slow query analysis changes

diff --git a/recipes/newrelic/infrastructure/ohi/mysql/debian.yml b/recipes/newrelic/infrastructure/ohi/mysql/debian.yml
--- a/recipes/newrelic/infrastructure/ohi/mysql/debian.yml
+++ b/recipes/newrelic/infrastructure/ohi/mysql/debian.yml
@@ -133,6 +133,25 @@ install:
           if [[ "$NEW_RELIC_MYSQL_PASSWORD" == "" ]]; then
             NEW_RELIC_MYSQL_PASSWORD=$(echo -n $(date +%s | sha256sum | base64 | head -c 16); echo "oO0$")
           fi
+          
+          if [[ "$NR_CLI_SLOW_QUERY" == "true" ]]; then
+          CONFIG_FILES=(
+            "/etc/mysql/mysql.conf.d/mysqld.cnf"
+            "/etc/my.cnf"
+            "/etc/mysql/my.cnf"
+          )
+          
+          # Iterate through each configuration file path and update if it exists
+            FILE_FOUND=0
+            for config in "${CONFIG_FILES[@]}"; do
+              # Check if the file exists
+              if [[ -f "$config" ]]; then
+                echo "Found MySQL configuration file at $config."
+                FILE_FOUND=1
+                break
+              fi
+            done 
+          fi
 
           # Check to see if default port works, or prompt if non-interactive
           CAN_CONNECT=$(curl $NEW_RELIC_MYSQL_HOSTNAME:$NEW_RELIC_MYSQL_PORT 2>&1 1>/dev/null -s -S | awk -F'[()]' '{print $2}')
@@ -188,6 +207,11 @@ install:
           GRANT REPLICATION CLIENT ON *.* TO 'newrelic'@'localhost';
           GRANT SELECT ON *.* TO 'newrelic'@'localhost';
           EOT
+          
+          # Conditionally append the GRANT PROCESS command if NR_CLI_SLOW_QUERY is true
+          if [[ "$NR_CLI_SLOW_QUERY" == "true" && $FILE_FOUND -eq 1 ]]; then
+            echo "GRANT PROCESS ON *.* TO 'newrelic'@'localhost';" | sudo tee -a /tmp/sql-create-user.sql > /dev/null
+          fi
 
           sudo sed -i 's/NEW_RELIC_MYSQL_USERNAME/'$NEW_RELIC_MYSQL_USERNAME'/g' /tmp/sql-drop-user.sql
           sudo sed -i 's/NEW_RELIC_MYSQL_USERNAME/'$NEW_RELIC_MYSQL_USERNAME'/g' /tmp/sql-create-user.sql
@@ -205,6 +229,11 @@ install:
               printf "\nPlease enter your username for MySql (default: root): "
               read -r USERNAME
               USERNAME=${USERNAME:-root}
+          
+              printf "\nEnter password: "
+              stty -echo
+              read -r NEW_RELIC_MYSQL_ROOT_PASSWORD
+              stty echo
 
               sudo mysql -u $USERNAME --port $NEW_RELIC_MYSQL_PORT -p$NEW_RELIC_MYSQL_ROOT_PASSWORD < /tmp/sql-drop-user.sql &> /dev/null ||:
               EXEC_OUTPUT=$(eval sudo mysql -u $USERNAME --port $NEW_RELIC_MYSQL_PORT -p$NEW_RELIC_MYSQL_ROOT_PASSWORD < /tmp/sql-create-user.sql 2>&1)
@@ -256,6 +285,25 @@ install:
           fi
 
           sudo cp /etc/newrelic-infra/integrations.d/mysql-config.yml.sample /etc/newrelic-infra/integrations.d/mysql-config.yml;
+          if [[ "$NR_CLI_SLOW_QUERY" == "true" && $FILE_FOUND -eq 1 ]]; then
+          sudo tee /etc/newrelic-infra/integrations.d/mysql-config.yml > /dev/null <<EOT
+          integrations:
+            - name: nri-mysql
+              env:
+                HOSTNAME: $NEW_RELIC_MYSQL_HOSTNAME
+                PORT: $NEW_RELIC_MYSQL_PORT
+                USERNAME: $NEW_RELIC_MYSQL_USERNAME
+                PASSWORD: '$NEW_RELIC_MYSQL_PASSWORD'
+                DATABASE:
+                EXTENDED_METRICS: true
+                EXTENDED_INNODB_METRICS: true
+                EXTENDED_MYISAM_METRICS: true
+                REMOTE_MONITORING: true
+                ENABLE_QUERY_MONITORING: true
+              inventory_source: config/mysql
+              interval: 30s
+          EOT
+          else
           sudo tee /etc/newrelic-infra/integrations.d/mysql-config.yml > /dev/null <<EOT
           integrations:
             - name: nri-mysql
@@ -272,6 +320,86 @@ install:
               inventory_source: config/mysql
               interval: 30s
           EOT
+          fi
+          
+          # Function to update or append the performance_schema and init-file properties
+          update_mysql_config() {
+              local config_file="$1"
+          
+              # Check if the [mysqld] section is present
+              if ! grep -qE '^\[mysqld\]' "$config_file"; then
+                # Append the [mysqld] section with the properties if not present
+                cp "$config_file" "$config_file.bak"
+                echo -e "\n[mysqld]\nperformance_schema=ON\ninit-file=/etc/mysql/init.sql" >> "$config_file"
+                echo "Successfully added the [mysqld] section with performance_schema=ON and init-file=/etc/mysql/init.sql to $config_file."
+              else
+                # Handle performance_schema property
+                if grep -qE '^\s*performance_schema\s*=\s*ON\s*$' "$config_file"; then
+                  echo "The performance_schema is already set to ON in $config_file. No changes made."
+                elif grep -qE '^\s*performance_schema\s*=' "$config_file"; then
+                  # Update any other value to ON
+                  sed -i.bak 's/^\s*performance_schema\s*=.*$/performance_schema=ON/' "$config_file"
+                  echo "Updated performance_schema to ON in $config_file."
+                else
+                  # Append the property below the [mysqld] section if not present
+                  sed -i.bak '/\[mysqld\]/a\performance_schema=ON' "$config_file"
+                    echo "Appended performance_schema=ON to $config_file."
+                  fi
+                  # Handle init-file property
+                  if grep -qE '^\s*init-file\s*=\s*/etc/mysql/init.sql\s*$' "$config_file"; then
+                    echo "The init-file is already set to /etc/mysql/init.sql in $config_file. No changes made."
+                  elif grep -qE '^\s*init-file\s*=' "$config_file"; then
+                    # Update any other value to /etc/mysql/init.sql
+                    sed -i 's|^\s*init-file\s*=.*$|init-file=/etc/mysql/init.sql|' "$config_file"
+                    echo "Updated init-file to /etc/mysql/init.sql in $config_file."
+                  else
+                    # Append the property below the [mysqld] section if not present
+                    sed -i '/\[mysqld\]/a\init-file=/etc/mysql/init.sql' "$config_file"
+                    echo "Appended init-file=/etc/mysql/init.sql to $config_file."
+                  fi
+                fi
+            }
+          
+          create_init_sql() {       
+          # Create init.sql file with required SQL commands
+          local INIT_FILE="/etc/mysql/init.sql"
+          
+          cat <<EOF | sudo tee "$INIT_FILE" > /dev/null
+          -- Enable required Performance Schema instruments
+          UPDATE performance_schema.setup_instruments SET ENABLED = 'YES', TIMED = 'YES' WHERE NAME LIKE 'wait/%';
+          -- Enable CPU Instruments
+          UPDATE performance_schema.setup_instruments SET ENABLED = 'YES', TIMED = 'YES' WHERE NAME LIKE 'statement/%';
+          -- Enable Collection of Current Data Lock Waits
+          UPDATE performance_schema.setup_instruments SET ENABLED = 'YES', TIMED = 'YES' WHERE NAME LIKE '%lock%';
+          -- Enable required Performance Schema consumers
+          UPDATE performance_schema.setup_consumers SET ENABLED = 'YES' WHERE NAME IN ('events_waits_current', 'events_waits_history_long', 'events_waits_history', 'events_statements_history_long');
+          -- Enable required Performance Schema consumers for CPU metrics
+          UPDATE performance_schema.setup_consumers SET ENABLED = 'YES' WHERE NAME IN ('events_statements_history', 'events_statements_current', 'events_statements_cpu');
+          UPDATE performance_schema.setup_consumers SET ENABLED = 'YES' WHERE NAME LIKE 'events_waits_current%' OR NAME LIKE 'events_statements_current%';
+          SET GLOBAL innodb_lock_wait_timeout = 120; -- Increase to 2 minutes
+          EOF
+          
+          echo "Created $INIT_FILE with necessary SQL commands."
+          
+          printf "Restart the MySQL server after the agent installation? Selecting 'y' will automatically restart the mysql server that is detected. Selecting 'n' will require you to manually restart the process to reflect the slow query configuration changes. (y/n): "
+          read -r APPLICATION_RESTART
+          APPLICATION_RESTART=${APPLICATION_RESTART:-y}
+          
+          if [ "$APPLICATION_RESTART" = "y" ]; then
+            # Restart MySQL service using systemd
+            sudo systemctl restart mysqld
+            echo "MySQL server restarted to apply changes."
+          else  
+            echo "Warning: Slow query configuration changes will be applied the next time you restart your MySQL server."
+          fi     
+          }
+          
+          if [[ "$NR_CLI_SLOW_QUERY" == "true" && $FILE_FOUND -eq 1 ]]; then
+              update_mysql_config "$config"
+              create_init_sql
+          else
+            echo "Error: No MySQL configuration file found in ${CONFIG_FILES[@]}. Slow query configuration changes will not be applied."
+          fi
 
     collect_meta:
       cmds:
@@ -280,7 +408,7 @@ install:
           version=$(type mysqld &>/dev/null && mysqld --version)
           echo {\"Metadata\": {\"user\":\"$user\", \"version\":\"$version\"}} | tee {{.NR_CLI_OUTPUT}} > /dev/null
 
-  info: |2
+info: |2
       ⚙️  The MySQL configuration file can be found in /etc/newrelic-infra/integrations.d/mysql-config.yml
       Edit this file to make changes or configure advanced features for this integration. See the docs for options:
       https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/mysql-monitoring-integration#config
