feat: Added minor enhancements to db query analysis

diff --git a/recipes/newrelic/infrastructure/ohi/mysql/debian.yml b/recipes/newrelic/infrastructure/ohi/mysql/debian.yml
--- a/recipes/newrelic/infrastructure/ohi/mysql/debian.yml
+++ b/recipes/newrelic/infrastructure/ohi/mysql/debian.yml
@@ -323,84 +323,74 @@ install:
           
           # Function to update or append the performance_schema and init-file properties
           update_mysql_config() {
-              local config_file="$1"
-              backup_log="[NR_CLI_SLOW_QUERY] Created /etc/my.cnf.bak backup file"
-          
-              # Check if the [mysqld] section is present
-              if ! grep -qE '^\[mysqld\]' "$config_file"; then
+            local config_file="$1"
+            backup_log="[NR_CLI_SLOW_QUERY] Created /etc/my.cnf.bak backup file"
+
+            # Check if the [mysqld] section is present
+            if ! grep -qE '^\[mysqld\]' "$config_file"; then
                 # Append the [mysqld] section with the properties if not present
                 cp "$config_file" "$config_file.bak"
                 echo "$backup_log"
-                echo -e "\n[mysqld]\nperformance_schema=ON\ninit-file=/etc/mysql/init.sql" >> "$config_file"
-                echo "[NR_CLI_SLOW_QUERY] Successfully added the [mysqld] section with performance_schema=ON and init-file=/etc/mysql/init.sql to $config_file."
-              else
+                echo -e "\n[mysqld]\nperformance_schema=ON\nmax_digest_length=4096\nperformance_schema_max_digest_length=4096\nperformance_schema_max_sql_text_length=4096\nperformance-schema-instrument='statement/%=ON'\nperformance-schema-consumer-events-statements-current=ON\nperformance-schema-consumer-events-statements-history=ON\nperformance-schema-consumer-events-statements-history-long=ON\nperformance-schema-consumer-events-statements-cpu=ON\nperformance-schema-instrument='wait/%=ON'\nperformance-schema-consumer-events-waits-current=ON\nperformance-schema-consumer-events-waits-history=ON\nperformance-schema-consumer-events-waits-history-long=ON\nperformance-schema-instrument='%lock%=ON" >> "$config_file"
+                echo "[NR_CLI_SLOW_QUERY] Successfully added the [mysqld] section with the required properties to $config_file."
+            else
                 # Handle performance_schema property
                 if grep -qE '^\s*performance_schema\s*=\s*ON\s*$' "$config_file"; then
-                  echo "[NR_CLI_SLOW_QUERY] The performance_schema is already set to ON in $config_file. No changes made."
+                    echo "[NR_CLI_SLOW_QUERY] The performance_schema is already set to ON in $config_file. No changes made."
                 elif grep -qE '^\s*performance_schema\s*=' "$config_file"; then
-                  # Update any other value to ON
-                  sed -i.bak 's/^\s*performance_schema\s*=.*$/performance_schema=ON/' "$config_file"
-                  echo "$backup_log"
-                  echo "[NR_CLI_SLOW_QUERY] Updated performance_schema to ON in $config_file."
+                    # Update any other value to ON
+                    sed -i.bak 's/^\s*performance_schema\s*=.*$/performance_schema=ON/' "$config_file"
+                    echo "$backup_log"
+                    echo "[NR_CLI_SLOW_QUERY] Updated performance_schema to ON in $config_file."
                 else
-                  # Append the property below the [mysqld] section if not present
-                  sed -i.bak '/\[mysqld\]/a\performance_schema=ON' "$config_file"
+                    # Append the property below the [mysqld] section if not present
+                    sed -i.bak '/\[mysqld\]/a\performance_schema=ON' "$config_file"
                     echo "$backup_log"
                     echo "[NR_CLI_SLOW_QUERY] Appended performance_schema=ON to $config_file."
-                  fi
-                  # Handle init-file property
-                  if grep -qE '^\s*init-file\s*=\s*/etc/mysql/init.sql\s*$' "$config_file"; then
-                    echo "[NR_CLI_SLOW_QUERY] The init-file is already set to /etc/mysql/init.sql in $config_file. No changes made."
-                  elif grep -qE '^\s*init-file\s*=' "$config_file"; then
-                    # Update any other value to /etc/mysql/init.sql
-                    sed -i 's|^\s*init-file\s*=.*$|init-file=/etc/mysql/init.sql|' "$config_file"
-                    echo "[NR_CLI_SLOW_QUERY] Updated init-file to /etc/mysql/init.sql in $config_file."
-                  else
-                    # Append the property below the [mysqld] section if not present
-                    sed -i '/\[mysqld\]/a\init-file=/etc/mysql/init.sql' "$config_file"
-                    echo "[NR_CLI_SLOW_QUERY] Appended init-file=/etc/mysql/init.sql to $config_file."
-                  fi
                 fi
-            }
-          
-          create_init_sql() {       
-          # Create init.sql file with required SQL commands
-          local INIT_FILE="/etc/mysql/init.sql"
-          
-          cat <<EOF | sudo tee "$INIT_FILE" > /dev/null
-          -- Enable required Performance Schema instruments
-          UPDATE performance_schema.setup_instruments SET ENABLED = 'YES', TIMED = 'YES' WHERE NAME LIKE 'wait/%';
-          -- Enable CPU Instruments
-          UPDATE performance_schema.setup_instruments SET ENABLED = 'YES', TIMED = 'YES' WHERE NAME LIKE 'statement/%';
-          -- Enable Collection of Current Data Lock Waits
-          UPDATE performance_schema.setup_instruments SET ENABLED = 'YES', TIMED = 'YES' WHERE NAME LIKE '%lock%';
-          -- Enable required Performance Schema consumers
-          UPDATE performance_schema.setup_consumers SET ENABLED = 'YES' WHERE NAME IN ('events_waits_current', 'events_waits_history_long', 'events_waits_history', 'events_statements_history_long');
-          -- Enable required Performance Schema consumers for CPU metrics
-          UPDATE performance_schema.setup_consumers SET ENABLED = 'YES' WHERE NAME IN ('events_statements_history', 'events_statements_current', 'events_statements_cpu');
-          UPDATE performance_schema.setup_consumers SET ENABLED = 'YES' WHERE NAME LIKE 'events_waits_current%' OR NAME LIKE 'events_statements_current%';
-          SET GLOBAL innodb_lock_wait_timeout = 120; -- Increase to 2 minutes
-          EOF
-          
-          echo "[NR_CLI_SLOW_QUERY] Created $INIT_FILE with necessary SQL commands."
-          
-          printf "\nRestart your MySQL instance to enable the performance schema settings now? (y/n): "
-          read -r APPLICATION_RESTART
-          APPLICATION_RESTART=${APPLICATION_RESTART:-y}
-          
-          if [ "$APPLICATION_RESTART" = "y" ]; then
-            if systemctl status mysqld >/dev/null 2>&1; then
-              # Restart mysqld service using systemd
-              sudo systemctl restart mysqld
-              echo -e "\n[NR_CLI_SLOW_QUERY] MySQL server restarted to apply changes."
-            elif systemctl status mysql >/dev/null 2>&1; then
-              # Restart mysql service using systemd
-              sudo systemctl restart mysql
-              echo -e "\n[NR_CLI_SLOW_QUERY] MySQL server restarted to apply changes."
+
+                # Append or update other required properties
+                if ! grep -qE '^\s*max_digest_length\s*=\s*4096\s*$' "$config_file"; then
+                    sed -i '/\[mysqld\]/a\max_digest_length=4096' "$config_file"
+                fi
+                if ! grep -qE '^\s*performance_schema_max_digest_length\s*=\s*4096\s*$' "$config_file"; then
+                    sed -i '/\[mysqld\]/a\performance_schema_max_digest_length=4096' "$config_file"
+                fi
+                if ! grep -qE '^\s*performance_schema_max_sql_text_length\s*=\s*4096\s*$' "$config_file"; then
+                    sed -i '/\[mysqld\]/a\performance_schema_max_sql_text_length=4096' "$config_file"
+                fi
+                if ! grep -qE '^\s*performance-schema-instrument='\''statement/%=ON'\''\s*$' "$config_file"; then
+                    sed -i '/\[mysqld\]/a\performance-schema-instrument='\''statement/%=ON'\''' "$config_file"
+                fi
+                if ! grep -qE '^\s*performance-schema-consumer-events-statements-current\s*=\s*ON\s*$' "$config_file"; then
+                    sed -i '/\[mysqld\]/a\performance-schema-consumer-events-statements-current=ON' "$config_file"
+                fi
+                if ! grep -qE '^\s*performance-schema-consumer-events-statements-history\s*=\s*ON\s*$' "$config_file"; then
+                    sed -i '/\[mysqld\]/a\performance-schema-consumer-events-statements-history=ON' "$config_file"
+                fi
+                if ! grep -qE '^\s*performance-schema-consumer-events-statements-history-long\s*=\s*ON\s*$' "$config_file"; then
+                    sed -i '/\[mysqld\]/a\performance-schema-consumer-events-statements-history-long=ON' "$config_file"
+                fi
+                if ! grep -qE '^\s*performance-schema-consumer-events-statements-cpu\s*=\s*ON\s*$' "$config_file"; then
+                    sed -i '/\[mysqld\]/a\performance-schema-consumer-events-statements-cpu=ON' "$config_file"
+                fi
+                if ! grep -qE '^\s*performance-schema-instrument='\''wait/%=ON'\''\s*$' "$config_file"; then
+                    sed -i '/\[mysqld\]/a\performance-schema-instrument='\''wait/%=ON'\''' "$config_file"
+                fi
+                if ! grep -qE '^\s*performance-schema-consumer-events-waits-current\s*=\s*ON\s*$' "$config_file"; then
+                    sed -i '/\[mysqld\]/a\performance-schema-consumer-events-waits-current=ON' "$config_file"
+                fi
+                if ! grep -qE '^\s*performance-schema-consumer-events-waits-history\s*=\s*ON\s*$' "$config_file"; then
+                    sed -i '/\[mysqld\]/a\performance-schema-consumer-events-waits-history=ON' "$config_file"
+                fi
+                if ! grep -qE '^\s*performance-schema-consumer-events-waits-history-long\s*=\s*ON\s*$' "$config_file"; then
+                    sed -i '/\[mysqld\]/a\performance-schema-consumer-events-waits-history-long=ON' "$config_file"
+                fi
+                if ! grep -qE '^\s*performance-schema-instrument='\''%lock%=ON'\''\s*$' "$config_file"; then
+                    sed -i '/\[mysqld\]/a\performance-schema-instrument='\''%lock%=ON'\''' "$config_file"
+                fi
+                echo "[NR_CLI_SLOW_QUERY] Appended additional performance schema properties to $config_file."
             fi
-          else  
-            echo -e "\n\033[0;33m[Warning] The Performance Schema configuration changes of the database will become active the next time you restart your MySQL server. Without those changes, the New Relic integration will not be able to collect SQL query level details.\033[0m" >&2
-          fi     
           }
           
           if [[ "$NR_CLI_SLOW_QUERY" == "true" ]]; then
@@ -409,7 +399,53 @@ install:
               echo "[NR_CLI_SLOW_QUERY] Granted PROCESS privilege to the $NEW_RELIC_MYSQL_USERNAME user"
               echo -e "[NR_CLI_SLOW_QUERY] Updated \`ENABLE_QUERY_MONITORING: true\` in /etc/newrelic-infra/integrations.d/mysql-config.yml"
               update_mysql_config "$config"
-              create_init_sql
+              
+              # Check and create schema, grant permissions, and define stored procedure
+              echo -e "\n--- Validating and creating schema and stored procedure for New Relic"
+              sudo mysql -u root --port $NEW_RELIC_MYSQL_PORT -p$NEW_RELIC_MYSQL_ROOT_PASSWORD <<EOT
+              
+              # Check if the schema exists
+              CREATE SCHEMA IF NOT EXISTS newrelic;
+
+              # Grant permissions to the newrelic user
+              GRANT EXECUTE ON newrelic.* TO 'newrelic'@'localhost';
+
+              # Check if the procedure already exists
+              DELIMITER $$
+              CREATE PROCEDURE IF NOT EXISTS newrelic.enable_essential_consumers_and_instruments()
+                  SQL SECURITY DEFINER
+              BEGIN
+                  UPDATE performance_schema.setup_consumers SET enabled='YES' WHERE name LIKE 'events_statements_%';
+                  UPDATE performance_schema.setup_consumers SET enabled='YES' WHERE name LIKE 'events_waits_%';
+                  UPDATE performance_schema.setup_instruments SET ENABLED = 'YES', TIMED = 'YES' WHERE NAME LIKE 'wait/%' OR NAME LIKE 'statement/%' OR NAME LIKE '%lock%';
+              END $$
+              DELIMITER ;
+
+              # Grant execute permission on the procedure
+              GRANT EXECUTE ON PROCEDURE newrelic.enable_essential_consumers_and_instruments TO 'newrelic'@'localhost';
+              EOT
+              echo "[NR_CLI_SLOW_QUERY] Schema and stored procedure validated and created successfully."
+
+              # Prompt user to restart MySQL instance
+              printf "\nRestart your MySQL instance to enable the performance schema settings now? (y/n): "
+              read -r APPLICATION_RESTART
+              APPLICATION_RESTART=${APPLICATION_RESTART:-y}
+
+              
+              # Restart MySQL service or provide a warning
+              if [ "$APPLICATION_RESTART" = "y" ]; then
+                  if systemctl status mysqld >/dev/null 2>&1; then
+                      # Restart mysqld service using systemd
+                      sudo systemctl restart mysqld
+                      echo -e "\n[NR_CLI_SLOW_QUERY] MySQL server restarted to apply changes."
+                  elif systemctl status mysql >/dev/null 2>&1; then
+                      # Restart mysql service using systemd
+                      sudo systemctl restart mysql
+                      echo -e "\n[NR_CLI_SLOW_QUERY] MySQL server restarted to apply changes."
+                  fi
+              else  
+                  echo -e "\n\033[0;33m[Warning] The Performance Schema configuration changes of the database will become active the next time you restart your MySQL server. Without those changes, the New Relic integration will not be able to collect SQL query level details.\033[0m" >&2
+              fi
             else
               echo -e "\033[0;33m[Warning] The database settings could not be checked or amended to enable the required Performance Schema. The rest of the installation will continue, to make sure we collect the basic telemetry data for MySQL, but these database configuration steps will need to be done manually. Instructions can be found (soon) on the documentation page for the MySQL Integration.\033[0m" >&2
             fi
