feat: Implement db slow query analysis changes

diff --git a/recipes/newrelic/infrastructure/ohi/mysql/rhel.yml b/recipes/newrelic/infrastructure/ohi/mysql/rhel.yml
--- a/recipes/newrelic/infrastructure/ohi/mysql/rhel.yml
+++ b/recipes/newrelic/infrastructure/ohi/mysql/rhel.yml
@@ -147,7 +147,7 @@ install:
               fi
             done
           elif [[ "$QUERY_MONITORING_PREVIOUSLY_ENABLED" -eq 1 ]]; then
-            echo "This guided install can enable the performance schema of your DB system, but it cannot safely turn these off. Please find details of what was enabled in a previous guided install in the log file /root/.newrelic/newrelic-cli.log. These details need to be manually reverted, if so desired."
+            echo -e "\033[0;33mThis guided install can enable the performance schema of your DB system, but it cannot safely turn these off.Please find details of what was enabled in a previous guided install in the log file /root/.newrelic/newrelic-cli.log. These details need to be manually reverted, if so desired.\033[0m" >&2
           fi
 
           # Check to see if default port works, or prompt if non-interactive
@@ -325,6 +325,7 @@ install:
           # Function to update or append the performance_schema and init-file properties
           update_mysql_config() {
               local config_file="$1"
+              backup_log="[NR_CLI_SLOW_QUERY] Created my.cnf.bak backup file"
           
               echo -e "\n--- Checking MySQL configuration settings"
           
@@ -332,6 +333,7 @@ install:
               if ! grep -qE '^\[mysqld\]' "$config_file"; then
                 # Append the [mysqld] section with the properties if not present
                 cp "$config_file" "$config_file.bak"
+                echo "$backup_log"
                 echo -e "\n[mysqld]\nperformance_schema=ON\ninit-file=/etc/my.cnf.d/init.sql" >> "$config_file"
                 echo "[NR_CLI_SLOW_QUERY] Successfully added the [mysqld] section with performance_schema=ON and init-file=/etc/my.cnf.d/init.sql to $config_file."
               else
@@ -341,10 +343,12 @@ install:
                 elif grep -qE '^\s*performance_schema\s*=' "$config_file"; then
                   # Update any other value to ON
                   sed -i.bak 's/^\s*performance_schema\s*=.*$/performance_schema=ON/' "$config_file"
+                  echo "$backup_log"
                   echo "[NR_CLI_SLOW_QUERY] Updated performance_schema to ON in $config_file."
                 else
                   # Append the property below the [mysqld] section if not present
                   sed -i.bak '/\[mysqld\]/a\performance_schema=ON' "$config_file"
+                    echo "$backup_log"  
                     echo "[NR_CLI_SLOW_QUERY] Appended performance_schema=ON to $config_file."
                   fi
                   # Handle init-file property
@@ -405,6 +409,7 @@ install:
               echo -e "\033[0;33m[Warning] The database settings could not be checked or amended to enable the required Performance Schema. The rest of the installation will continue, to make sure we collect the basic telemetry data for MySQL, but these database configuration steps will need to be done manually. Instructions can be found (soon) on the documentation page for the MySQL Integration.\033[0m" >&2
             fi
           fi
+          echo "You can find the CLI logs in this path: /root/.newrelic/newrelic-cli.log"
     restart:
       cmds:
         - |
