chore: attempt to create user automatically

diff --git a/recipes/newrelic/infrastructure/ohi/mysql/rhel.yml b/recipes/newrelic/infrastructure/ohi/mysql/rhel.yml
--- a/recipes/newrelic/infrastructure/ohi/mysql/rhel.yml
+++ b/recipes/newrelic/infrastructure/ohi/mysql/rhel.yml
@@ -93,7 +93,7 @@ install:
           NR_CLI_DB_PORT=${NR_CLI_DB_PORT:-3306}
           NR_CLI_DB_USERNAME=${NR_CLI_DB_USERNAME:-newrelic}
           if [ "$NR_CLI_DB_PASSWORD" == "" ]; then
-            NR_CLI_DB_PASSWORD=$(echo -n $(date +%s | sha256sum | base64 | head -c 16); echo "%")
+            NR_CLI_DB_PASSWORD=$(echo -n $(date +%s | sha256sum | base64 | head -c 16); echo "oO0%")
           fi
 
           # Get and validate Port
@@ -179,7 +179,9 @@ install:
           fi
           SQL_OUTPUT_ERROR=$(echo -n $EXEC_OUTPUT | grep "ERROR" | wc -l)
           if [ $SQL_OUTPUT_ERROR -gt 0 ] ; then
-            printf "\n[Error]: This installation failed to create the required newrelic user, detail:"$EXEC_OUTPUT". Please follow the manual installation steps documented at https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/mysql-monitoring-integration/\n" >&2
+            echo "SQL:"$SQL
+            echo "OUTPUT:"$EXEC_OUTPUT
+            printf "\n[Error]: This installation failed to create the required newrelic user. Please follow the manual installation steps documented at https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/mysql-monitoring-integration/\n" >&2
             exit 41
           fi
 
