Sync ubuntu and centos recipes

diff --git a/recipes/newrelic/ebpf/centos.yml b/recipes/newrelic/ebpf/centos.yml
--- a/recipes/newrelic/ebpf/centos.yml
+++ b/recipes/newrelic/ebpf/centos.yml
@@ -94,10 +94,12 @@ install:
             exit 15
           fi
         - |
+          IS_GPG_AGENT_INSTALLED=$(which gpg-agent | wc -l)
+          IS_GPG_CONNECT_AGENT_INSTALLED=$(which gpg-connect-agent | wc -l)
           IS_GPG_INSTALLED=$(which gpg | wc -l)
-          if [ $IS_GPG_INSTALLED -eq 0 ] ; then
+          if [ $IS_GPG_AGENT_INSTALLED -eq 0 ] || [ $IS_GPG_CONNECT_AGENT_INSTALLED -eq 0 ] || [ $IS_GPG_INSTALLED -eq 0 ]; then
             echo ""
-            echo -e "\e[31mERROR:\e[0m gpg is required to run the newrelic install. Please install gpg and re-run the installation." >&2
+            echo -e "\e[31mERROR:\e[0m GnuPG suite is required to run the newrelic install. Please install gnupg suite and re-run the installation." >&2
             echo ""
             exit 15
           fi
@@ -110,15 +112,15 @@ install:
             exit 15
           fi
         - |
-          if [[ ! -d "$PX_DIR" ]]; then
-            if ! sudo mkdir -p /px; then
+          if [[ ! -d "/px" ]]; then
+            if ! sudo mkdir -p "/px"; then
               echo ""
               echo -e "\e[31mERROR:\e[0m Failed to create /px directory. Aborting installation."
               echo ""
               exit 16
             fi
           else
-            echo "Directory /px already exists. Continuing with installation."  
+            echo "Directory /px already exists. Continuing with installation."
           fi
 
     check_config_file:
@@ -418,7 +420,6 @@ install:
             echo ""
             echo -e "\e[31mERROR:\e[0m Failed to install kernel headers for kernel $KERNEL_VERSION. Please ensure the correct headers are available and try again."
             echo ""
-            exit 20
           fi
           echo "Kernel headers installed successfully for kernel $KERNEL_VERSION."ignore_error: true
       ignore_error: true
