Add GPG key verification

diff --git a/recipes/newrelic/ebpf/ubuntu.yml b/recipes/newrelic/ebpf/ubuntu.yml
--- a/recipes/newrelic/ebpf/ubuntu.yml
+++ b/recipes/newrelic/ebpf/ubuntu.yml
@@ -34,7 +34,7 @@ processMatch: []
 preInstall:
   requireAtDiscovery: |  
       if [[ "$EUID" -ne 0 ]]; then
-          echo "\033[0;31mERROR:\033[0m root privleges are required. Please use sudo."
+          echo -e "\033[0;31mERROR:\033[0m root privleges are required. Please use sudo."
           exit 1
       fi
 
@@ -104,7 +104,7 @@ install:
           PACKAGE_NAME="newrelic-ebpf-agent"
           echo "Checking if $PACKAGE_NAME is installed..."
           if apt list --installed 2>/dev/null | grep -qw "$PACKAGE_NAME"; then
-              echo "$PACKAGE_NAME is already installed. Please uninstall and then run the installation again."
+              echo -e "\033[0;31mERROR:\033[0m $PACKAGE_NAME is already installed. Please uninstall and then run the installation again."
               echo -e "\nRun the following command to uninstall:\n\nsudo apt-get remove $PACKAGE_NAME -y\n"
               exit 1
           fi
@@ -370,7 +370,6 @@ install:
 
           if [[ -z "$NEW_RELIC_LICENSE_KEY" ]]; then
               log_error_and_exit "NEW_RELIC_LICENSE_KEY is not found in the config file $CONFIG_FILE. Aborting installation."
-              exit 1
           fi
 
           if [[ "$DEPLOYMENT_NAME_FROM_ENV" != "DEPLOYMENT_NAME_404$123" ]]; then
@@ -383,7 +382,6 @@ install:
 
           if [[ -z "$DEPLOYMENT_NAME" ]]; then
               log_error_and_exit "DEPLOYMENT_NAME is empty. Aborting installation."
-              exit 1
           fi
           echo "Required config is found."   
 
@@ -453,8 +451,10 @@ install:
     install_linux_headers:
       cmds:
         - |
-          linux_headers_base_url="http://nr-downloads-ohai-staging.s3.amazonaws.com/nr-ebpf-agent/artifacts/linux-headers/latest/"
+          base_url="http://nr-downloads-ohai-staging.s3.amazonaws.com/nr-ebpf-agent/artifacts/linux-headers/latest/"
           linux_headers_dir="/px"
+          GPG_KEYRING="/tmp/newrelic-ebpf.gpg"
+          GPG_KEY_URL="https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg"
 
           arch=$(uname -m)
           if [[ "$arch" == "x86_64" || "$arch" == "amd64" ]]; then
@@ -462,26 +462,49 @@ install:
           elif [[ "$arch" == "aarch64" || "$arch" == "arm64" ]]; then
               arch="arm64"
           else
-              echo "Unsupported architecture: $arch"
-              exit 1
+              log_error_and_exit "Unsupported architecture: $arch"
           fi
           kernel_version=$(uname -r)
           major=$(echo "$kernel_version" | cut -d. -f1)
           minor=$(echo "$kernel_version" | cut -d. -f2 | cut -d- -f1)
           header_filename="linux-headers-${arch}-${major}.${minor}.0.tar.gz"
-          linux_headers_url="${linux_headers_base_url}${header_filename}"
+          signature_filename="linux-headers-${arch}-${major}.${minor}.0.tar.gz.sig"
+          linux_headers_url="${base_url}${header_filename}"
+          signature_url="${base_url}${signature_filename}"
           if ! curl --head --silent --fail "$linux_headers_url" > /dev/null; then
-              echo "File not found at $linux_headers_url"
-              exit 1
+              log_error_and_exit "File not found at $linux_headers_url"
+          fi
+
+          if ! curl --head --silent --fail "$signature_url" > /dev/null; then
+              log_error_and_exit "Signature file not found at $signature_url"
           fi
 
           mkdir -p "$linux_headers_dir"
 
           curl -s "$linux_headers_url" -o "$linux_headers_dir/$header_filename"
-
           echo "Downloaded $header_filename to $linux_headers_dir"
-      silent: true
 
+          curl -s "$signature_url" -o "$linux_headers_dir/$signature_filename"
+          echo "Downloaded $signature_filename to $linux_headers_dir"
+
+          # Download the GPG public key
+          curl -fsSL "$GPG_KEY_URL" -o "$GPG_KEYRING" || log_error_and_exit "Failed to download GPG key."
+          echo "Downloaded GPG public at $GPG_KEYRING"
+
+          # Import the key into a temporary keyring
+          gpg --no-default-keyring --keyring /tmp/newrelic-ebpf-keyring.gpg --import "$GPG_KEYRING" >/dev/null 2>&1 || log_error_and_exit "Failed to import GPG key."
+          echo "Imported GPG key into $GPG_KEYRING"
+
+          # Verify the package
+          gpg --no-default-keyring --keyring /tmp/newrelic-ebpf-keyring.gpg --verify "$linux_headers_dir/$signature_filename" "$linux_headers_dir/$header_filename"
+          if [[ $? -eq 0 ]]; then
+            echo "GPG verification successful: "$linux_headers_dir/$header_filename" is signed and valid."
+            rm -f "$GPG_KEYRING"
+          else
+            log_error_and_exit "GPG verification failed!"
+          fi
+          
+      silent: true
     install_ebpf_agent:
       cmds:
         - |
