Add status stub location in nginx recipe if not present in existing configuration

diff --git a/recipes/newrelic/infrastructure/ohi/nginx/linux.yml b/recipes/newrelic/infrastructure/ohi/nginx/linux.yml
--- a/recipes/newrelic/infrastructure/ohi/nginx/linux.yml
+++ b/recipes/newrelic/infrastructure/ohi/nginx/linux.yml
@@ -58,37 +58,11 @@ preInstall:
       - See https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/nginx-monitoring-integration#config for more info.
 
   requireAtDiscovery: |
-    # extract NGINX status url
-    stub_location=$(sudo nginx -T 2>&1 | grep -ozP "(?s:.*\s)\Klocation(?s).*stub_status" | grep -aoP "\/([^\s]+)")
-    if [ "$stub_location" == "" ]; then
+    # determine whether NGINX status url setting is enabled
+    stub_status_enabled=$(nginx -V 2>&1 | grep -o "with-http_stub_status_module")
+    if [ "$stub_status_enabled" == "" ]; then
       exit 1
     fi
-
-    curledPorts=""
-
-    # split on lines
-    IFS=$'\n'
-    portlines=$(sudo nginx -Tq | grep listen)
-    for line in $portlines; do
-      # we chech the line is not commented
-      if ! echo $line | grep -aoPq "#"; then
-        port=$(echo $line | grep -aoP "\d+")
-
-        # we set this port variable with the surrounded by the hash symbol so we can distinct 20 from 200
-        currentPort="#{$port}#"
-
-        # then we check if it doesn't exist on our curledPorts var
-        if ! echo $curledPorts | grep -qw "$currentPort"; then
-          code=$(curl -I "http://127.0.0.1:${port}${stub_location}" -w %{response_code} -so '/dev/null')
-          if [ $code == "200" ]; then
-            exit 0
-          fi
-          curledPorts+=${currentPort}
-          fi
-        fi
-    done
-
-    exit 1
 
 install:
   version: "3"
@@ -113,11 +87,47 @@ install:
       cmds:
         - |
           stub_location=$(sudo nginx -T 2>&1 | grep -ozP "(?s:.*\s)\Klocation(?s).*stub_status" | grep -aoP "\/([^\s]+)")
+          if [ "$stub_location" == "" ]; then
+            # ask the user if we can add it. if yes proceed, if no exit as unsupported
+            echo -n "An nginx status stub location is required to proceed. Add default status location of /status? Y/N (default: Y)? "
+            read answer
+            echo ""
+            NEW_RELIC_CONTINUE=$(echo "${answer^^}" | cut -c1-1)
+            if [[ -z "$NEW_RELIC_CONTINUE" ]]; then
+              NEW_RELIC_CONTINUE="Y"
+            fi
+            if [[ "$NEW_RELIC_CONTINUE" == "N" ]]; then
+              echo "Exiting the installation"
+              exit 1
+            fi
+
+            # determine which config file we need to add the include into (or maybe not if it's including all the *.conf files)
+            config_location=$(sudo nginx -V 2>&1 | grep -ozP "conf-path=((/*[a-z]*\.*)*)" | cut -d "=" -f 2-)
+            config_directory=$(dirname $config_location)
+
+            # include our newrelic.conf file in the existing config's server block
+            cd $config_directory
+            cp $config_location $config_location.back
+            sudo awk -F "~" '/server ?{.*$/ {if(count++ == 0)$0=$0"\n        # Load configuration files for the New Relic required config. \n        include /etc/nginx/newrelic.d/newrelic.conf;\n"} 1' $config_location.back | sudo tee $config_location > /dev/null
+            sudo rm $config_location.back
+
+            # create newrelic.conf file with our new default status block
+            sudo mkdir newrelic.d -p
+            sudo printf "location = /status {\n      stub_status;\n      allow 127.0.0.1;    # only allow requests from localhost\n      deny all;           # deny all other hosts  \n}\n" > newrelic.d/newrelic.conf
+
+            # reload nginx and check again for the stub location
+            sudo nginx -s reload
+            stub_location=$(sudo nginx -T 2>&1 | grep -ozP "(?s:.*\s)\Klocation(?s).*stub_status" | grep -aoP "\/([^\s]+)")
+            if [ "$stub_location" == "" ]; then
+              exit 1
+            fi
+          fi
 
           port=""
           curledPorts=""
+          statusStubOK=false
           sudo nginx -T | grep listen | while read -r line ; do
-            # we chech the line is not commented
+            # we check the line is not commented
             if ! echo $line | grep -aoPq "#"; then
               port=$(echo $line | grep -aoP "\d+")
 
@@ -128,12 +138,18 @@ install:
               if ! echo $curledPorts | grep -qw "$currentPort"; then
                 code=$(curl -I "http://127.0.0.1:${port}${stub_location}" -w %{response_code} -so '/dev/null')
                 if [ $code == "200" ]; then
+                  statusStubOK=true
                   break
                 fi
                 curledPorts+=${currentPort}
               fi
             fi
           done
+
+          # exit with failed status if the status stub location port is not in our curledPorts var
+          if [ "$statusStubOK" = false ]; then
+            exit 1
+          fi
 
           # Set Defaults
           NR_CLI_STUB_STATUS_URL="http://127.0.0.1:${port}${stub_location}"
