Add error message when nginx integration installation fails due to missing status endpoint

diff --git a/recipes/newrelic/infrastructure/ohi/nginx/linux.yml b/recipes/newrelic/infrastructure/ohi/nginx/linux.yml
--- a/recipes/newrelic/infrastructure/ohi/nginx/linux.yml
+++ b/recipes/newrelic/infrastructure/ohi/nginx/linux.yml
@@ -119,6 +119,7 @@ install:
             sudo systemctl restart nginx
             stub_location=$(sudo nginx -T 2>&1 | grep -ozP "(?s:.*\s)\Klocation(?s).*stub_status" | grep -aoP "\/([^\s]+)")
             if [ "$stub_location" == "" ]; then
+              printf "\n[Error]: Failed to add status location to nginx configuration. Ensure your configuration matches the requirements for New Relic monitoring. \nSee https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/nginx/nginx-integration/#enable-instance for more information. \n" >&2
               exit 1
             fi
           fi
@@ -148,6 +149,7 @@ install:
 
           # exit with failed status if the status stub location port is not in our curledPorts var
           if [ "$statusStubOK" = false ]; then
+            printf "\n[Error]: Failed to find status stub. Ensure your configuration matches the requirements for New Relic monitoring. \nSee https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/nginx/nginx-integration/#enable-instance for more information. \n" >&2
             exit 1
           fi
 
