feat: Nginx recipe: allow user to retry inputData and detect status_module

diff --git a/recipes/newrelic/infrastructure/ohi/nginx/suse.yml b/recipes/newrelic/infrastructure/ohi/nginx/suse.yml
--- a/recipes/newrelic/infrastructure/ohi/nginx/suse.yml
+++ b/recipes/newrelic/infrastructure/ohi/nginx/suse.yml
@@ -36,11 +36,6 @@ validationNrql: "SELECT count(*) from NginxSample where hostname like '{{.HOSTNA
 
 successLinkConfig:
   type: EXPLORER
-  
-inputVars:
-  - name: "NR_CLI_STUB_STATUS_URL"
-    prompt: "NGINX status URL (default: http://127.0.0.1/status)"
-    default: "http://127.0.0.1/status"
 
 preInstall:
   info: |2
@@ -48,37 +43,89 @@ preInstall:
       and configure the applicable extension module:
       - For NGINX Open Source: HTTP stub status module 
       - For NGINX Plus: HTTP status module and HTTP API module
+      - See https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/nginx-monitoring-integration#config for more info.
 
 install:
   version: "3"
   silent: true
-
   tasks:
     default:
       cmds:
+        - task: input
+          vars:
+            MAX_RETRIES: 3
         - task: assert_pre_req
+          vars:
+            NR_CLI_STUB_STATUS_URL:
+              sh: sudo cat /tmp/nginx-ohai-input
         - task: setup
+          vars:
+            NR_CLI_STUB_STATUS_URL:
+              sh: sudo cat /tmp/nginx-ohai-input
+            NR_CLI_STATUS_MODULE:
+              sh: sudo cat /tmp/nginx-ohai-status-module
+        - task: restart
 
-    assert_pre_req:
+    input:
       cmds:
         - |
-          IS_INFRA_INSTALLED=$(sudo ps aux | grep newrelic-infra-service | grep -v grep | wc -l)
-          if [ $IS_INFRA_INSTALLED -eq 0 ] ; then
-            echo "The infrastructure agent is required to install this integration, we recommend going through our guided install path for this pre-requisite which can be found here:  https://docs.newrelic.com/docs/new-relic-guided-installation-overview" >> /dev/stderr
-            exit 1
-          fi
-        - |
-          STUB_STATUS_ENABLED=$(curl {{.NR_CLI_STUB_STATUS_URL}} -s | grep "Active connections:" | wc -l)
-          if [ $STUB_STATUS_ENABLED -eq 0 ] ; then
-            echo "NGINX HTTP status module must be configured for New Relic to collect data. \n - See https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/nginx-monitoring-integration#config for more info." >> /dev/stderr
+          tries=0
+          while [ $tries -lt {{.MAX_RETRIES}} ]; do
+            printf "\nNGINX status URL (default: http://127.0.0.1/status): "
+            read -r input
+            input=${input:-http://127.0.0.1/status}
+            code=$(curl -I $input -w %{response_code} -so '/dev/null')
+            if [ $code == "200" ]; then
+              echo $input > /tmp/nginx-ohai-input
+              chmod 600 /tmp/nginx-ohai-input && sudo chown root:root /tmp/nginx-ohai-input
+              break
+            fi
+            ((tries++))
+            echo "The status url provided $input couldn't be reached. Try again"
+            if [ ! $tries -lt {{.MAX_RETRIES}} ]; then
+              echo "NGINX HTTP status must be configured for New Relic to collect data. \n - See https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/nginx-monitoring-integration#config for more info." >> /dev/stderr
+              exit 2
+            fi
+            echo "Try again"
+          done
+
+      assert_pre_req:
+        cmds:
+          - |
+            IS_INFRA_INSTALLED=$(sudo ps aux | grep newrelic-infra-service | grep -v grep | wc -l)
+            if [ $IS_INFRA_INSTALLED -eq 0 ] ; then
+              echo "The infrastructure agent is required to install this integration, we recommend going through our guided install path for this pre-requisite which can be found here:  https://docs.newrelic.com/docs/new-relic-guided-installation-overview" >> /dev/stderr
+              sudo rm /tmp/nginx-ohai-input
+              exit 1
+            fi
+          - |
+            STATUS_RESPONSE=$(curl {{.NR_CLI_STUB_STATUS_URL}} -s)
+            if [ ! $(echo $STATUS_RESPONSE | grep "Active connections:" | wc -l) -eq 0 ] ; then
+              echo "ngx_http_stub_status_module" > /tmp/nginx-ohai-status-module
+              chmod 600 /tmp/nginx-ohai-input && sudo chown root:root /tmp/nginx-ohai-status-module
+              exit 0
+            fi
+            if [ ! $(echo $STATUS_RESPONSE | grep '"nginx_version"' | wc -l) -eq 0 ] ; then
+              echo "ngx_http_status_module" > /tmp/nginx-ohai-status-module
+              chmod 600 /tmp/nginx-ohai-input && sudo chown root:root /tmp/nginx-ohai-status-module
+              exit 0
+            fi
+            if [ ! $(echo $STATUS_RESPONSE | grep '"nginx"' | wc -l) -eq 0 ] ; then
+              echo "ngx_http_api_module" > /tmp/nginx-ohai-status-module
+              chmod 600 /tmp/nginx-ohai-input && sudo chown root:root /tmp/nginx-ohai-status-module
+              exit 0
+            fi
+            echo "NGINX status must be configured for New Relic to collect data. \n - See https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/nginx-monitoring-integration#config for more info." >> /dev/stderr
+            sudo rm /tmp/nginx-ohai-input
             exit 2
-          fi
 
     setup:
       label: "Installing NGINX integration..."
       cmds:
         - |
           sudo mkdir -p "/etc/newrelic-infra/integrations.d"
+          sudo rm /tmp/nginx-ohai-input
+          sudo rm /tmp/nginx-ohai-status-module
         - |
           sudo zypper -n ref -r newrelic-infra
         - |
@@ -101,7 +148,7 @@ install:
                 status_url: {{.NR_CLI_STUB_STATUS_URL}}
 
                 # Name of Nginx status module OHI is to query against. discover | ngx_http_stub_status_module | ngx_http_status_module | ngx_http_api_module
-                status_module: discover
+                status_module: {{.NR_CLI_STATUS_MODULE}}
 
                 # New users should leave this property as `true`, to identify the
                 # monitored entities as `remote`. Setting this property to `false` (the
