fix: Update recipe to automate nagios plugin install

diff --git a/recipes/newrelic/infrastructure/ohi/nagios/debian.yml b/recipes/newrelic/infrastructure/ohi/nagios/debian.yml
--- a/recipes/newrelic/infrastructure/ohi/nagios/debian.yml
+++ b/recipes/newrelic/infrastructure/ohi/nagios/debian.yml
@@ -63,19 +63,20 @@ install:
             exit 1
           fi
         - |
+          NEW_RELIC_ASSUME_YES="{{.NEW_RELIC_ASSUME_YES}}"
           PLUGINS_EXIST=$(ls /usr/local/nagios/libexec | grep check_users | wc -l)
           if [ $PLUGINS_EXIST -eq 0 ]; then
             echo "[INFO] Nagios plugins not found. Nagios plugins are a prerequisite for this integration." >&2
-          
-            # Prompt user for confirmation
-            printf "Do you want to proceed with downloading and installing Nagios plugins? This involves downloading third-party software not hosted by New Relic. y/n (default: y): "
-            read -r USER_CONFIRMATION
-            USER_CONFIRMATION=${USER_CONFIRMATION:-y}
-          
-            # Check user response
-            if [ "$USER_CONFIRMATION" != "y" ]; then
-            echo "Nagios plugins are required for this integration. Please install them and re-run the installation." >&2
-            exit 3
+                    
+            if [[ "$NEW_RELIC_ASSUME_YES" != "true" ]] ; then                       
+              printf "Do you want to proceed with downloading and installing Nagios plugins? This involves downloading third-party software not hosted by New Relic. y/n (default: y): "
+              read -r USER_CONFIRMATION
+              USER_CONFIRMATION=${USER_CONFIRMATION:-y}
+            
+              if [ "$USER_CONFIRMATION" != "y" ]; then
+                echo "Nagios plugins are required for this integration. Please install them and re-run the installation." >&2
+                exit 3
+              fi
             fi
           
             echo "[INFO] Proceeding with Nagios plugins download..." >&2
