chore: update systemctl check and error message
Here we avoid $?, which doesn't seem to be respected by go-task.  Also here we
update the message and point the user some documentation.

diff --git a/recipes/newrelic/infrastructure/ohi/nagios/rhel.yml b/recipes/newrelic/infrastructure/ohi/nagios/rhel.yml
--- a/recipes/newrelic/infrastructure/ohi/nagios/rhel.yml
+++ b/recipes/newrelic/infrastructure/ohi/nagios/rhel.yml
@@ -48,11 +48,7 @@ install:
     assert_pre_req:
       cmds:
         - |
-          sudo systemctl is-active --quiet newrelic-infra
-          if [ $? -ne 0 ]; then
-            echo "The newrelic-infra agent service is not installed on the host, but is required to install this integration." >> /dev/stderr
-            exit 1
-          fi
+          sudo systemctl is-active --quiet newrelic-infra || (echo "The infrastructure agent is required to install this integration, we recommend going through our guided install path for this pre-requisite which can be found here:  https://docs.newrelic.com/docs/new-relic-guided-installation-overview" >> /dev/stderr; exit 1)
         - |
           PLUGINS_EXIST=$(ls /usr/local/nagios/libexec | grep check_users | wc -l)
           if [ $PLUGINS_EXIST -eq 0 ] ; then
