fix: add preinstall, silent install, and use sample service-checks file

diff --git a/recipes/newrelic/infrastructure/ohi/nagios/rhel.yml b/recipes/newrelic/infrastructure/ohi/nagios/rhel.yml
--- a/recipes/newrelic/infrastructure/ohi/nagios/rhel.yml
+++ b/recipes/newrelic/infrastructure/ohi/nagios/rhel.yml
@@ -31,8 +31,12 @@ logMatch:
 
 validationNrql: "SELECT count(*) from NagiosServiceCheckSample where hostname like '{{.HOSTNAME}}%' FACET entityGuid SINCE 10 minutes ago"
 
-install:
+preInstall:
+  info: |2
+      To capture data from the Nagios integration, you'll first need to meet these prerequisites:
+      - Must have an existing service that conforms to the Nagios Plugin API
 
+install:
   version: "3"
   silent: true
 
@@ -42,7 +46,7 @@ install:
         - task: assert_pre_req
         - task: setup
         - task: restart
-        
+
     assert_pre_req:
       cmds:
         - |
@@ -51,36 +55,29 @@ install:
             echo "The newrelic-infra agent service is NOT installed on the host, but is required to install this integration." >> /dev/stderr
             exit 1
           fi
+        - |
+          PLUGINS_EXIST=$(ls /usr/local/nagios/libexec | grep check_users | wc -l)
+          if [ $PLUGINS_EXIST -eq 0 ] ; then
+            echo "check_users plugin not found in /usr/local/nagios/libexec/ - Please make sure that the plugins are installed." >> /dev/stderr
+            exit 2
+          fi
 
     setup:
-      label: "Installing nagios integration..."
+      label: "Installing Nagios integration..."
       cmds:
         - |
           sudo mkdir -p "/etc/newrelic-infra/integrations.d"
         - |
-          sudo yum update -y
+          sudo yum update -y -q
         - |
-          sudo yum install nri-nagios -y
+          sudo yum install nri-nagios -y -q
         - |
           if [ -f /etc/newrelic-infra/integrations.d/nagios-config.yml ]; then
             sudo rm /etc/newrelic-infra/integrations.d/nagios-config.yml;
           fi
 
           sudo cp /etc/newrelic-infra/integrations.d/nagios-config.yml.sample /etc/newrelic-infra/integrations.d/nagios-config.yml;
-
-        - | 
-          sudo tee /etc/newrelic-infra/integrations.d/service_checks.yml > /dev/null <<"EOT"
-          service_checks:
-            - name: check_users
-              command: ["/usr/local/nagios/libexec/check_users", "-w", "5", "-c", "10"]
-              parse_output: true
-              labels:
-                env: staging
-                key1: val1
-            - name: check_apt
-              command: ["/usr/local/nagios/libexec/check_apt"]
-          EOT
-        - |
+          sudo cp /etc/newrelic-infra/integrations.d/nagios-service-checks.yml.sample /etc/newrelic-infra/integrations.d/service-checks.yml;
           sudo chmod 0600 /etc/newrelic-infra/integrations.d/service_checks.yml
 
     restart:
