refactor(debian): added check for existence of mongodb

diff --git a/recipes/newrelic/mongodb/debian.yml b/recipes/newrelic/mongodb/debian.yml
--- a/recipes/newrelic/mongodb/debian.yml
+++ b/recipes/newrelic/mongodb/debian.yml
@@ -96,8 +96,12 @@ install:
             echo "The newrelic-infra agent service is NOT installed on the host, but is required to install this integration." >> /dev/stderr
             exit 1
           fi
-        # - |
-        #   MONGODB_EXISTS=$(mongo --eval 'db.runCommand({ connectionStatus: 1 })'))
+        - |
+          MONGODB_EXISTS=$(mongo --eval 'db.runCommand({ connectionStatus: 1 })' | grep "ok" | awk '{print $1 $2 $3}')
+          if [ $MONGODB_EXISTS != "ok:1"]; then
+            echo "Cannot estabilish connection to mongodb, please verify that it's installed correctly."
+            exit 2
+          fi
 
     setup:
       label: "Installing mongodb integration..."
