fix: Fail as unsupported when inputs are bad

diff --git a/recipes/newrelic/infrastructure/ohi/cassandra/rhel.yml b/recipes/newrelic/infrastructure/ohi/cassandra/rhel.yml
--- a/recipes/newrelic/infrastructure/ohi/cassandra/rhel.yml
+++ b/recipes/newrelic/infrastructure/ohi/cassandra/rhel.yml
@@ -68,7 +68,7 @@ install:
         - task: input_assert
           vars:
             MAX_RETRIES: 3
-            EXIT130: ""
+            EXIT131: ""
         - task: restart
 
     assert_pre_req:
@@ -159,17 +159,17 @@ install:
           if [[ "$NEW_RELIC_ASSUME_YES" == "true" ]]; then
             NODETOOL_RESPONSE=$(nodetool -p "$NEW_RELIC_CASSANDRA_PORT" -h "$NEW_RELIC_CASSANDRA_HOSTNAME" -u "$NEW_RELIC_CASSANDRA_USERNAME" -pw "$NEW_RELIC_CASSANDRA_PASSWORD" version 2>&1)
             if [ $(echo $NODETOOL_RESPONSE | grep -i "Failed to connect" | wc -l) -gt 0 ]; then
-              EXIT130=" - NEW_RELIC_CASSANDRA_PORT=<port>\n - NEW_RELIC_CASSANDRA_HOSTNAME=<hostname>"
+              EXIT131=" - NEW_RELIC_CASSANDRA_PORT=<port>\n - NEW_RELIC_CASSANDRA_HOSTNAME=<hostname>"
             fi
 
             if [ $(echo $NODETOOL_RESPONSE | grep -Ei "Invalid username or password|Required values.*not provided" | wc -l) -gt 0 ]; then
-              EXIT130=" - NEW_RELIC_CASSANDRA_USERNAME=<jmx_username>\n - NEW_RELIC_CASSANDRA_PASSWORD=<jmx_user_password>"
+              EXIT131=" - NEW_RELIC_CASSANDRA_USERNAME=<jmx_username>\n - NEW_RELIC_CASSANDRA_PASSWORD=<jmx_user_password>"
             fi
           fi
 
-          if [ "$EXIT130" != "" ]; then
-            printf "There is a problem with the required environment variables. Please set the following variable(s) and try again:\n\n$EXIT130\n"
-            exit 130
+          if [ "$EXIT131" != "" ]; then
+            printf "There is a problem with the required environment variables. Please set the following variable(s) and try again:\n\n$EXIT131\n"
+            exit 131
           else
             printf "\n[OK] All checks passed. Installing Cassandra Integration...\n\n"
           fi
