Add pre-req to ngin rhel and suse.

diff --git a/recipes/newrelic/nginx/rhel.yml b/recipes/newrelic/nginx/rhel.yml
--- a/recipes/newrelic/nginx/rhel.yml
+++ b/recipes/newrelic/nginx/rhel.yml
@@ -44,7 +44,24 @@ install:
   tasks:
     default:
       cmds:
+        - task: assert_pre_req
         - task: setup
+
+    assert_pre_req:
+      cmds:
+        - |
+          SERVICE_EXIST=$(sudo systemctl status newrelic-infra.service | grep "Active" | wc -l)
+          if [ $SERVICE_EXIST -eq 0 ]; then
+            echo "The newrelic-infra agent service is NOT installed on the host, but is required to install this integration." >> /dev/stderr
+            exit 1
+          fi
+        - |
+          HTTP_STUB_STATUS_MODULE_EXISTS=$(nginx -V 2>&1 | tr ' ' '\n' | grep -o with-http_stub_status_module | wc -l)
+          STUB_STATUS_ENABLED=$(curl http://127.0.0.1/status -s | grep "Active connections:" | wc -l)
+          if [ $HTTP_STUB_STATUS_MODULE_EXISTS -eq 0 ] || [ $STUB_STATUS_ENABLED -eq 0 ] ; then
+            echo "nginx HTTP status module must be configured for New Relic to collect data. \n - See https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/nginx-monitoring-integration#config for more info." >> /dev/stderr
+            exit 2
+          fi
 
     setup:
       label: "Installing nginx integration..."
@@ -60,13 +77,7 @@ install:
 
           sudo touch /etc/newrelic-infra/integrations.d/nginx-config.yml;
         - |
-          # Check for HTTP stub status module existing and configured
-          HTTP_STUB_STATUS_MODULE_EXISTS=$(nginx -V 2>&1 | tr ' ' '\n' | grep -o with-http_stub_status_module | wc -l)
-          STUB_STATUS_ENABLED=$(curl http://127.0.0.1/status -s | grep "Active connections:" | wc -l)
-
-          if [ $HTTP_STUB_STATUS_MODULE_EXISTS -gt 0 ] && [ $STUB_STATUS_ENABLED -gt 0 ] ; then
-
-            sudo tee -a /etc/newrelic-infra/integrations.d/nginx-config.yml > /dev/null <<"EOT"
+          sudo tee -a /etc/newrelic-infra/integrations.d/nginx-config.yml > /dev/null <<"EOT"
           integration_name: com.newrelic.nginx
 
           instances:
@@ -107,8 +118,6 @@ install:
                 # status_url is used to identify the monitored entity to which the inventory will be attached.
                 status_url: http://127.0.0.1/status
           EOT
-          else
-            echo -e "[Error]: nginx HTTP status module must be configured for New Relic to collect data. \n - See https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/nginx-monitoring-integration#config for more info."
+        - |
+          sudo systemctl restart newrelic-infra.service
 
-          fi
-        - sudo systemctl restart newrelic-infra.service
