feat(debian): added assert pre req step for checking if nr infra agent is running

diff --git a/recipes/newrelic/elasticsearch/debian.yml b/recipes/newrelic/elasticsearch/debian.yml
--- a/recipes/newrelic/elasticsearch/debian.yml
+++ b/recipes/newrelic/elasticsearch/debian.yml
@@ -56,7 +56,17 @@ install:
   tasks:
     default:
       cmds:
+        - taks: assert_pre_req
         - task: setup
+
+     assert_pre_req:
+      cmds:
+        - |
+          SERVICE_EXIST=$(sudo systemctl status newrelic-infra.service | grep "Active" | wc -l)
+          if [ $SERVICE_EXIST -eq 0 ]; then
+            echo "The newrelic-infra agent service is NOT installed on the host, but is required to install this integration." >> /dev/stderr
+            exit 1
+          fi
 
     setup:
       label: "Installing elasticsearch integration..."
