Add input validation for elasticsearch recipes. Expand RHEL to cover AWS older linux, fix restart for debian/suse to cover multiple init methods.

diff --git a/recipes/newrelic/infrastructure/ohi/elasticsearch/debian.yml b/recipes/newrelic/infrastructure/ohi/elasticsearch/debian.yml
--- a/recipes/newrelic/infrastructure/ohi/elasticsearch/debian.yml
+++ b/recipes/newrelic/infrastructure/ohi/elasticsearch/debian.yml
@@ -34,6 +34,7 @@ inputVars:
     prompt: "ElasticSearch Username"
   - name: "NR_CLI_API_PASSWORD"
     prompt: "ElasticSearch Password"
+    secret: true
   - name: "NR_CLI_API_HOSTNAME"
     prompt: "ElasticSearch Hostname (default: localhost)"
     default: "localhost"
@@ -47,7 +48,7 @@ inputVars:
     prompt: "Use SSL to connect? (false/true)"
     default: false
   - name: "NR_CLI_API_CA_BUNDLE_DIR"
-    prompt: "SSL certificate Directory (if applicable)"
+    prompt: "SSL Certificate Directory (if applicable)"
   - name: "NR_CLI_API_CA_BUNDLE_FILE"
     prompt: "SSL Certificate File (if applicable)"
 
@@ -74,6 +75,22 @@ install:
           if [ $IS_INFRA_INSTALLED -eq 0 ] ; then
             echo "The infrastructure agent is required to install this integration, we recommend going through our guided install path for this pre-requisite which can be found here:  https://docs.newrelic.com/docs/new-relic-guided-installation-overview" >> /dev/stderr
             exit 1
+          fi
+        - |
+          if [ ! -f {{.NR_CLI_CONFIG_PATH}} ]; then
+            echo "[Error]: The ElasticSearch config file cannot be found at '{{.NR_CLI_CONFIG_PATH}}'. See https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/elasticsearch-monitoring-integration#comp-req for more info." >> /dev/stderr
+            exit 9
+          fi
+        - |
+          if [ {{.NR_CLI_API_USE_SSL}} == true ]; then
+            if [ ! -d {{.NR_CLI_API_CA_BUNDLE_DIR}} ]; then
+              echo "[Error]: SSL is true but no certificate bundle directory exist at '{{.NR_CLI_API_CA_BUNDLE_DIR}}'. See https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/elasticsearch-monitoring-integration#comp-req for more info." >> /dev/stderr
+              exit 11
+            fi
+            if [ ! -f {{.NR_CLI_API_CA_BUNDLE_DIR}}/{{.NR_CLI_API_CA_BUNDLE_FILE}} ]; then
+              echo "[Error]: SSL is true but no client certificate file exist at '{{.NR_CLI_API_CA_BUNDLE_DIR}}/{{.NR_CLI_API_CA_BUNDLE_FILE}}'. See https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/elasticsearch-monitoring-integration#comp-req for more info." >> /dev/stderr
+              exit 12
+            fi
           fi
 
     setup:
@@ -103,12 +120,11 @@ install:
                 cluster_environment: staging
                 config_path: {{.NR_CLI_API_CONFIG_PATH}}
                 hostname: {{.NR_CLI_API_HOSTNAME}}
-                local_hostname: localhost
                 username: {{.NR_CLI_API_USERNAME}}
                 password: {{.NR_CLI_API_PASSWORD}}
                 port: {{.NR_CLI_API_PORT}}
                 timeout: 30
-                use_ssl: {{.NR_CLI_API_USE_SSL}}
+                use_ssl: false
                 indices_regex:
                 collect_indices: true
                 collect_primaries: true
@@ -124,12 +140,11 @@ install:
                 cluster_environment: staging
                 config_path: {{.NR_CLI_API_CONFIG_PATH}}
                 hostname: {{.NR_CLI_API_HOSTNAME}}
-                local_hostname: localhost
                 username: {{.NR_CLI_API_USERNAME}}
                 password: {{.NR_CLI_API_PASSWORD}}
                 port: {{.NR_CLI_API_PORT}}
                 timeout: 30
-                use_ssl: {{.NR_CLI_API_USE_SSL}}
+                use_ssl: true
                 ca_bundle_dir: {{.NR_CLI_API_CA_BUNDLE_DIR}}
                 ca_bundle_file: {{.NR_CLI_API_CA_BUNDLE_FILE}}
                 indices_regex:
